### ISSUE TITLE
WCAG: Hoppe over blokker (Nivå A)

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#10]
## Description
Når blokker med innhold blir presentert over flere sider skal brukeren ha mulighet til å hoppe over det ved hjelp av tastaturnavigasjon. Dette er ofte løst med en knapp som blir synlig ved første tab trykk på. Om den blir klikket på hopper fokus til hovedinnholdet på nettsiden. 

Tidligere har vi ikke lagt til en slik knapp da vi ikke har hatt en bolk med elementer før hovedinnholdet. Men nå har vi flere knapper og en navigasjonsbar vil også bli inkludert i mange apper. Det vil da være mye repeterende for en bruker og gå gjennom for hver nye side i appen. 

I sammenheng med dette må vi se på om vi skal få inn "landmarks" i løsningen vår. Denne teknikken er beskrevet her: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11.html

[Tilsynets forklaring av 2.4.1 Hoppe over blokker](https://www.uutilsynet.no/wcag-standarden/241-hoppe-over-blokker-niva/103)

## Screenshots
Eksempel fra Altinn.no
![Skjermbilde 2022-04-08 kl  09 34 18](https://user-images.githubusercontent.com/33222679/162387029-71f9b488-8ca9-47b4-ad30-c3a5baad1118.png)

## Specification tasks

- [ ] Development tasks are defined

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by nkylstad** [comment]
Tested ok in Chrome, Edge and Firefox.
