### ISSUE TITLE
Gruppe  - openByDefault

### ISSUE THREAD

**Issue by madsenandreas** [Altinn/app-frontend-react#1038]
### Description of the bug

Ved versjon 3.58.2 fikk man opp gruppen ved å legge til:
        "type": "Group",
        "edit": {
          "openByDefault": true
        },
Etter denne versjon forsvinner gruppen helt fra websiden, kommer kun tilbake om man sletter edit.

### Steps To Reproduce

Lag en gruppe med konfigurasjon over

**Comment by olemartinorg** [comment]
Hei @madsenandreas! Jeg sliter med å reprodusere problemet. Kunne du potensielt lagt inn en lenke til en app hvor du opplever dette problemet, sammen med en beskrivelse av hvor i skjemaet man skal gå for å se dette?

Merk at `openByDefault` er en opsjon som kun gir mening i en _repeterende gruppe_, som vil si at man må sette en opsjon med `"maxCount": 2` eller flere. Det er uklart fra feilrapporten om dette gjelder en repeterende gruppe eller ei.

**Comment by madsenandreas** [comment]
Hele gruppen er:
`      {
        "id": "repeating-group-matematikk-1t",
        "type": "Group",
        "edit": {
          "openByDefault": true
        },
        "children": [
          "layout-elevOgForesatte-elev-elevGruppe-matematikk-1t",
          "layout-elevOgForesatte-elev-elevFoedselsnummer-matematikk-1t",
          "layout-elevOgForesatte-elev-elevEtternavn-matematikk-1t",
          "layout-elevOgForesatte-elev-elevFolkeregisteret-resultatAvhenting-matematikk-1t",
          "layout-elevOgForesatte-elev-elevFornavn-matematikk-1t",
          "layout-elevOgForesatte-elev-elevAdresse-matematikk-1t",
          "layout-elevOgForesatte-elev-elevEpost-matematikk-1t",
          "layout-elevOgForesatte-elev-elevTelefonnummer-matematikk-1t",
          "layout-h3-eleven-under-18-matematikk-1t",
          "layout-h3-Foresatt1-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt1Foedselsnummer-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt1Etternavn-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt1Folkeregisteret-resultatAvhenting-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt1Fornavn-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt1Adresse-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt1Epost-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt1Telefon-matematikk-1t",
          "layout-h3-Foresatt2-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt2Foedselsnummer-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt2Etternavn-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt2Folkeregisteret-resultatAvhenting-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt2Fornavn-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt2Adresse-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt2Epost-matematikk-1t",
          "layout-elevOgForesatte-foresatte-foresatt2Telefon-matematikk-1t"
        ],
        "maxCount": 20,
        "tableHeaders": [
        ],
        "dataModelBindings": {
          "group": "elevOgForesatte"
        },
        "hidden": ["or",
          ["equals", ["dataModel", "valgtTilbud"], "tosprakelig"],
          ["equals", ["dataModel", "valgtTilbud"], "ukrainsk"]
        ]
      },
`
tt02: https://udir.apps.tt02.altinn.no/udir/digilaer-registrering-altinn3/

Du kan gå til bunn av siden og velge ett tilbud så trykke neste. Da skal det komme opp en side uansett valg som har en gruppe i seg.

3.58.2:
![image](https://user-images.githubusercontent.com/32479865/227498577-6f1f7cd6-d4e6-4d53-a48f-2902db0cfd1a.png)
Etter 3.58.2
![image](https://user-images.githubusercontent.com/32479865/227498745-dab3495b-4aa5-4716-b089-b533c7a7b6f9.png)
