### ISSUE TITLE
Language selector options are not translated

### ISSUE THREAD

**Issue by lasseklovstad** [Altinn/app-frontend-react#1043]
### Description of the bug

If you have added custom language files their translations are not shown. If the app is stateless it helps to refresh the page for some reason. It seemes to be related to this issue i think: https://github.com/digdir/designsystem/issues/180

### Steps To Reproduce

1. Go to an app with translations
2. Open the language selector
3. the options are not translated

### Additional Information

![image](https://user-images.githubusercontent.com/43168787/227461413-e6506980-89c5-4394-8c45-d403c92aa5ce.png)

The textresources are probably fetched after the languageSelector has been rendered so the options will only use the key instead of the textresources value.

**Comment by bjosttveit** [comment]
Huh, the component should rerender if the textresources change. Do you have an app with custom languages I can take a look at?

**Comment by lasseklovstad** [comment]
@bjosttveit if you want to see the behavior: https://udir.apps.tt02.altinn.no/udir/pbu-test-anonym and username: t-gangs-105 password: srxn9

**Comment by bjosttveit** [comment]
Ahh, so it shows up when selected but not in the dropdown, weird!
![image](https://user-images.githubusercontent.com/47412359/227492984-e5cf2eb2-b0c1-478a-8893-e35e87fc9150.png)

**Comment by lasseklovstad** [comment]
I changed the version of react app frontend to 3.58.0 and that works: 
![image](https://user-images.githubusercontent.com/43168787/227493711-7693446d-dbdb-4143-b47f-821fad681c1f.png)

**Comment by bjosttveit** [comment]
Yeah that component was recently switched out to use digdir/designsystem

**Comment by bjosttveit** [comment]
Weird, I managed to reproduce this in my own app. But only by omitting the language name in some resource files. It worked for me as long as each language name was defined in all of the resource files.

**Comment by lasseklovstad** [comment]
Interessting I can try that!

**Comment by lasseklovstad** [comment]
That doesn't seem to help for me... It seems wierd that it has to be defined in all the resourcefiles because it just fetches one language resource file at a time?

It could behave different in local development. Our demoapplication show it correct after a refresh: https://udir.apps.tt02.altinn.no/udir/pbu-test-demo?survey=survey-5-aarstrinn5

**Comment by bjosttveit** [comment]
That link worked without refresh for me

**Comment by lasseklovstad** [comment]
This seemes to be fixed
