### ISSUE TITLE
Repeating groups with openByDefault steals focus when empty and dataProcessWrite returns true.

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-frontend-react#1053]
A simple (possible minimal) test app is provided at https://altinn.studio/repos/xivne/test-repeating-group-help

https://user-images.githubusercontent.com/131616/227946436-8e38d750-c8a2-4f98-924c-24305eac7dbe.mp4

### Requirements for this to happen
* The group needs to define `edit.openByDefault = true`
* One of the elements in the group needs to have a `textResourceBindings.help` defined
* `dataProcessWrite` needs to return `true`
* the group needs to be empty and have a single element open by the `openByDefault` rule

1. Try to edit any other field.
2. See that focus jumps directly to the Help icon while typing.

One cause of the error seems to be located in [GroupContainer.tsx](https://github.com/Altinn/app-frontend-react/blob/63288758b4c0e2b28879cbce67d9a38ccc2f224f/src/features/form/containers/GroupContainer.tsx#L113-L117) because we use the `onClickAdd` in a lazy effect, so that every clean render, first have an empty table, and then renders an empty element, instead of always rendering the empty element. This does not explain why the `Help` icon steals the focus

```typescript
  useEffect(() => {
    if (edit?.openByDefault && repeatingGroupIndex === -1) {
      onClickAdd();
    }
  }, [edit?.openByDefault, onClickAdd, repeatingGroupIndex]);
```

**Comment by ivarne** [comment]
I updated the title on this. Would be great to get some feedback on possible timing of

**Comment by ivarne** [comment]
@olemartinorg The app https://altinn.studio/repos/xivne/test-repeating-group-help isn't fixed on current app-frontend-react main branch. The behaviour is changed though. Now the group closes when `ProcessDataWrite` returns `true`. That is still useless behaviour. Can you reopen?

**Comment by olemartinorg** [comment]
Sorry about that! I didn't intend to close this issue (I think github read a bit much into my comment that #1120 "might fix" this issue).

Looking into this, along with #1089 this sprint.

**Comment by ivarne** [comment]
Yes, you need to write `might fix the problem in #`

Anyways, the auto closing of repeating groups does not happen anymore, so I'm not sure what caused that issue.
