### ISSUE TITLE
Give the user a warning before deleting a row in the repeating group

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#106]
## Description
If the user wants to delete a row from the table we dont give them a warning before deleting. (Are you sure you want to do this) 
When working with small groups this may not be a big issue, but we see several cases of large repeating groups. One wrong click from the user in those cases could cause a lot of frustration. 

Could be solved with a popover asking the user if they really want to delete the row.

## Specification tasks

- [ ] Design sketches
- [ ] Standard text in NB, NN and EN

**Comment by olemartinorg** [comment]
I guess the trendy approach is to delete and then provide an option to roll back changes for a limited time if the user regrets their choice.

I'm currently implementing [#7659](https://github.com/altinn/altinn-studio/issues/7659) where attachments uploaded in the row have to be deleted before the row deletion is considered successful. That works fine with a confirmation before deletion, but should we implement a 'soft deletion' with the option to roll back deleted attachments, it might lead to a very strange UX whenever deletion of attachments fail.
