### ISSUE TITLE
Frontend does not ignore `required` validations from backend

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-frontend-react#1062]
### Description of the bug

Apps that enable `"RemoveHiddenDataPreview"` gets the benefit of backend validation of components that are marked `"required": true` (or an expression that evaluates to true). This is great because it ensures that users that open devtools, or deliver schema using the API, also is forced to answer all the required questions before submitting.

A problem is that backend during validation does not know what language the user wants their messages, so it can't really say anything more than `required` and indicate the field and component that triggered the error. I suggest to improve it somewhat in https://github.com/Altinn/app-lib-dotnet/pull/217, but as frontend already generates great warnings for empty required fields, the result will always be a duplicated validation message. I think the best solution is to just ignore any validation error with `"code": "required"` so that frontend can handle required independent of backend. (there probably need to be some way to show the error in case frontend thinks the instance is OK, but backend still thinks required values are missing).

 
![image](https://user-images.githubusercontent.com/131616/228529065-507fbd09-5467-4cf9-bf15-2e756dfbd2cc.png)

### Steps To Reproduce

1. Enable `"RemoveHiddenDataPreview"`
2. Add components with `"required"` to the schema
3. Trigger validation with empty required components
4. See that you get double error messages for required where one just states `TODO required`

**Comment by ivarne** [comment]
@RonnyB71 @olemartinorg I'd like to be able to resolve this mess with `TODO required` showing up in frontend, because I feel it has my name written all over it. Any ideas/preferences?

I currently see a few possible solutions:
1. Add default translation text for `TODO required`, or just change the text to remove `TODO` (easy, but does not solve the problem that frontend also does this validation, and it causes duplicate errors for users.)
2. Ignore `"code": "required"` validations in frontend in redux. (there would need to be some way to show the errors before submitting in case the validation in frontend works differently and OK in frontend fails in backend.)
3. Be intelligent in frontend on display, and ensure that only a single `required` validation is shown to the user, and obviously prefer the pretty client side one with proper translation and included question text.

**Comment by olemartinorg** [comment]
I'd prefer number 2 as a temporary solution, but with that said, the whole validations system is due for an overhaul (and I think the plan is to start discussing solutions there very soon). I think it's better to look into the whole problem area instead of playing whack-a-mole with every bug in this category right now.

**Comment by olemartinorg** [comment]
Workaround has been manually tested and verified to work. 🥳 Thanks!

**Comment by olemartinorg** [comment]
I think it's time to close this one, and live with the workaround we already have. It is even less temporary now than it was back when we started talking about it as temporary.. 😉

As for the overhaul: https://github.com/Altinn/app-template-dotnet/issues/180
