### ISSUE TITLE
Duplicate error messages when combining expressions and custom validations

### ISSUE THREAD

**Issue by torbjokv** [Altinn/app-frontend-react#1066]
### Description of the bug

![image](https://user-images.githubusercontent.com/554713/228760203-494146b9-6910-4819-b94b-4d315674aa6b.png)
I have multiple pages where only one show and they all have an input that references the same data field. When applying custom validation, the the front-end does not hide messages for the hidden pages.

### Steps To Reproduce

- Create three pages where only one is showing by using page-level expressions
- Add a input to each page and map to the same data field
- Add custom validation for the field
- Try to send

See example here https://altinn.studio/repos/t_kvaale/validatepage-duplicates

### Additional Information
Test to see if this is already fixed as part of evaluating expressions.

**Comment by bjosttveit** [comment]
Appears to be fixed by #1281 

![Image](https://github.com/Altinn/app-frontend-react/assets/47412359/3b202b9e-1ce0-4c03-8a17-f264308100dc)
