### ISSUE TITLE
PDF: Mulighet for å printe hele skjema uten å måtte sende inn skjema

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1083]
### Description

Slik det er i dag så må en sende inn skjema før en kan få printet ut et helt skjema.
Man kan legge inn en printknapp på sidene men den printer bare siden man står på.

Man ønsker å kunne printe hele skjema også før man sender inn skjema, dvs for eksempel allerede på side 1, dette for å kunne printe ut og skaffe seg en oversikt over hva som skal besvares i skjema.

**Comment by StianVestli** [comment]
org/ssb

**Comment by ivarne** [comment]
Man bør tenke litt på hvordan dette skal virke sammen med dynamikk. Det blir ofte mange spørsmål som ikke er synlige ennå før man har svart på onde er relevant.

**Comment by bjosttveit** [comment]
Dette ble lagt til i https://github.com/Altinn/app-frontend-react/pull/2710
