### ISSUE TITLE
Undesirable jumping to the first field in a repeating group on certain occasions

### ISSUE THREAD

**Issue by akselhmadslien** [Altinn/app-frontend-react#1089]
### Description of the bug

The jumping to the first field in repeating groups happens on at least two occasions. Both are described below:

### When opening a new app while having `"openByDefault": true,` in the repeating group. 
This can be viewed in this video from the app https://altinn.studio/repos/krt/krt-3010a-1/src/commit/5dfd65217ab96075d37740deffe6236ea0fc6029 

https://user-images.githubusercontent.com/113341457/231501166-2b6d0fe3-1421-416f-ad91-2c00d4e13b8f.mp4

The behaviour can also be seen in https://altinn.studio/repos/krt/krt-1230a-1/src/commit/3259c1532c9ce516aca2657d832e476aaec4397c

### When triggering dynamic behaviour from components inside the repeating group. 
In the video the hidden-property of field 6.4 is dependent on the value of 6.2. When the video is filmed I used the "component"-type as the "Function name" in the dynamic expression, but I got the same behaviour when using "dataModel".
The video is from the same app as the previous (https://altinn.studio/repos/krt/krt-3010a-1/src/commit/5dfd65217ab96075d37740deffe6236ea0fc6029)

https://user-images.githubusercontent.com/113341457/231504979-0d6efccb-62e1-4b99-9e6b-e0645ea13a15.mp4

The same behaviour can be viewed in https://altinn.studio/repos/krt/krt-3000a-1/src/commit/688de29c1ae2c41d9572be25530b5ec80ecf102f, but is not as obvious, and is harder to obtain due to a larger app

### Steps To Reproduce

1. Clone the repository https://altinn.studio/repos/krt/krt-3010a-1/src/commit/5dfd65217ab96075d37740deffe6236ea0fc6029
2. Start the app as an organization (Observe case 1)
3. Go to field 6.2 in the repeating group and select "Det gjelder opphør på avtale" (Observe case 2)

**Comment by ivarne** [comment]
See also
* https://github.com/Altinn/app-frontend-react/issues/1053
* https://github.com/Altinn/app-frontend-react/issues/1060

The issue is still that `openByDefault` uses the `onClickAdd()` function in a `useEffect` so that the row "steals" focus. instead of just silently adding an empty row when the repeating group is rendered with no rows in the data model.

**Comment by akselhmadslien** [comment]
Case 2 seems to be solved. Case 1 still unresolved

**Comment by RonnyB71** [comment]
@olemartinorg rumors says that you already have done some work in this area that resolves this issue - can you verify?

**Comment by olemartinorg** [comment]
@RonnyB71 Yup, in #1120. I didnt deliberately try to fix this bug, but I changed the behaviour slightly.

**Comment by ivarne** [comment]
It still jumps to the first field in a repeating group on master. This is not correct behavior when the row is opened by "openByDefault"
