### ISSUE TITLE
How should our state look like and is redux the right state management tool for us?

### ISSUE THREAD

**Issue by framitdavid** [Altinn/app-frontend-react#1096]
We should find out how our state should look like and how it can be structured to simplify our implementations. Is Redux the right tool for our state or should we use something else? To find out which state tool we should use we need to know how our state should be structured. 

Ole Martin has written some great thoughts in [#345](https://github.com/orgs/Altinn/projects/39/views/6?pane=issue&itemId=12144642) about the restructure the Redux State and today's issues.

This issue is meant for analysis and finding out how we want our state to look like and what needs to be done to achieve it.

**Questions that should be asked**
* Are we happy with the format we get the layouts from the backend or could it be changed to simplify the frontend?
* How should the state look to make validation easier? How should we do validation between the frontend and backend? Will this affect how our state should be structure?
*  Should the client-side and data state be merged together or should these be two different things?

**Comment by RonnyB71** [comment]
Partially covered by #1175 and #1094. We need to look further into the remaining parts of this issue.

**Comment by olemartinorg** [comment]
Redux is no longer a dependency in v4, so I guess the answer is 'no'. :partying_face: Closing this issue as done.
