### ISSUE TITLE
Repeating groups: Muligheten til å sette "required" og "minCount"

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1098]
### Description

Slik det er i dag så finnes det ingen enkel mulighet for at man kan stoppe brukeren for å ikke levere data i en repgruppe.
Dette blir enda mer viktig der man har gruppe i gruppe og man vil splitte opp besvarelsene i flere sider.
Vi ønsker at man skal kunne sette "required": true på lik linje som på andre komponeter, med støtte fra dynamikk. 
Slik at bruker blir stoppet hvis en har satt "required": true på en repeterende gruppe og bruker ikke har angitt noe data.
Vi ønsker og å kunne sette "minCount" på lik linje som "maxCount" slik at en kan styre at man feks skal ha minimum 3 rader i gruppa før en kan gå videre.

Denne saken her henger jo litt sammen med dette: https://github.com/Altinn/altinn-studio/issues/10184

**Comment by StianVestli** [comment]
org/ssb

**Comment by StianVestli** [comment]
Denne må ta hensyn til at man kan ha skjulte rader i gruppa som da ikke vises. Hvis minCount er satt til 0 så må minst en rad være synlig.

**Comment by Magnusrm** [comment]
Closing this because the feedback on required updates to the functionality are described in issue: https://github.com/Altinn/app-frontend-react/issues/1276
