### ISSUE TITLE
Store the display value of a selected codelist entry in the datamodel

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#1104]
### Description

Codelists are connected to checkboxes, radiobuttons and dropdowns and consist of a key/value pair. Today only the key is persisted when these fields are connected to the data model.There are however several cases where you would like to store the actual text displayed to the user as well in order to reference that field later in the form. This can be achieved today by doing an additional lookkup on DataProcessWrite, but this requires C# and extra complexity just for storing an already known value.

### Additional Information
This should not be solved using a | (or other symbol) and store both values in the same field as this only pushes complexity further down the processing chain.

Blocked by: https://github.com/Altinn/app-frontend-react/issues/1175

Possible solutions:
1. Map the text value to data model
2. Allow components as data source for a text resource as this would allow for formatted values in texts.

### Acceptance Criterias

- [ ] Ability to configure a separate field for storing the text value of a selected codelist entry
- [ ] Selected text value is stored in the selected field

**Comment by ivarne** [comment]
One solution might be to have something like
```json
{
    "type": "RadioButtons",
    "dataModelBindings":{
        "simpleBinding": "normal.store.of.key",
        "valueBinding": "additional.store.of.translated.tekst.shown"
    }
}
```

**Comment by olemartinorg** [comment]
I agree with @ivarne, but I'll add that it feels a bit redundant to include the word `binding` everywhere. A `simpleBinding` seems to always mean that the value is bound as a string value, so in a way I think it should just be called `string`, or at the very least just `simple`, but it's easy to see in hindsight. For this new binding, I think we should use `label` as a key, as that's the term we use in option lists.

So:
```json
{
    "type": "RadioButtons",
    "dataModelBindings":{
        "simpleBinding": "normal.store.of.key",
        "label": "additional.store.of.translated.tekst.shown"
    }
}
```

**Comment by olemartinorg** [comment]
Yup, I think we should have both! The expression for looking up the display value of a component would be nice, but at the same time that display value might not be very machine readable. I think part of the point of having this in the data model is that it can be extracted and processed in backend code (or on the receiving end when the form is submitted).

One more thing Ronny reminded me about today: This probably requires us to map to more list-like structures in the data model. For a checkbox group, comma-separated *option values* might work, but *option labels* are far more likely to contain commas (as they are meant to be human readable). Making this work smoothly might require us to know more about the data model and store the display values properly (see #990).

**Comment by bjosttveit** [comment]
Solution 2 is kind of possible now since #1341 . You can now get the formatted value of any component including the label of a selected code list using the new `displayValue` expression. So if the use-case is simply to display the formatted value of a code list in a text it can be achieved using:

```json
{
  "textResourceBindings": {
    "title": ["concat", ["text", "selectedColor"], ": ", ["displayValue", "radio-button-component"]]
  }
}
```

Which would result in something like
```
Farge valgt: Blå
```

**Comment by adamhaeger** [comment]
Putting this on blocked as I might have discovered a bug in the PATCH while working on this.

If you add an subtract a value in a list, and this ends up in the PATCH request we end up with this payload:

![Image](https://github.com/Altinn/app-frontend-react/assets/1534950/ed54933d-caeb-4f58-94e3-c17a723d75b2)

As you can see, value 4 was first deleted, but then we try to insert a value in the same position.

We end up with this response from backend:


![Image](https://github.com/Altinn/app-frontend-react/assets/1534950/1c5dc98c-ce0d-4e42-a180-699a4f492ec8)
