### ISSUE TITLE
Repeating groups: "openByDefault" åpner ikke gruppen som deles på flere sider

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1111]
### Description of the bug

Har du repeterende grupper som ligger under hverandre i datamodellen. Dvs en foreldre gruppe som har en annen gruppe under seg. Når jeg da viser disse gruppene på en side der jeg kun viser forelder nivået, og viser foreldre og barn på side 2 så får jeg ikke den til å åpne som default med settingen "openByDefault": "first"

![image](https://user-images.githubusercontent.com/91887041/233321986-be35b1c6-d9cd-4936-bf8b-7607404e7ed9.png)

### Steps To Reproduce

Dra ned https://altinn.studio/repos/stian.vestli/ra0244-01.git commit aeef9954209c2e64090d573de152bc9111ae6dfd

Det er side7 og side8 som feilen ligger.

### Additional Information
Blocked by: https://github.com/Altinn/app-frontend-react/issues/1175

**Comment by bjosttveit** [comment]
Forslag til løsning: https://github.com/Altinn/app-frontend-react/pull/1106

**Comment by olemartinorg** [comment]
Det ligger noen kommentarer i #1106 som Bjørnar lenket til over, og jeg skrev litt videre om disse tankene i #1147 over. Lenke til den kommentaren (som er veldig relevant her også):
- https://github.com/Altinn/app-frontend-react/issues/1147#issuecomment-1543817029

**Comment by StianVestli** [comment]
https://altinn.slack.com/archives/C02EVE4RU82/p1684144686856809

**Comment by RonnyB71** [comment]
Will be solved by https://github.com/Altinn/app-frontend-react/issues/1175
