### ISSUE TITLE
Summary: Oppsummeringssiden stopper ikke ved validering backend i alle situasjoner

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1112]
### Description of the bug

Det kan se ut som at validering backend ikke trigges som det skal når man er på en annen side, feks oppsummering.  Har backend valideringe som feiler ved sjekk på oppsummeringssiden backend men det dukker ikke opp noen feil noe sted. Slik ser da valideringen ut: 
![image](https://user-images.githubusercontent.com/91887041/233334000-ddac8f80-85dd-4316-ad0f-c3666208551f.png)

Ser og ut til at "tilbake til oppsummering" sender deg tilbake til oppsummering selv om det er valideringer bak som settes som feil, den burde vel ikke gjøre det?
![image](https://user-images.githubusercontent.com/91887041/233333869-073a485e-0562-4423-9bf6-d2719c914dff.png)

Feilen her settes i en repeterende struktur og da på en undergruppe som mangler blant annet. Denne valideringen funker som den skal på selve siden(side8) men ikke når man setter feilen fra oppsummeringssiden.
Her kan en se åssen dette ser ut:

![valideringfeiloppsummering](https://user-images.githubusercontent.com/91887041/233340982-6a5b0649-efcd-428e-b544-d82833e895c0.gif)

### Steps To Reproduce

Dra ned https://altinn.studio/repos/stian.vestli/ra0244-01.git commit aeef9954209c2e64090d573de152bc9111ae6dfd

Kjør gjennom skjema som på her:

![valideringfeiloppsummering](https://user-images.githubusercontent.com/91887041/233341021-74492338-14a3-4025-b21e-2409bcad95d0.gif)

**Comment by rvessb** [comment]
https://altinn.slack.com/archives/C02EVE4RU82/p1681900620647079

**Comment by rvessb** [comment]
Denne utfordringen gjelder ikke kun for validering backend, jeg har samme problem i skjema som kun har frontend-validering.
Det er et problem at det ikke kjøres "sidevalidering" på knappen "Tilbake til oppsummering" (eller at dette i det minste kan settes på som et option. Det gjør at man får lov til å gå tilbake til oppsummering til tross for at man har innført en feil på den siden man står på. 

https://github.com/Altinn/app-frontend-react/assets/43333852/b5452aab-e1ab-4299-ba8a-4d0b3dc29739
