### ISSUE TITLE
Support iframe to show content

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#1116]
### Description

Valgdirektoratet wants to show the election card as html in a iframe rather than todays solution where the raw html is fetched and embedded into the app ref. https://github.com/Altinn/altinn-support-private/issues/1032.

### Additional Information
It's not clarified if this is via the src or srcdoc attribute on the iframe element.

15.05.2023
srcdoc should be prioritized as we will fetch the html from Altinn 2 inbox.
Example HTML: 

[RESULT_DOUBLE_ADDRESS_LINE.html.txt](https://github.com/Altinn/app-frontend-react/files/11477779/RESULT_DOUBLE_ADDRESS_LINE.html.txt)

**Comment by framitdavid** [comment]
To use the "src" attribute, we need a URL for an external resource to load into the "<iframe/>". Instead, using "srcdoc" allows us to retrieve HTML and embed it into the "<iframe/>". Based on the issue description, it appears we can already use "srcdoc" to retrieve the desired HTML for embedding.

Security is a concern. Currently, the HTML is fetched and directly appended to the front-end without using an "<iframe/>". This means that the HTML can access our cookies, local storage, and other parts of our document, posing a security risk if we don't trust the HTML/external source. If all important cookies are HTTP-only, it might not be a security issue. However, we should consider whether we trust the external resource or the HTML we're fetching. We could also add the "sandbox" attribute to the "<iframe/>" to disallow features that could be a security risk, such as plugins, local storage, form submissions, and cookies.

This approach may be straightforward for Valgdirektoratet, but it's unknown who will use this feature in the future or what they'll embed into our "<iframe/>". 😄

**Comment by ivarne** [comment]
Httponly cookies will not make untrusted html safe, because they can still use javascript and use fetch to call any api they want and the browser will add the cookies.

Apps currently share domain (same origin) and have full control over html/js, so we really need to trust that app developers don’t try to do mischief to read/modify data in other apps for their users.
