### ISSUE TITLE
Feil på skjemaet https://digdir.apps.altinn.no/digdir/be-om-api-nokkel/

### ISSUE THREAD

**Issue by GeirHerbertHorn** [Altinn/app-frontend-react#1126]
### Description of the bug

Når man fyller ut dette skjemaet og kommer til knappen Send inn.
Kommer siden opp der man skal Godkjenn egenerklæring og send inn.
Når man klikker på denne blir skjemaet stående flere sekunder før kvitterings siden kommer opp.

Hvis innsender klikker flere ganger på knappen Godkjenn egenerklæring og send inn blir skjemaet sendt inn x antall ganger.

Det kommer ikke noen feilmelding. Det vises heller ikke i browser at siden laster.

Kan noen se på dette?

### Steps To Reproduce

Prøv å send inn skjema

### Additional Information

Ingen feilmeldinger

**Comment by framitdavid** [comment]
@GeirHerbertHorn endringene var ikke med i forrige alpha-release og du har antagelig derfor ikke fått testet med siste endringene som skal løse denne saken. Tester du direkte i produksjon eller har du en test-app? Lenken i denne saken er vel direkte til appen i produksjon?

Vi har nå publisert en ny alpha-release med nødvendige endringer nå, får du testet denne i et testmiljø? 😄

**Comment by framitdavid** [comment]
Takk for beskjed @GeirHerbertHorn. Jeg sier i fra når vi har disse endringene i produksjon, slik at du kan teste dette i produksjon da. :)

**Comment by framitdavid** [comment]
@GeirHerbertHorn da skal endringene ligge ute i produksjon fra vår side, så da kan du teste igjen. 😄

**Comment by GeirHerbertHorn** [comment]
@framitdavid det ble litt bedre.
Nå ser man at skjemaet laster etter man har klikket på sendt inn

**Comment by framitdavid** [comment]
@GeirHerbertHorn! Supert - det var det vi gjorde som en fiks på denne, slik at brukeren får tilbakemelding om at vi jobber med saken og at siden laster. Takk for at du fikk testet. 👏 😄
