### ISSUE TITLE
Panel, textResourceBinding, body not working as intended

### ISSUE THREAD

**Issue by DanRJ** [Altinn/app-frontend-react#1153]
### Description of the bug

I have the following Group that uses a Panel, and the documentation says I can use title and body, however body is not showing anything. [According to this slack discussion](https://altinndevops.slack.com/archives/C045EB3JA9X/p1683639976903589), it is a bug.

### Steps To Reproduce

Have a Group with a Panel
Try to add body in textResourceBinding
See that body wont show.

**Comment by olemartinorg** [comment]
@Magnusrm It works, but does not look the best when there are multiple components inside the panel that uses `grid` settings to make them show up side-by-side.

![20230512_11h13m37s_grim](https://github.com/Altinn/app-frontend-react/assets/700139/c8e06978-d972-4060-8e4b-f523aae3aee5)

**Comment by Magnusrm** [comment]
@olemartinorg Does not look good indeed 😅 Mabye using div instead of span and setting width to 100% would solve the issue?
