### ISSUE TITLE
Validation messages doesn't respond as expected to required logic on checkbox fields

### ISSUE THREAD

**Issue by mariannestor** [Altinn/app-frontend-react#1156]
### Description of the bug

When i.e. two checkbox fields are dependant on each other regarding required logic the validation messages doesn't respond as expected (as they do with i.e. input fields that are dependant on each other). So, if at least one check is required on the entire page with i.e. two checkbox fields, and one of the checkbox fields is checked, the other one still has a validation message even though required is switched to false after checking in one of the fields. This indicates that the user hasn't met the requirements in filling out the form, even though the user has met these requirements.

This works fine when regular input fields are dependant on each other in the same way. It seems that it's a problem regarding checkboxes. 

See video for better description below. 

The example app for test is this one: https://altinn.studio/editor/krt/krt-1116a-1/deploy
But this has been observed on other apps too. 

### Steps To Reproduce

1. Go to https://krt.apps.tt02.altinn.no/krt/krt-1116a-1/
2. Log in with an organisational user.
3. Choose i.e. 2nd or 3rd option in 1.6 ("Finansføretak som ikkje blir organisert som aksjeselskap eller allmennaksjeselskap" or "Gjensidige forsikringsføretak"). 
4. Click next / go to page 2. Forskriftshenvisning.
5. Try clicking directly on next-button. See validation messages pop up on both fields with checkboxes. 
6. Check on of the checkboxes in _one_ of the checkbox fields.
7. See that the validation message doesn't go away on the other checkbox field (the one that has none checked off), even though the triggers validation should prompt this to go away. 
8. (Going to next page works fine, so it indicates that the required-logic is okay. It's just the validation/error messages that doesn't follow the logic correctly.)

### Additional Information

Reported on Slack here: https://altinn.slack.com/archives/C02FK32KVKJ/p1683717901921249 

See video of reported bug here:
https://github.com/Altinn/app-frontend-react/assets/113341248/5f9cb534-fe8e-4d46-9a8d-7f57f9812c76

Should be looked at together with https://github.com/Altinn/app-frontend-react/issues/726

**Comment by olemartinorg** [comment]
This is possible to solve with a ['fixed' validation message](https://docs.altinn.studio/app/development/logic/validation/#specify-that-validation-errors-are-fixed), but it may be hard to get right.

Other than that, if validations are implemented with expressions, as in #726, this should now be solved. Closing the issue.
