### ISSUE TITLE
Option in select does not get bold if there are no description

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#1169]
### Description of the bug

When having option lists with and without description in the same list - all values should be bold, not just the ones that has a description. When having large lists of values it's easy to miss the ones without a description since it's not bold as the rest of the values.

### Steps To Reproduce

1. Create a codelist with a two options
2. Add description to one of them
3. Use the code list in a dropdown field
4. Note that the one with a description the option gets bold, while the other without a description is not.

### Additional Information

![image](https://github.com/Altinn/app-frontend-react/assets/5430430/8f6a1f37-211c-45a3-b052-d870dfc3e9fe)

**Comment by bjosttveit** [comment]
What about when there are only options with no description? Should they all still be bold?

**Comment by hannefinnoy** [comment]
@mrosvik Do you have any thoughts about this?

**Comment by mrosvik** [comment]
Suggestion:

If no options has description:
- Regular text an all options

If some options has description: 
- Semibold on title, regular on description
- Semibold on options without description
