### ISSUE TITLE
Should we offer animated transitions in our forms

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#117]
## Description
There has been requested to include transition animations in our forms. This could make our forms easier to follow when they are expanding for instance. 

[Protoypes illustrating how this might work](https://www.figma.com/proto/kq3yTAS4vifQgrNeTjL5d9/Sprintleveranser-2020?node-id=1474%3A393&viewport=-1182%2C-3180%2C0.6221728324890137&scaling=min-zoom) 
**Press the "r" key to return to start.**

**Update**
User tests showed some user did not see the form change when clicking next. This could cause the user skipping content in cases where form pages look similar. Possible solutions: Animation transition or mock loader of some sort. 

## In scope
UU/WCAG analysis

## Out of scope
> What's **out** of scope for this analysis?

Lorem ipsum

## Constraints
> Constraints or requirements (technical or functional) that affects this analysis.

Lorem ipsum

## Analysis

Lorem ipsum

## Conclusion
> Short summary of the proposed solution.

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by FinnurO** [comment]
DIHE wanted a spinner for API calls. Ref Slack september 2022

**Comment by Febakke** [comment]
Closing this as a duplicate #586
