### ISSUE TITLE
Fields in nested repeating groups cannot be used in or from in resource-files

### ISSUE THREAD

**Issue by guttoma** [Altinn/app-frontend-react#1191]
### Description of the bug

We have a nested repeating Group, and we would like to use a value from the inner Group in a text appearing in the same inner Group. However, this doesn't work and just displays the `{0}` directly on the page: 
```
    {
      "id": "mellomliggende.norskutenlandsk.title",
      "value": "__{0}__",
      "variables": [
        {
          "key": "skjemainnhold.skjemadata.reellRettighetshaver[{0}].posisjonEierMellomliggendeVirksomhet[{1}].virksomhet.navn",
          "dataSource": "dataModel.Brønnøysundregistrene_ReelleRettighetshavere_M"
        }
      ]
    },
```
It _does_ work if you set it up like this (note the hardcoded array-keys): 
```
    {
      "id": "mellomliggende.norskutenlandsk.title",
      "value": "__{0}__",
      "variables": [
        {
          "key": "skjemainnhold.skjemadata.reellRettighetshaver[0].posisjonEierMellomliggendeVirksomhet[0].virksomhet.navn",
          "dataSource": "dataModel.Brønnøysundregistrene_ReelleRettighetshavere_M"
        }
      ]
    },
```
But as soon as you try to use any variable in the key-part of the variable, it just displays `{0}`. This does NOT work, for instance (note only one variable in the key): 
```
    {
      "id": "mellomliggende.norskutenlandsk.title",
      "value": "__{0}__",
      "variables": [
        {
          "key": "skjemainnhold.skjemadata.reellRettighetshaver[{0}].posisjonEierMellomliggendeVirksomhet[0].virksomhet.navn",
          "dataSource": "dataModel.Brønnøysundregistrene_ReelleRettighetshavere_M"
        }
      ]
    },
```

And for fun, trying to use a nested list-element _outside_ of a nested list does not work (as expected), BUT it does not display `{0}` on the page, it displays nothing (which is as expected). 

This bug was discovered in https://altinn.studio/repos/brg/rrh-innrapportering, though the code that triggers it is not merged yet. 

### Steps To Reproduce

1. Create a nested Group
2. Try to use a variable from the dataModel within the inner Group in a text within the inner Group.

**Comment by RonnyB71** [comment]
Will be solved by #1218
