### ISSUE TITLE
Allow popus from iFrame component

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#1216]
### Description

The iFrame component runs in sandbox mode with most settings disabled. We would like to allow links in the html to open in a new tab, but this currently doesn't work as the browswer complains that allow-popups is disabled.

### Additional Information
Consider the effects of these two attributes. Probably makes sense to not force the sandbox on new tabs.

* **allow-popups:** Allows popups (like from [Window.open()](https://developer.mozilla.org/en-US/docs/Web/API/Window/open), target="_blank", [Window.showModalDialog()](https://developer.mozilla.org/en-US/docs/Web/API/Window/showModalDialog)). If this keyword is not used, that functionality will silently fail.
* **allow-popups-to-escape-sandbox:** Allows a sandboxed document to open new windows without forcing the sandboxing flags upon them. This will allow, for example, a third-party advertisement to be safely sandboxed without forcing the same restrictions upon the page the ad links to.

**Comment by bjosttveit** [comment]
Should this be optional? There are many options for the `sandbox` attribute, any others that should be controllable?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attributes
