### ISSUE TITLE
Mer brukervennlig styring av full bredde i skjemaet

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1220]
### Oppdatering
Se kommenterer lengre nede for et oppdatert løsningsforslag. Behovet bak dette forslaget var å gjøre det lettere for brukere å ta i bruk full-bredde-visning i skjemaet de steder vi vet behovet vil kunne oppstå.

### Description

Slik det er dag så legger knappen for å utvide til fullbredde seg på toppen til høyre, denne burde kunne knyttes mot en eller flere komponenter i en side slik at den ligger der det er behov for å se data i full bredde.
I et skjema som er langt da så vil det være knotet å måtte gå til toppen for å utvide.

### Additional Information

![image](https://github.com/Altinn/app-frontend-react/assets/91887041/5c663a4c-b374-4530-af1d-3d0756d18b66)

**Comment by StianVestli** [comment]
org/ssb

**Comment by hannefinnoy** [comment]
Er det en mulighet at vi heller løser dette som en innstilling i appen slik at det alltid vil gjelde når det er skrudd på, i stedenfor at vi innfører dette på komponentnivå? @StianVestli @olemartinorg

**Comment by olemartinorg** [comment]
Regner med Hanne tenkte på en "standardinnstilling" i appen som gjør at siden alltid vises med utvidet bredde. Vil tro det kan løse noe, og det har blitt etterspurt før (men jeg fant ingen issue på det).

**Comment by hannefinnoy** [comment]
Ja, jeg tenkte som Ole Martin sier at det var en innstilling som settes av tjenesteeier f.eks. på sidene. Siden det kontrollerer hele sidebredden så vil det kunne bli ganske komplekst om det skal ligge på komponentnivå.

**Comment by hannefinnoy** [comment]
Ja, skjønner det. Kan vi ikke prøve det å sette det som en innstilling først? Og hvis det blir rart, så ser vi videre på det? Skal jeg lage en oppgave på det @olemartinorg eller oppdatere denne?

**Comment by StianVestli** [comment]
Slik at vi ikke misforstår hverandre, så er det hele skjema som skal utvides ikke bare komponenten selv om knappen legges ved komponenten.

**Comment by StianVestli** [comment]
Ja det vil nok funke det, så lenge det kan styre pr side.

**Comment by olemartinorg** [comment]
Jeg tenker det er helt greit å gjenbruke dette issuet. Her er det beskrevet en ønskelig løsning (_at knappen ligger ved siden av komponenten hvor man trenger den_), men jeg synes det er viktig at vi får frem hva som er behovet bak denne funksjonaliteten (_at man vil gjøre det lettere for brukeren å ta i bruk funksjonaliteten for utvidet bredde i skjemaet_). Sett i lys av behovet synes jeg den alternative løsningen foreslått her er bedre (nemlig å sette dette som en innstilling per side i skjemaet, uten at brukeren trenger å foreta seg noe). 

Vil dere ta en ekstra runde på en slik løsning - for eksempel ved å lage prototyper, utforske eventuell animering (#117, #586), eller skal vi fjerne `ux`-labelen @hannefinnoy?

**Comment by hannefinnoy** [comment]
Tror ikke vi trenger en ekstra runde på denne :)

**Comment by jhhssb** [comment]
Behovet er aktuelt i forb. med flere skjemaer i OKI som er under utvikling nå.
