### ISSUE TITLE
Grid component: Helptext in text cells

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1230]
### Description

There has been multiple requests for helptext support in Grid cells that show text. Theoretically simple to implement, but this isn't a normal FieldSet (because we don't know which field(s) the text cell refers to).

### Additional Information

- https://altinn.slack.com/archives/C02FK32KVKJ/p1685532531583239

**Comment by RonnyB71** [comment]
Alternatives:
1. Help text on text cell, no binding against input filed and text needs to be duplicated on input field for screen readers.
2. Property on text cell that holds a reference to the input field and uses the text and help text from that component
