### ISSUE TITLE
Gi varsel til bruker ved endring av valg i dropdown

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1233]
### Description

Man kan i dag sette "alertOnDelete" på repeterender grupper, dette hadde vært ønskelig på feks checkbokslister og, i grunn på alle komponenter der en kan endre et valg. 
Grunnen til dette er at man i dag genrer opp datastrukturer i koden bak ut fra valg gjort i feks checkbokslister. Hvis man endrer valg i en slik liste kan de betyr at man sletter datastrukturen bak for dette valget, det å kunne da kunne gi bruker et varsel hadde vært fint. Man vil da og unngå at bruker fjerner valg ved en feil som ikke er reverserbar.

### Additional Information

Blokkert av https://github.com/digdir/designsystem/issues/563

**Comment by lassopicasso** [comment]
Hei @StianVestli ,

Kunne du forklart litt nærmere hvilke type use case dere ønsker dette skal gjelde for når det kommer til radioknapper/sjekkbokser?
Ønskes det for eks. at man setter en property som `"alertOnChange": true` på en komponent med type "radioButtons" og det gir varsel hver gang man endrer valg av radioknapp?

Eller er det flere momenter dere ønsker at det skal tas hensyn til når varselet skal trigges? For eks. at det må være påbegynt utfylt (og prefilled) i feltene knyttet til den aktive radioknappen for at varselet skal trigges?
Da må jeg isf finne en god løsning for hvordan input-felt knyttet til aktiv radioknapp skal kobles sammen :)  

Her er et eksempel på hvordan det vil se ut (ikke ferdig) når det er konfigurert med `alertOnChange` og det varsles ved hver endring i radioknapper uavhengig av innholdet i feltene knyttet til den aktive radioknappen.

https://github.com/Altinn/app-frontend-react/assets/74791975/f0c96085-adc5-40ee-83fb-707fd5de98db

**Comment by StianVestli** [comment]
Hei, det er typisk når man har mer logikk rundt radioknapper og checkbokser dette er mest aktuelt. Da tenker jeg på at en endring av valg vil føre til større endringer i skjema, enten ved dynamikk eller kode bak. 
Jeg vil tru at "alertOnChange": true vil godt nok i mange tilfeller. Har ikke vært borti at vi prefiller data i denne type felter, man man vil la brukeren huke av valgene.
Skal man kunne ønske seg noe så er det jo at denne settingen også kan styres med logikk ved dynamiske uttrykk.

**Comment by olemartinorg** [comment]
Re-opening as this hasn't been solved for dropdowns yet.

**Comment by StianVestli** [comment]
Dette bør også gjelde for Multipleselect komponenten også. Spesielt på slett alle knappen i denne.
