### ISSUE TITLE
Validation messages not removed inside repeated groups

### ISSUE THREAD

**Issue by JohanGuntherKrogevoll** [Altinn/app-frontend-react#124]
## Description
Error message after validation on field inside repeating group is not removed.
## To Reproduce
(Specific for [our app](https://altinn.studio/repos/dsb/melding-om-sikkerhetsraadgiver/src/commit/7b65b6909d2e6ec390db5bd5df661fc4c7562a2a))
1. Add new or edit an entry in a repeating group.
2. Trigger a validation error on a field that is validated depending on another field.
3. Address the validation error by changing the other field the validation is dependent upon. 

## Expected behavior
The validation error message is removed.

## Screenshots
![Kapture 2022-05-24 at 13 40 07](https://user-images.githubusercontent.com/66003225/170026577-9985b248-8310-47d8-b184-b4b19c78a946.gif)

## Additional info
* The error-message is removed if i focus the field to remove the error as demonstrated in the GIF.
* The dynamics causing the relevant field to hide and show seems to be irrelevant for the problem.
* In this example its server-side validation that checks if the SSN is required or not. I have also tried setting the field to required in the layout and relying on the dynamic to remove and add the field, but this produces the same result.
* [Relevant slack discussion](https://altinn.slack.com/archives/C02ESDSC929/p1653052884981219)

**Comment by xmrsa** [comment]
I think this comment is also relevant to this issue: https://github.com/Altinn/app-frontend-react/issues/545#issuecomment-1280751207

The validation for fields shown when a question is answered is Yes, shows integer fields that are required (set as standard rule in Altinn Studio). If I answer No, the integer fields still validate even though the row is hidden by a filter. It seems to me that the problem might come from the fact that the field probably exists even if it is hidden.

**Comment by bjosttveit** [comment]
@olemartinorg Is this fixed by https://github.com/Altinn/app-frontend-react/pull/627?

**Comment by olemartinorg** [comment]
Should be, yes! :partying_face: Seems like #617 was a duplicate issue, sadly. @JohanGuntherKrogevoll, do you mind testing this? Assuming #617 was a duplicate, so let us know if closing this was a mistake.
