### ISSUE TITLE
Should be able to render CustomComponent in ButtonGroup

### ISSUE THREAD

**Issue by lasseklovstad** [Altinn/app-frontend-react#1256]
### Description of the bug

Hey we have made a button as a custom web component and we would like to use it with ButtonGroup to align them horisontaly. But this is not possible. Is there areason why this is not possible today?

### Steps To Reproduce

1. Add a custom web component to a ButtonGroup
2. Doesn't work

### Additional Information

I think an easy fix is to add:
```
canRenderInButtonGroup(): boolean {
    return true;
  }
```
to custom component class

**Comment by olemartinorg** [comment]
@lasseklovstad Do you have a chance to test this now? It'll soon be released, but you can also test it in the main branch.

**Comment by lasseklovstad** [comment]
@olemartinorg Yes we will tests it as soon we have time. It is in our summer sprint board :)

**Comment by ZuperNova** [comment]
@olemartinorg I just updated our app to utilize the new feature for ButtonGroup and I can confirm that this works 🎉
