### ISSUE TITLE
Unexpected font sizes in `Panel`

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1280]
### Description of the bug

It seems that font sizes (at least for the heading) in a Panel are unexpectedly large. Possibly after a refactor.

Notice that the heading here is larger than the app title above it:
![font-size-panel](https://github.com/Altinn/app-frontend-react/assets/700139/183047be-44c2-4e99-a8e3-0ea64d899ece)

The link in **additional information** should also be investigated.

### Steps To Reproduce

1. Look at a `Panel`
2. Try out earlier versions of app-frontend to compare?

### Additional Information

- https://altinn.slack.com/archives/C02EVE4RU82/p1684498771118749

**Comment by bjosttveit** [comment]
Fixed by #1173
