### ISSUE TITLE
Auto save form data for end user

### ISSUE THREAD

**Issue by gudrunvigerustfuru** [Altinn/app-frontend-react#129]
## Description
As an end user I want the form to be stored automatically while I fil it out, not only on submit, so that I can continue to work after for instance a data crash or going in and out of a form for example.
(Copy from old backlog, US 2518 from sprint 18)

The implementation should include tasks for removing the code for the save button that was kept in Altinn/altinn-studio#1025, since we were missing auto save of form data.

**Comment by nkylstad** [comment]
We have auto-save for form data in apps. Closing this issue.
