### ISSUE TITLE
Rewrite `useGetOptions()` and data lists to hooks using Tanstack Query without Redux

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1294]
It should be possible just to pass in all the different props (`options`, `optionsId`, `source` and `mapping`) and just return `IOption[]` (or whatever it's called). No need for Redux.

Same goes for data lists, which is very similar to regular options.

### Links to relevant issues
- Should make this easier: #1104 
- #1094 
- #1096
- #141

**Comment by RonnyB71** [comment]
Verify the PDF implementation as this depends on sagas fetching options.

**Comment by olemartinorg** [comment]
Also related:
- #1180 
- #957
- #936
