### ISSUE TITLE
Stateless apps without login

### ISSUE THREAD

**Issue by altinnadmin** [Altinn/app-frontend-react#131]
We now have support for [stateless apps](https://altinn.github.io/docs/altinn-studio/app-creation/configuration/stateless/), which is great.
Next step in the evolution is supporting stateless apps *without* requiring login for the user.

Examples for these kind of simple forms can be found here:

- E-guides: https://www.altinn.no/starte-og-drive/starte/guider/
- "Står du fast" on altinn.no (not linkable).

Supporting this will enable [dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) and to make it possible for us to stop using a proprietary product in Altinn, saving big bucks.

## Describe the solution you'd like
- The ability to configure authentication level "-1" for a stateless app. No login, complete anonymity.
- This should disable the redirect to login
- and make it possible to still access logic and post data to the stateless `/data` api

## Describe alternatives you've considered
 - N/A

## Additional context
> Add any other context or screenshots about the feature request here.

## Consideration

Constraint: Only stateless!

Should it be possible to log in after an anonymous section? (NOT NOW)
How to keep data in between?  Local storage?

### Common
- Config for disabling required authentication
- Config of the default language

### Fake user

- Extend authentication with fake user login
- How to prevent "fake user" doing stuff we don't want
- Messagebox
- Using existing apps before concept was introduced 

### Not authenticated at all

- Disable check on API (stateless API only)
- Update frontend to hide components not relevant for anonymous login
- Language cant be retrieved from the profile
- ReporteeList disabling 
- Check with security
- DOS attack?
- Should we generate a session id?

E-guide screenshot:
![image](https://user-images.githubusercontent.com/6088624/123998096-6de44200-d9d1-11eb-8c58-510253beb98d.png)

**Comment by nkylstad** [comment]
Code is deployed and all connected issues are closed. Closing this epic.
