### ISSUE TITLE
Attachment changes in backend are not shown after alterations via DataProcessingHandler

### ISSUE THREAD

**Issue by Gunnar-Solli-Olsen** [Altinn/app-frontend-react#1335]
### Description of the bug

Deletion of attachments via ProcessDataWrite() does not apply to frontend, attempted interactions then fail with code 404 not found. 

Reloading the page updates listed attachments and clears non-existing attachments

### Steps To Reproduce

1. Make application with custom dataprocessinghandler
2. Add attachment to frontend (via altinn.studio)
3. Dependency inject the 'IData' interface in the dataprocessinghandler
4. in 'ProcessDataWrite(), use the .DeleteData() method on what you named the implementation of IData to delete an attachment from 'instance.Data' and return true 
5. trigger the deletion
6. interaction with the attachment now returns a 404 not found message 

### Additional Information

![image](https://github.com/Altinn/app-frontend-react/assets/95483155/fcc3a1b2-f4ce-4e0c-9eec-4fe99a89a689)
![image](https://github.com/Altinn/app-frontend-react/assets/95483155/5dc1a0ea-b2df-4f09-88a0-67afc4d27021)
![image](https://github.com/Altinn/app-frontend-react/assets/95483155/e931bec9-7ab4-4350-955a-bc3671c369d3)

**Comment by rodsjo** [comment]
Jeg opplever det samme, hadde vært fint å fått denne fikset

**Comment by ivarne** [comment]
@bjosttveit Should app-lib just add `Instance` (including `instance.data`) to the PATCH responses? so that this would be efficient for frontend to fix?

**Comment by olemartinorg** [comment]
@ivarne That might work, yes! :raised_hands: The PATCH request is growing up to be the 'one request to rule them all', but I can't say I mind it all that much.

**Comment by ivarne** [comment]
> EDIT: It would probably be best for everyone if that only happens if any instance data changed as a result of the save operation, of course.

If there are multiple frontends running simultaneously, there is a race condition possible here. I would prefer to follow the pattern we chose when we returned the full updated model in the patch responses

**Comment by olemartinorg** [comment]
Good point!

Also, discussion here (which is why I found the issue): https://altinn.slack.com/archives/C02FK32FBR6/p1724328182689299

**Comment by rodsjo** [comment]
I had a similar use case as you @Gunnar-Solli-Olsen. We have logic in our form that displays/hide a file uploader based on radio buttons.  If the file uploader was hidden we wanted to remove uploaded attachments. I ended up implementing deletion in  `IProcessTaskEnd`, where we delete attachments both from storage (using `IData`-client) **and** from `ìnstance.Data` . I got an `500 - Internal Server Error - Altinn.Platform.Storage.Repository.RepositoryException` if I did not delete the file from `instance.Data`.

See attached implementation of `IProcessTaskEnd`
[ProcessTaskEnd.txt](https://github.com/user-attachments/files/16747730/ProcessTaskEnd.txt)

**Comment by ivarne** [comment]
This has been fixed in 8.5 versions of backend (and newest frontend versions) with the following caveats .
* New interface `IDataWriteProcessor` that provides an `IInstanceDataMutator` with methods to update data and report back to frontend.
* Changes made using `IDataClient` is not captured, but will be caught on the next change.
* `IProcessTaskEnd`has not yet been updated to provide `IInstanceDataMutator`, so you need to manually mutate `instance.Data` to keep the list of elements in sync with the changes you make with `IDataClient`.
