### ISSUE TITLE
Justering av avstander (WCAG 2.1)

### ISSUE THREAD

**Issue by Janingetjosvoll** [Altinn/app-frontend-react#1362]
### Description

Register over reelle rettighetshavere utvikler skjema som må oppfylle mange krav til universell utforming. For å kunne oppfylle en del av disse lovkravene må vi ha hjelp av dere i Altinn.

WCAG 2.1:"Brukeren skal kunne justere avstand mellom linjer, paragrafer, bokstaver og ord uten at innhold eller funksjonalitet går tapt."

Dette fungerer ved innstillinger i nettleseren noen steder, men ikke i alle elementer.

### Additional Information

Dette er mest sannsynlig på grunn av at det er hardkodet inn avstander og størrelser i stedet for å bruke justerbare verdier som REM

[(https://www.uutilsynet.no/wcag-standarden/1412-tekstavstand-niva-aa/14)]

### gjennomgang av Lasse (Digdir)
Testet ved å gå gjennom hele testappen i 400% forstørrelse
Datepicker får en intern scroll i modalvisningen. Vi burde ta en titt på den.
<img width="1324" alt="Skjermbilde 2023-08-23 kl  14 11 42" src="https://github.com/Altinn/app-frontend-react/assets/33222679/c6a8963b-d451-43b1-8767-1a85b74963bc">

Repeterende gruppe (Kanskje spesielt i testappen blir vanskelig å forstå hva man holder på med. Kanskje det kan løses av denne: #1244 

Vet ikke om dette brukes av mange, men gridløsning på oppsummering burde falle ned på en kolonne. 
<img width="1340" alt="Skjermbilde 2023-08-23 kl  14 15 23" src="https://github.com/Altinn/app-frontend-react/assets/33222679/87981644-eb22-49be-b269-989911d72274">

Jeg testet også med å endre alle tekstvariabler definert i 1.4.12 og fant ikke noe innhold som forsvant. Om dere fant noe i deres app, gjerne send skjermbilde.

**Comment by Febakke** [comment]
@Janingetjosvoll 
Gjerne legg inn skjermdump og forklaring på hvilken komponenter dette skjer på.
[Dette](https://github.com/Altinn/app-frontend-react/issues/756) er kanskje ikke fikset igjen hvis vi rullet tilbake font byttet til inter? @bjosttveit

**Comment by bjosttveit** [comment]
Nei jeg tror den spesifikt fortsatt er fikset, vi rullet ikke tilbake endringene, bare switchet fonten igjen. Jeg tror vi stort sett alltid bruker `rem` til font-størrelser, men til andre størrelser (spesielt `padding` og `margin`) ser jeg at det brukes `px` en del. Er det sånn at man så å si "aldri" skal bruke `px` noen steder for at dette skal fungere skikkelig?

**Comment by Febakke** [comment]
- [ ] Ask Brreg for concrete examples

**Comment by Janingetjosvoll** [comment]
Fra vår UX-ressurs: "Alle plassene som refererer til avstanden mellom objekter er i rem med unntaket av:

letterspacing som referer til px eller %, jeg vet ikke hva den %en peker til så det jeg ikke si om en bruker kan tilpasse den variabelen den peker til.
Jeg trodde det var enda en som var table padding, men ser nå at det er et regnestykke mellom et fast tall og font størrelsen som har sin kilde i rem, så da bør brukeren kunne endre rem og spacing endres etter behov. Da er vel dette teknisk sett innenfor kravet." 
- Denne oppgaven kan da lukkes som OK.
