### ISSUE TITLE
Tilbakeknapp i nettleser må kunne brukes (beste praksis-krav Brreg)

### ISSUE THREAD

**Issue by Janingetjosvoll** [Altinn/app-frontend-react#1363]
### Description

Register over reelle rettighetshavere utvikler skjema som må oppfylle mange krav til universell utforming. For å kunne oppfylle en del av disse lovkravene må vi ha hjelp av dere i Altinn. 

Beste praksis - krav i Brønnøysundregistrene: "Nettleserens tilbakeknapp kan brukes i løsningen."

Dette fungerer ikke i appen per nå. Sendes ut av skjemaet hvis tilbakeknapp brukes.

**Comment by bjosttveit** [comment]
https://github.com/Altinn/app-frontend-react/issues/225

**Comment by bjosttveit** [comment]
Fixed by https://github.com/Altinn/app-frontend-react/pull/1682
