### ISSUE TITLE
Accordion looks weird in PDF view

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/app-frontend-react#1380]
### Description of the bug

When looking at an `Accordion` in PDF preview, the background of the text is not visible (or has very little height). 

### Steps To Reproduce

1. Go to frontend-tests.
2. Open PDF preview.
3. Observe the text inside accordion get these thin gray streaks above the content. 

### Additional Information

![image](https://github.com/Altinn/app-frontend-react/assets/26043795/92b870c8-b5e0-4e41-9d5b-56e834deb3bf)

**Comment by bjosttveit** [comment]
Tested looks good 👍
