### ISSUE TITLE
FileUploadWithTag unable to use langauge resource files

### ISSUE THREAD

**Issue by magnusrf** [Altinn/app-frontend-react#1382]
### Description of the bug

The values from the resource file are not read in the dropdownlist for the tagTitle 

org/pat

### Steps To Reproduce

1. upload file to fileUploadWithTag
2. when dropdown list appears, the values are not read from the resource files
3. after a category has been chosen and saved, its resource value is read again, but on the column for  tagTitle, "file-attachment.type" is not read

### Additional Information

![bug1](https://github.com/Altinn/app-frontend-react/assets/32111471/a0f90bf6-f6de-47ae-a849-b34ba14b3bb0)

![bug2](https://github.com/Altinn/app-frontend-react/assets/32111471/faf279d6-16f0-462e-8b1d-66b9d31365a2)

**Comment by Sindrir** [comment]
This is an issue for us as well (NBIB), we have some confused users ATM.
Rolling back to v3.65.1 seems to be the fix for us now. So something happened in 3.66

**Comment by Sindrir** [comment]
@bjosttveit 🎊 works great
