### ISSUE TITLE
Allow markdown in body of Alert

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/app-frontend-react#1404]
### Description

There has been expressed a wish for Markdown/HTML in the body of an `Alert`. The [design system](https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-alert--docs) lists examples with links in the body,  so we should be able to allow it as well.

**Comment by bjosttveit** [comment]
Seems to be working great 🥳 

![Image](https://github.com/Altinn/app-frontend-react/assets/47412359/ed5905ad-3a23-4ee7-9ef0-08654bf29c92)
