### ISSUE TITLE
Thirdparty components in app-frontend

### ISSUE THREAD

**Issue by malmil** [Altinn/app-frontend-react#142]
Today's thirdparty component is not sufficient because it uses an external url (or url connected to altinn studio). Using external url's could be a security risk when we use eval. 

### Suggested solution
Using the thirdparty component as it is in UX-editor and download the script for thirdparty components as a part of the runtime resources. That way it can't be changed once deployed.

## Acceptance criteria
Should work as thirdparty components does in current runtime

## Tasks
- [x] Clarify if this is to be implemented in MVP (or post-MVP)
- [ ] Redesign thirdparty to not be dependent on altinn studio resources and implement
- [ ] Test

**Comment by olemartinorg** [comment]
Implemented in:
- #320
