### ISSUE TITLE
File uploader – undefined filetypes

### ISSUE THREAD

**Issue by sarahwoodhouse** [Altinn/app-frontend-react#144]
## Describe the bug
If the service developer has chosen to define which filetypes that can be uploaded, but then hasn't typed in anything. the filetype is set to undefined and that is what is shown to the end user, which doesn't mean anything.

## To Reproduce
1. Create a new service or go to an existing one
2. Go to ui editor and drag in a file uploader
3. check the "egendefinerte filtyper" radiobutton
4. Go to test and create a new instance
5. See that the allowed file types are set to "undefined"
3. See error

## Expected behavior
That all file types are still allowed and undefined is not shown to the end user. To the end user in Altinn it should look and behave the same as for when the "egendefinerte filtyper" is not checked.

## Screenshots
![Screenshot 2019-05-16 at 16 45 32](https://user-images.githubusercontent.com/6996124/57863739-e8a27100-77fa-11e9-90c9-c160562b27bf.png)

## Additional info
Tested in altinn.studio

## Fix
If they don't write anything, every filetype is allowed. This must be reflected in the application the same way as if they choose every filetype in the UI-editor. "alle" written after "tillatte filformater:" in the component. 

## Acceptance criterea 
- When the there are no values in the "skriv in gyldige filtyper" field, the component should act as if "Alle filtyper" is selected. 
- The component should tell the end-user that all filetypes are allowed. 

## Sketch
**UI-editor (No values)**
https://www.figma.com/file/O7Oqx6p9ZUZBt8DFBNanrymh/MVP-2-Altinn-Studio?node-id=2265%3A2
**Application**
https://www.figma.com/file/O7Oqx6p9ZUZBt8DFBNanrymh/MVP-2-Altinn-Studio?node-id=2265%3A485

**Comment by olemartinorg** [comment]
Looks to me like this has been fixed in the period since this was reported. I tried with and without `allowedContentTypes` in `applicationmetadata.json`, and both present the same for me, at least.

**Comment by haakemon** [comment]
Closing issue as it has been reported as fixed.
