### ISSUE TITLE
Certain organisation logos are too small to use

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/app-frontend-react#1452]
### Description of the bug

When Finanstilsynet tried to use the new organisation logo feature, it was immediately evident that the default max size of the logo does not fit all different logo shapes and forms. 

The logo is too small: 
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/a390fbb6-98df-498d-9de5-c6e960fb1c66)

### Steps To Reproduce

1. Configure use of organisation logo
2. Add this configuration to `applicationmetadata.json`: 
```json
{
  "logo": {
    "source": "resource",
    "displayAppOwnerNameInHeader": false
  }
}
```
3. Add a logo that is not fitting in `resource.[lang].json`:
```json
[
  {
    "id": "appLogo.url",
    "value": "<url to logo that is too tall>"
  }
]
```

**Comment by olavflar** [comment]
![Image](https://github.com/Altinn/app-frontend-react/assets/70377508/9e0bc103-712d-45d7-bbfd-1097699ae457)
