### ISSUE TITLE
Validate and warn against dataModelBindings not found in data model

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1463]
### Description

In the spirit of #648, we should validate and warn about dataModelBindings we cannot find in the data model (schema). We used to have a tool for this, `json-schema-library`, but it is slow and unreliable.

We should detect and warn about: 
- [ ] Missing `dataModelBindings` for components where a binding is expected
- [ ] `dataModelBindings` pointing to non-existing locations in the data model (use Levenshtein to find the correct one if misttyped)
- [ ] `dataModelBindings` pointing to invalid types in the data model 
  - [ ] I.e. `Input` supports strings and numbers (and with numeric data types, number formatting should be set)
  - [ ] Booleans are not supported/recommended (#205)
  - [ ] Repeating groups should have their `group` binding pointing to an array-type in the data model (with an object type within)
  - [ ] Components inside groups must have their bindings contained within an object inside the array-type of the `group`
  - [ ] Components that are bound to properties inside what is defined as a repeating group in the data model, without having been defined inside of a repeating group structure in the layout, should produce warnings/errors

### Related issue(s)
- #743
- https://github.com/Altinn/altinn-studio/issues/1841

**Comment by bjosttveit** [comment]
Works like a charm ✨
