### ISSUE TITLE
Custom receipt should render even after reloading the page

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1468]
### Description

Right now, when configuring a custom receipt layout, it is added to `settings.json` _within_ a layout-set. This creates a few problems:

- It is possible to define it multiple times, each subsequent layout-set could overwrite the previous one
- Frontend has to keep old layouts laying around in redux/state storage, for use when showing the receipt in a future process step
- Reloading a page when looking at the custom receipt does not load the `settings.json` file, so frontend is unable to know about the custom receipt that has been defined, and will simply not display it.

Instead, we should move the configuration for a custom receipt to `layout-sets.json` where it belongs. There we could configure a layout-set for the end-event in the process (or simply name it something like receipt), define the data type frontend should download the data for, and have a folder of one (or more!) layouts to display upon reaching the receipt page.

For this to work flawlessly, we should coordinate this with Studio and have them support this alternative configuration there before we release it in app-frontend.

### Additional Information

- https://altinn.slack.com/archives/C0534SVCJLD/p1694781993448529
- #859
- #823 
- #171

**Comment by RonnyB71** [comment]
@nkylstad this will require changes in Studio as well.
