### ISSUE TITLE
filter on group component shows all the data in the table

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/app-frontend-react#147]
## Describe the bug
An app with group component configured with filter does not filter out the group that matches the criteria in the filter, and displays all the entries in the table.

## To Reproduce
1. Start an app with group component configured with filter on one or two fields in the group.
2. Fill out group with values that does not match the filter defined in the group component.
3. The values are shown in the table.

## Expected behavior
The group items which are not matching the filter should not be shown in the group table.

## Additional info
env: localtest
app: jeeva/test-5178

**Comment by FinnurO** [comment]
Relatwrt til #339 @bjosttveit er ikke dette noe du jobber med?

**Comment by bjosttveit** [comment]
Tanken er å implementere filter på nytt med expressions https://github.com/Altinn/app-frontend-react/issues/584 der disse problemene skal løses

**Comment by olemartinorg** [comment]
Lukker denne da saken er kjent, har eksistert lenge, og tjenesteutviklere kan ha gjort seg avhengige av denne oppførselen (så vi kan ikke/bør ikke endre dette uten en breaking change). Som nevnt bør det heller lages noe nytt. Se også kommentarer i #339.
