### ISSUE TITLE
Repeating groups: Mulighet for å angi tekst i første kolonne

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1494]
### Description

Slik det er i dag så er det ikke mulig å vise et tekst felt i en kolonne i en repeterende gruppe. Man kan få det til via feks et inputfelt men dette krever at tekst må inn via datamodell og at denne også blir liggende i datamodellen. Vi ønsker å kunne benytte tekst id'er slik at man får språkstøtten samtidig som man og kan flette inn info fra datamodellen.
En måte kunne være å tillate å vise header komponenten i gruppen, men slik det er i dag vises ikke denne i rep gruppen når den er lukket. 

Eksemplet under er en av flere slik tabell strukturer som man hadde hatt dette behovet i:
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/e82483b4-a63b-4af6-91a1-2ccd9b962c7b)

Vi har i dag Grid som man kan legge opp text i kolonne, det er en lignende funksjonalitet vi trenger men, Grid er ikke løsningen da denne er statisk, man vil også kunne ønske å legge til flere rader.
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/e1745a48-176a-44cc-94d8-afa24797d216)

**Comment by olemartinorg** [comment]
Vil dette kunne løses om man definerer statiske `text`-celler (ala Grid) i tillegg til vanlige komponenter i tabellen, @StianVestli?

**Comment by StianVestli** [comment]
Ja det trur jeg i mange tilfeller. Men man vil også ha denne med seg til oppsummeringssiden.

**Comment by olemartinorg** [comment]
Relevant diskusjon:
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1709031316363209

I denne lenkede saken ønkes det støtte for å hente tekst fra en komponent inni en ikke-repeterende gruppe og vise i tabellen. Riktignok ikke i første kolonne, men jeg tenker det store bildet her går på det samme; man ønsker mer detaljstyring på hvordan tabellen for repeterende grupper skal se ut.

**Comment by olemartinorg** [comment]
Denne saken har nok blitt tolket til å være mer avansert enn den kanskje trenger å være. Istedenfor å lage en helt ny (og mer konfigurerbar) variant av repeterende grupper, kan jeg se for meg noe ekstra konfigurasjon som (sammen med `tableHeaders`, `tableColumns` og `children` som vi allerede har) går på å konfigurere opp mer statiske kolonner/celler. Gitt at man har en nøkkel som beskriver en "custom" celle kan man bruke den nøkkelen også i `tableHeaders` og `tableColumns` (dog, jeg er usikker på om noe annet enn `width` er særlig relevant der).

Eksempel med `extraColumns`:

```json
{
  "children": ["myComp1", "myComp2"],
  "extraColumns": {
    "someLabel": {
      "labelFrom": "someComponentWithLabel",
      "compact": false // Defaults to false, displays description and helpText when false
    },
    "anExpr": {
      "content": ["text", "some-lang-key"]
    }
  },
  "tableHeaders": ["someLabel", "anExpr", "myComp1", "myComp2"],
  "tableColumns": {
    "myComp1": {
      "editInTable": true
    },
    "anExpr": {
      "width": "10%",
      "alignText": "right"
    }
  }
}
```

Tanken min her er å ikke _bare_ støtte uttrykk, men potensielt også andre ting (som her, med `labelFrom`). Det er også et veldig aktuelt use-case for SSB å vise frem en valgt option fra en option-liste, som er ulik for hver rad i den repeterende gruppen. I dag bruker de en skjult `Dropdown` inne i gruppa, som brukes for å vise den valgte verdien i tabellen, men da støttes det bare å vise selve labelen/tittelen på den valgte opsjonen. Det ønskes også å utvide dette til å vise både beskrivelse og hjelpetekst for den valgte opsjonen.

**Comment by olemartinorg** [comment]
Vi diskuterte denne på statusmøtet på fredag, og kom frem til at mesteparten av behovene her kan dekkes vha. å putte `Text`-komponenten inn i den repeterende gruppa. Vi avventer om SSB kan dekke behovene med den (og `Number` eller `Date`, etter behov).

FYI @bjosttveit

**Comment by rvessb** [comment]
@bjosttveit @olemartinorg Jeg har nå testet dette med `Text`, og det ser ut til å fungere det. Så da tenker jeg at denne saken kan lukkes.
