### ISSUE TITLE
Dynamic options does not work as expected with apps having two different datamodels

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/app-frontend-react#151]
## Description
On going from stateless to statefull, the mapping defined in layout of statefull app for dynamic options can access values from the stateless datamodel and in some cases the references api is sent with undefined values.

## To Reproduce
1. Start the statless-app and fill in journalnummer feild with 1337
2. Move forward to the statefull app
3. The references api is sent with value undefined in the query parameter
Test 2:
change the source in mapping to datamodelbinding fra stateless model, the references api is sent with undefined when journalnummer in 1364.

## Expected behavior
- It should not be possible to use data model binding from stateless app layout as mapping source in the statefull layout.
- The references api should be called with the values in the form data and undefined should not be sent.

## Additional info
env: local
app: ttd/stateless-app
branch: dynamic-options

**Comment by olemartinorg** [comment]
This has fundamentally not been an issue any longer since the major refactoring towards v4, which now isolates data models when navigating from one task (or stateless) to another.
