### ISSUE TITLE
Upgrade TextField from the design system

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1520]
### Description

In the latest versions of the design system, the TextField component no longer supports number formatting, so we should install `react-number-format` again and maintain number formatting in app-frontend.

When doing this, check the `fillOutChangeName()` which fills out the Grid percentages. This test was flaky because of number-formatting (and/or default values we got from the server), so when upgrading the design system we should make sure number-formatting does not lead to flakiness in those tests.

**Comment by Magnusrm** [comment]
The TextField component was upgraded from LegacyTextField to the Designsystem TextField component in https://github.com/Altinn/app-frontend-react/pull/2213
