### ISSUE TITLE
Design: Select language in an app

### ISSUE THREAD

**Issue by helenekri** [Altinn/app-frontend-react#154]
## Hypothesis
As part of the header that is used in applications available in Altinn.no, we need to include language menu option. It should show all languages the app is available in, preferably written in said language. Once a language is selected, the app interface should reflect this.

## Specification tasks
- [ ] Specify which pages the "language" menu option should be available on. 
- [ ] How to handle languages that use other alphabets
  - [ ] Including right-to-left script language
- [ ] Add development tasks

## Development tasks
- [ ] Documentation (if relevant)
- [ ] Manual test (if needed)
- [ ] Automated test (if needed)

**Comment by haakemon** [comment]
This has been fixed in https://github.com/Altinn/app-frontend-react/pull/83
