### ISSUE TITLE
Navigation back from Confirm-Task to Form-Task "lags"

### ISSUE THREAD

**Issue by violaguttorm** [Altinn/app-frontend-react#1552]
In our application rrh-innrapportering, we have a Confirm-task where a user can see a summary of what they've filled in, and navigate back if they want to change anything, but  when navigating back to the Form-Task the website just "lags" (the default "loading" screen just stays there forever). 

When you refresh the page, you are placed back in the Form-Task and you can make changes and so on, so it has actually navigated successfully, but ideally you should be able to see the Form without refreshing. This has worked befroe.

**Comment by RonnyB71** [comment]
Seem be related to gotoTask functionality. Same issue seen when aborting as well.

**Comment by tjololo** [comment]
Same behaviour is seen when navigating to a previous process step with v8-preview versions
