### ISSUE TITLE
Hidden rows are shown as empty boxes in summary

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#1553]
### Description of the bug

In `frontend-test` in the group step, if you set the value to hide certain rows, the hidden rows will show up as empty boxes when using `largeGroup: false` which is the case when generating PDF for this step:

<img width="544" alt="image" src="https://github.com/Altinn/app-frontend-react/assets/47412359/3a0c2cf5-0480-4cea-b1c6-1983edd7bce1">

The expected behavior is that hidden rows should not be present instead of showing up as empty boxes.

### Steps To Reproduce

.

**Comment by Noorsesverre** [comment]
Vi (AT) har nytte av at denne buggen blir fikset!
