### ISSUE TITLE
Summary/PDF - rendered before dynamic options are loaded

### ISSUE THREAD

**Issue by lassopicasso** [Altinn/app-frontend-react#1556]
### Description of the bug

In the context of implementing Tanstack Query in useGetOptions and PDF, we've identified a bug that occurs in certain scenarios where options are not fully loaded/fetched before they are displayed in the PDF or Summary. 

This issue is primarily associated with dynamic options, which do not appear to finish loading before they are rendered in PDF or Summary. It has been observed by @bjosttveit that the `initiallyLoaded` variable within `useAllOptions` is being set to true before it has actually finished loading. This was done by wrapping the reducer of `allOptions`, enabling it to log the state of `initiallyLoaded` for each update. 

![image](https://github.com/Altinn/app-frontend-react/assets/74791975/8e2e1598-e3ba-437f-861c-6653fd355d39)

### Steps To Reproduce

Here's an example to reproduce this issue:
1. Start the frontend test app in the `changeName` form.
2. Reduce the network speed (I set it to d: 200kb/s, u: 200kb/s and latency: 4000ms).
3. Refresh the page
4. In the drop-down lists under "Referanser", change the option in source, then quickly navigate to the summary page.
5. You will probably notice that "Referanse2" hasn't had enough time to fetch before the summary is rendered. It should display the same value as Referanse.
![image](https://github.com/Altinn/app-frontend-react/assets/74791975/a271bec7-3bb9-4c9d-9892-bab7a417aad1)

6. If you refresh the page while on the summary page, the issue won't resolve itself. To fix this, you need navigate back to `form` so that these dynamic options can finish rendering. After that, navigate back to the summary page again.

**Comment by bjosttveit** [comment]
Looks like a different bug, but values in Referanse and Referanse 2 are not getting cleared when the source field changes. This Works in frontend-test-v3.

https://github.com/Altinn/app-frontend-react/assets/47412359/564b3cd9-903a-4c2a-bb8f-1c42cf22d067

**Comment by RonnyB71** [comment]
The different bug mentioned, where Referanse and Referanse 2 doesn't get updated. In my case, Referanse gets cleared when the first dropdown changes, but Referanse 2 does not. Referanse 2 does get cleared when Referanse changes.
