### ISSUE TITLE
Format text for PDF component

### ISSUE THREAD

**Issue by magnusrf** [Altinn/app-frontend-react#1570]
**Update 06.08.24**

The updated summary/PDF styling will have medium weight input values. And we are looking to do the same for this type of text.
It will be the reverse of what you are asking for here, but it will be in line with the rest of the styling and will be slightly easier to scan when reading.

### Description

Is it possible to change the styling for the `InstanceInformation` component and get bold text for example, somthing similiar to this: 
<img width="761" alt="pdf comp" src="https://github.com/Altinn/app-frontend-react/assets/32111471/66ab569f-64c7-487b-82d1-ca4e8b5d16cf">

**Comment by Edavda** [comment]
The updated summary/PDF styling will have medium weight input values. And we are looking to do the same for this type of text. 
It will be the reverse of what you are asking for here, but it will be in line with the rest of the styling and will be slightly easier to scan when reading. 

Example here: 


![Image](https://github.com/user-attachments/assets/24680e45-157a-4b75-8ddc-dc10c74e677c)
