### ISSUE TITLE
Cleanup of store in app-frontend 

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#159]
## Description

Currently we have disabled the default `serializableCheck` and `immutableCheck` redux middlewares as we have some operations that currently mutates the redux state + non-serializable elements. This could lead to unexpected behaviour and should be fixed.

Seems to be related to our handling of variables in text. Need to investigate further.

```
getDefaultMiddleware({
      // TODO: enable once we have cleaned up our store
      serializableCheck: false,
      immutableCheck: false,
    })
```

## To Reproduce
1. Enable default redux middleware
2. See errors

## Expected behavior
No mutations and state should be serializable.

## Tasks

- [x] Fix immutability issues https://github.com/Altinn/app-frontend-react/pull/186
- [x] Fix serializable issues

**Comment by olemartinorg** [comment]
Should be fixed in #372! :partying_face: The TODO has been removed, and both serializable and immutable checks are on now.
