### ISSUE TITLE
AlertOnChange is broken for Checkboxes

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1593]
I found a problem when testing #1558. In Checkboxes, the dialog appears twice. Sometimes the first button (near the top) works, but not all the time. Radio seems OK.

![20231020_11h56m40s_grim](https://github.com/Altinn/app-frontend-react/assets/700139/27a7257c-0a9e-4b53-921d-6813cd44be07)

_Originally posted by @olemartinorg in https://github.com/Altinn/app-frontend-react/issues/1558#issuecomment-1772441039_

**Comment by RonnyB71** [comment]
Seems to be working, needs verification.
