### ISSUE TITLE
Need a way to format datetime fields in the frontend

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/app-frontend-react#1609]
### Description

Currently, there is no other way to display a date in the specified users locale other than rendering a datepicker and using `displayValue`, expression on that component. 

I want to be able to use a function like `formatDateLocale` in an expression to be able to show dates that are now connected to a component on the correct format.

**Comment by lassopicasso** [comment]
I have tested the solution, and it works smoothly! Well done, @mikaelrss!
