### ISSUE TITLE
App crashes when pressing "send" if a validation error is triggered

### ISSUE THREAD

**Issue by allinox** [Altinn/app-frontend-react#161]
## Describe the bug
My app crashes when I hit "send inn" while I have an erroneous input in one of my fields (even though the field has validation).

## To Reproduce
What I did:
1. I opened my app, which contains validations on multiple fields. (The validations work as expected in general)
2. I fill out all fields in the correct manner except from one field where I have regex validation in my data model.
3. I move on to the summary page and hit "send inn"
4. The app crashes

The app in question here is [this one](https://altinn.studio/repos/ttd/krt-1021)

## Expected behavior
I expect the app not to crash but rather to stay on the final page and to have my error pointed out to me.

## Screenshots
Validation from data model (regex) that crashes on send

![image](https://user-images.githubusercontent.com/22012997/114690506-0e05c580-9d17-11eb-8a0a-908f4e363b22.png)
![image](https://user-images.githubusercontent.com/22012997/114709179-8fb41e00-9d2c-11eb-8572-833651f49f10.png)

Validation from ValidationHandler doesn't crash, but it does go through to the receipt even with the validation error

![image](https://user-images.githubusercontent.com/22012997/114697916-bff4c000-9d1e-11eb-9680-4d14c7df9d59.png)
![image](https://user-images.githubusercontent.com/22012997/114697947-cbe08200-9d1e-11eb-99eb-cfaa7a3778fe.png)

**Comment by olemartinorg** [comment]
@allinox Is this still an issue? If this happened for every app in every circumstance, this problem was probably solved long ago.

**Comment by FinnurO** [comment]
Closing. Assumed solved. Reopen if needed.
