### ISSUE TITLE
Accessibility issue with Grid title 

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#1650]
### Description of the bug

When using accessibility checkers we get warnings and errors consering our handling of titles for the grid component. We have been told that we should use `caption` instead of a `label` when setting up our grids (tables) 

**Example of an error**
![image (6)](https://github.com/Altinn/app-frontend-react/assets/33222679/11b59b54-6a6b-49dd-8cb2-fa8bdcb37362)

### Steps To Reproduce

1. Go to an app with a grid that has a title
2. Run wave or a similar tool 
3. You should get a warning or an error on the `label` element

**Comment by Magnusrm** [comment]
Caption is added for Grid in desktop mode, and fieldset for mobile view in the PR: #1693
