### ISSUE TITLE
Man må klikke 2 ganger på send inn ved bruk av myke kontroller i skjema

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#167]
## Description
Man må trykke på send inn knappene i skjemaet 2 ganger, når man har myke kontroller i skjema. 

## To Reproduce
Repo som bugen dukket opp i https://altinn.studio/repos/stian.vestli/ra0000-kontaktogkommentar.git
Enkelt skjema med bare 4 felter og en avhuking.
![image](https://user-images.githubusercontent.com/91887041/149936475-558dc366-fdb9-4913-b6a6-a2d80367cee5.png)

Avhukning har en hard kontroll, denne trigger også validering som setter Myke kontroller i ValidateData eventet.
`if (string.IsNullOrEmpty(model.Kontakt.kontaktPersonNavn))
               {
                    validationResults.AddModelError("Kontakt.kontaktPersonNavn", "*WARNING*SkjemaNavn.Error"); // viser feilen på feltet MYK kontroll
                }`

Denne kontrollen er satt på alle 3 felter foruten kommentarfeltet.
Den harde kontrollen er også tatt hånd om i ValidateData:
`if (string.IsNullOrEmpty(model.Kontakt.kontaktInfoBekreftet))
                {

                    validationResults.AddModelError("Kontakt.kontaktInfoBekreftet", "SkjemaBekreftelse.Error"); 
                    validationResults.AddModelError(nameof(Kontakt.kontaktInfoBekreftet), "SkjemaBekreftelse.Error"); øverst i bildet
                    
                }else
                {
                     validationResults.AddModelError(nameof(Kontakt.kontaktInfoBekreftet), "*FIXED*SkjemaBekreftelse.Error"); //*FIXED* 
                }`

For den harde settes det 2 feilmedlinger for å vise hvilket felt det feiler på på toppen av skjema ved kontroll, det settes også en FIXED tag slik at denne fjernes når feilen er rettet.

Ved å trykke send inn uten å ha fylt ut noe vil den stoppe deg:
![image](https://user-images.githubusercontent.com/91887041/149937295-ab010d9c-b663-4461-a38f-2384a3d9703c.png)

Hvis man nå huker av bekreft så skal man kunne sende inn skjema siden resten av kontrollene er myke:
![image](https://user-images.githubusercontent.com/91887041/149937433-c84defd6-3cf4-462c-a5bb-efdc276b0535.png)

Her må man da trykke 2 ganger på send inn, første gangen tenker den bare litt også skjer det ikke noe mer.

## Expected behavior
Et trykk på send inn skal være nok siden det er myke kontroller.

**Comment by StianVestli** [comment]
Så det du sier er at man må ha et påkrevd felt for at man skal kunne trigge den mjuke kontrollen. Det beste er jo om en kunne satt at et felt skal ha mjuk kontroll på lik linje som påkrevd, men også da kunne koblet til en kontroll ala vis skjul. Men i saken over så dukket den mjuke opp men man måtte trykke to ganger på send inn etter at den var vist for at det skulle skje noe det var vel det man syntes var litt rart.

**Comment by StianVestli** [comment]
Jeg ser vel at problemet i repoet her var at avhukingen for "bekreft info" trigger validation som da viser mjuke kontroller , og at man da må trykke send inn to ganger etter at meldingene kommer opp. Dette har nok med at koden i valideringen ikke er god nok slik at den ikke skiller på hvem som kaller validation.
Men når det er sagt så jeg mener at hvis en bruker har fylt ut alle felter riktig så skal ikke mjukekontroller vises. Mjuke kontroller burde ligge frontend og ikke slik de ligger i dag. Mulig at bedre feedback til brukeren når man trykker på neste eller send inn og vi bedre opplevelsen når man må trykke to ganger. Jeg satt litt med følelsen de første gangene at jeg ikke hadde trykket på knappen , sjølv om jeg hadde gjort det.

**Comment by olemartinorg** [comment]
Nå har det skjedd små endringer i app-frontend siden den gang dette ble registrert, og nå lagrer vi iallefall underveis mens man skriver i et felt (ikke bare når man flytter fokus ut av det). Det bør da trigges validering på felt som skal gi myk validering _før_ man trykker for å gå til neste side. Å kreve dobbel-klikking noen steder (tilsynelatende helt uten et mønster for brukerens del) gir bare dårlig UX. Putter på `good-first-issue` på denne da jeg tror (og håper :pray:) at dette kan være noenlunde enkelt å fikse. Om noen begynner å jobbe med denne og sliter med å finne ut av det, ikke nøl med å spørre meg!
