### ISSUE TITLE
Layout settings for receipt pages and instance selection

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/app-frontend-react#1686]
### Description of the bug

Currently. There is no way of setting the `showLanguageSelector` or `hideCloseButton` pages that are not a part of a layout set. #1682 Refactores these settings to use a `UiConfigContext`. This highlighed a new problem. The current way of fetching these values uses the layout settings, which mean that, for instance `showLanguageSelector` can only be specified in a layout set. This means that for instance selection and receipt pages, there is no way of showing the language selector. This worked previously because the settings of the last page was stored in redux and subsequently used in the receipt page.

### Steps To Reproduce

No steps to reproduce, but the app developers do not have a way of specifying whether the language selector should be visible on pages outside layout settings. 

### Additional Information

We need to agree on an API for the app developers to be able to set these settings also outside of the current layout set.

**Comment by olemartinorg** [comment]
As noted in #1712, I think I have a fix in place for this already there. I'll put me as assigned to this issue and be sure to write tests for it.
