### ISSUE TITLE
Devtools Issues in v4

### ISSUE THREAD

**Issue by lassopicasso** [Altinn/app-frontend-react#1701]
### Description of the bug

Some bugs have occurred in devtools during the work on v4. The following have stopped working:

- Scrolling
- Navigation
- Switching frontend version

*Add to the list if anything else in devtools is uncovered.*

Another issue related to devtools: https://github.com/Altinn/app-frontend-react/issues/1613

### Steps To Reproduce

1. Open an app
2. Open devtools
3. Test the different functionalities in devtools

**Comment by bjosttveit** [comment]
The issue with switching frontend version seems to be caused by the new page navigation. After switching from a v4.x version to a v3.x we need to remove the new parts of the URL (e.g. `/Task_1/form`) to make it load properly.
