### ISSUE TITLE
Task and page path is added to the URL recursively crashing the page (v4)

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#1702]
### Description of the bug

If you remove the `task/page` part of the url, but leave a `/` remaining after the instance id, the `task/page` part gets added back recursively until the page crashes.

https://github.com/Altinn/app-frontend-react/assets/47412359/d3bc1bab-b35c-4adf-92db-0472b7a5ab1d

### Steps To Reproduce

1. Open an app in v4
2. Remove `task/page` from the url leaving it like `#/instance/partyid/instanceid/` (the final slash is important)
3. Observe the `task/page` getting added recursively until the page crashes

**Comment by olemartinorg** [comment]
Fix on the way in #1175

**Comment by olemartinorg** [comment]
Fixed in #1175
