### ISSUE TITLE
Text: Bruk av tekst i dynamiske utrykk og med variabler fungere ikke sammen

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1716]
### Description of the bug

Vi bruker dynamiske uttrykk for å hente ut tekst:
`["text","S07.tittel.repgrp.petroleumgass"]`

Tekstidenten får info fra datamodellen:
```
{
      "id": "S07.tittel.repgrp.petroleumgass",
      "value": "{0}",
      "variables": [
        {
          "key": "SkjemaData.GassOgPetroleumKost[{0}].produktTypeBrukt",
          "dataSource": "dataModel.default"
        }
      ]
}
```
Men den returnere da ikke data fra datamodellen men men bare:  {0}
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/28a78575-6143-47fc-b26e-70d78f7051d7)

Bruker jeg tekst identen rett mot et titelfelt og da funker det:
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/38bd49bf-3fa4-441d-ac40-d6749dab753b)
Koden til feltet over:
```
{
        "id": "Header-hhCUJH",
        "type": "Header",
        "size": "M",
        "textResourceBindings": {
          "title": "S07.tittel.repgrp.petroleumgass"
        }
},
```

### Steps To Reproduce

Koden til skjema ligge her https://altinn.studio/repos/stian.vestli/ra0439-01.git det er gruppen på side 7 commit id 56727766d85d70dbf3012be00f98fcea08532320

Samtale på Slack: https://altinn.slack.com/archives/C02EJ9HKQA3/p1704271430752939

**Comment by mikaelrss** [comment]
Det ser ut som dette fungerer som det skal i v4.
