### ISSUE TITLE
Dynamic expression text function strips away html/markdown from text resources

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/app-frontend-react#1728]
### Description of the bug

Markdown and HTML is stripped (in some cases from the `text`-function)

### Steps To Reproduce

1. Create a text resource with markdown/HTML
2. Use it directly in a paragraph: 
```json
 "textResourceBindings": {
    "title": "my-text-resource"
  },
```
3. See that the markdown/HTML is applied to the text
4. Use the same text resource via an expression:
```json
 "textResourceBindings": {
    "title": ["text", "my-text-resource"]
  },
``` 
5. See that it does not apply markdown/HTML

## Following below are some examples, all utilize these two paragraph components:
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/893c9eb0-6b79-4e8d-9f89-71a6740e424f)

### Text resource with HTML. 
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/dac77e76-9639-47bb-b19f-e8fdc1b7ca95)
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/6918d4f8-3007-4a8f-bebe-3c1df443b5bb)

### Text resource with HTML _and_ Markdown:
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/0bf2f59f-8c46-4e84-9b9c-32df64899013)
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/5f9daf02-9f25-4e3b-979b-2c5389a5e647)

### Text resource with only Markdown: 
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/855c2361-c532-45ce-8d63-3a0548263bb1)
![image](https://github.com/Altinn/app-frontend-react/assets/26043795/0b899d96-7962-490a-9e69-d1c0056b0aa0)

**Comment by olemartinorg** [comment]
I assume this is because expressions have to return strings/basic data types, and this is using `langAsString()` which now has this behaviour. We might want to use the `langAsNonProcessedString()` function instead here, then.

**Comment by mikaelrss** [comment]
I've already tried with the `langAsNonProcessedString` and it seems to work. Just need to run tests 🙌
