### ISSUE TITLE
Logo stretches when the appOwner title is too long 

### ISSUE THREAD

**Issue by magnusrf** [Altinn/app-frontend-react#1734]
### Description of the bug

![image](https://github.com/Altinn/app-frontend-react/assets/32111471/2172a4cb-6210-4306-ae52-4992668f481c)
The square logo stretches when the appOwner title is too long 

### Steps To Reproduce

use square org logo and an appOwner title that is long

**Comment by RonnyB71** [comment]
Closing, duplicate of https://github.com/Altinn/app-frontend-react/issues/1739
