### ISSUE TITLE
Go over to material-ui core v5

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#174]
## Description
Material-UI has released v5. These changes include some rather big changes (and some breaking) (https://mui.com/blog/mui-core-v5/). We should update to v5 in our different solutions.

## Acceptance criteria
- All solutions use material-ui v5.

## Specification tasks

- [ ] Development tasks are defined

## Development tasks
- [ ] Studio
  - [ ] dashboard
  - [ ] app-development
  - [ ] schema-editor
  - [ ] shared
- [ ] Apps
  - [ ] app-frontend
  - [ ] shared
  - [ ] receipt

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by RonnyB71** [comment]
Won't do - using Felles Designsystem
