### ISSUE TITLE
How do we solve digital signatures and confirmations in Altinn 3 

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#175]
## Description
This is a placeholder issue for the upcoming work on digital signatures and confirmations in Altinn 3.

## In scope
Research: What are the needs

## Tasks
- [ ] First task is to define what needs to be done
- [ ] QA has been done

**Comment by olemartinorg** [comment]
Related to:
- #291
- https://github.com/Altinn/altinn-studio/issues/8944
