### ISSUE TITLE
JsonPatch: Better support for uniquely identifying rows in repeating groups 

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1750]
With the new JsonPatch saving method, we still allow users to make changes to the data model in the time between when we send a save request to the backend and the point at which we receive a reply from the backend with the full (and possibly changed) data model. To make this work, we compare the data we got from the backend with the current data we have on the frontend, and we try to make a decision based upon some rules:

1. If a value such as a `string`, `number` or `boolean` changed in the backend while it also changed on the frontend (i.e. the user made a change to it) we overwrite the changes the backend did - which will also schedule a new save request for later. If the backend did not make the changes, but another (or the same) user made a change outside of the current app-frontend session, the save request will fail when the backends expectations in the `test` operation fails in a later request - so we can only possibly overwrite (perceived stale) data received from the backend such as those made automatically by `ProcessDataWrite` and automatic population of `null` or default values from the typed data model.
2. If there are changes in a repeating group (i.e. `Object[]`), we employ a LCS (Longest Common Subsequence) algorithm using the `fast-array-diff` package, along with our own custom comparison function in order to figure out if a row (object in the array) looks like they represent the same row as the one we already had locally, or if the backend meant to remove one row and add another.

It's the second part here that is currently very brittle and sub-optimal. With more details in a [lengthy thread on Slack](https://altinndevops.slack.com/archives/C045EB3JA9X/p1706104091281899), we're hoping to implement a way to add metadata for these objects to uniquely identify them and differentiate them. In frontend then, we should be able to:

1. Reduce the complexity of our custom `isSimilarEnough()` function by comparing the unique IDs
2. Add code to automatically generate unique IDs for new rows, and for those rows we get from the backend that are missing unique IDs (which we should assume are new rows in `isSimilarEnough()`).
3. Remove the code in the `group.ts` Cypress test that introduces waiting until rows are saved before continuing the tests. Running this test on github + tt02 should reveal if the code fixes the core issue, as these tests failed often before these workarounds.

**Comment by RonnyB71** [comment]
Uniquely identifying rows in a repeating group should also cater for the application developer to specify what that key should be. Ideally we should have a default that just works, but if the application developer prefers a field that is part of the data model he/she should be able to specify what the unique key is. We should also support composite keys, specifying an array of fields to be used as key.

**Comment by olemartinorg** [comment]
I think that should its own issue. If we decided to make the unique key configurable by the app developer, they probably also want to make it *changeable* by the user. If we then start actually building the features in app-frontend we want to build upon this row-uniqueness, it would behave like a buggy experience for the user. So, for example, if we use that configured key to optimize renders in React, we'd also reset the state telling us that the row is open for editing when the key changes - thus changing the key would cause the row to close for editing.
