### ISSUE TITLE
Schema validation fails for `null`/`undefined` values

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#1752]
### Description of the bug

Schema validation returns an error if the field has a `format` constraint and the value of the field is `null` or `undefined`. I think the reason for this is that there was an assumption that empty fields will be removed entierly from the data model (key deleted). This may no longer be the case after all of the data saving changes(?). Fields that do not exist are not validated against the schema and so this used to work as it should. Schema validation should generally not give any errors if the field is empty, as this is `required` validation's job to handle. This should probably be solved by explicitly returning an empty validation array for schema validation if the field is empy, `null` or `undefined`.

- Slack: https://altinn.slack.com/archives/C02EJ9HKQA3/p1706277321354569?thread_ts=1706099835.186329&cid=C02EJ9HKQA3

### Steps To Reproduce

1. Set `"showValidations": ["Schema"]` on a field
2. Have the value of that field somehow be `null` or `undefined`

**Comment by RonnyB71** [comment]
1. Add input that fails, verify that schema validation shows
2. Remove the input value, verify that the schema validation is removed
3. Refresh the page (F5), note that the schema validation error is no back
4. Adding a value and removing it again will clear the error
