### ISSUE TITLE
?language=${language} query parameter in more places

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-frontend-react#1774]
### Description

New developments in backend adds the expectation that frontend adds the ?language=${language} query parameter in

* `{org}/{app}/instances/{instanceOwnerPartyId:int}/{instanceGuid:guid}/process/completeProcess` (not sure if frontend uses this)
* `{org}/{app}/instances/{instanceOwnerPartyId:int}/{instanceGuid:guid}/process/next` (optional, but nice for consistency, see https://github.com/Altinn/app-lib-dotnet/pull/433)
* `validation` (added in https://github.com/Altinn/app-lib-dotnet/pull/423)
* `instance/../data` (previously added in https://github.com/Altinn/app-lib-dotnet/pull/405)

Somehow I'm starting to think that a header that we set everywhere kind of makes more and more sense as we start adding the query parameter everywhere.

**Comment by RonnyB71** [comment]
Noticed this in requests to options endpoint as well, seems like language isn't passed on from frontend.

**Comment by RonnyB71** [comment]
On the topic of query parameter vs. header we should think about direct links to steps/pages and that would probably require language support as well.

**Comment by ivarne** [comment]
For `process/next` we use `?lang=` instead of `?language=`. It's awkwardly coded (implicitly found in http context), so I did not see that there were two conventions in use.

What to do? I suggest switching frontend to `language` everywhere and make backend handle either for pdf language in `process/next`?
