### ISSUE TITLE
Use `@xsdType` hint in JsonSchema when converting types before sending to backend

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1776]
Our current `convertData()` function was implemented based on a few (wrong) assumptions, for example that `integer` in JsonSchema maps to `int`/`int32` in C#, and that `number` maps to `decimal`.

Studio maps types a little differently when generating models, and we should account for that. See this clarification:
- https://altinndevops.slack.com/archives/CDU1S3NLW/p1706875045501569

Also, search for `@xsdType` in existing schemas for good examples.

**Comment by bjosttveit** [comment]
Ran a quick search of `@xsdType` over the apps from [altinn-fetch-apps](https://github.com/olemartinorg/altinn-fetch-apps), which of these needs to be checked? @olemartinorg @mirkoSekulic 

```bash
❯ awk '{if ($1 ~ "xsdType") {if ($2 == ":") {print $3} else {print $2}}}' **/*.schema.json | sort | uniq -c | sort
   1 "Integer",
   1 "short",
   2 "XmlSimpleContentExtension",
   4 "XmlAttribute",
   6 "int",
  14 "nonNegativeInteger",
  15 "#ref"
  17 "dateTime",
  22 "gYear",
  44 "token",
  52 "date",
  57 "decimal",
 144 "double",
 155 "long",
 171 "#ref",
 195 "positiveInteger",
 355 "boolean",
 674 "XmlSimpleContentExtension"
 694 "integer",
 991 "XmlAttribute"
4997 "string",

```

**Comment by olemartinorg** [comment]
Seems like a bit of a mess, but we'd need to figure out a mapping from those `@xsdType` values to their corresponding generated types in C#. Do you have such a mapping somewhere in Studio we can look at for inspiration, @mirkoSekulic? I would think this mostly counts for numeric types, but we should also account for booleans, and possibly dates.

I would assume that the `XmlAttribute`, `XmlSimpleContentExtension` and `#ref` values could safely be ignored (i.ie, if not a valid numeric/boolean/date type, assume the C# type is string).

**Comment by olemartinorg** [comment]
@mirkoSekulic Did you get a chance to look at this?

**Comment by olemartinorg** [comment]
Rapport fra testing:
> int (-2147483648 til 2147483647)  og short (-32768 til 32767) gir feil på rette grenseverdier
