### ISSUE TITLE
Ability to preview the PDF before submitting the form

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#1804]
## Acceptance criterias
- [ ] It should be possible to add a button in the layout that will show the PDF preview as described above.
- [ ] When calling the PDF endpoint to create a preview of the PDF, the PDF footer should show the default or configured "Forhåndsvisning" text.
- [ ] At any point during a process of completing a form, the user should be able to preview the PDF using the PDF layout as it would be used in the PDF creation process.

**Comment by Magnusrm** [comment]
I have tested this and it works nicely! ✨

**Comment by bjosttveit** [comment]
Repoening this, see https://github.com/Altinn/app-frontend-react/pull/2489#issuecomment-2426253555
