### ISSUE TITLE
Inconsistent Language Display in AddressComponent

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-frontend-react#1809]
### Description of the bug

Currently, the AddressComponent labels in some scenarios display the incorrect language. This occurs because the address component relies on the language set in the end user's Altinn profile. 
Consequently, the Altinn 3 app may display the wrong language in the AddressComponent text labels when the selected language in the user's profile is not supported by the specific App. This issue extends to cases where application supports languages other than Bokmål, Norwegian Nynorsk, and English, resulting in incorrect language display.

In this excample the app only support Bokmål but the user profile is set to English, so the app show a mix of Bokmål and English. 
![image](https://github.com/Altinn/app-frontend-react/assets/75472603/73ad3f84-6464-4fec-9002-bfac42f22364)

To address this issue, implementing the following solutions may solve the problem:

1. Language Control: The AddressComponent should be controlled by the language selected within the application rather than relying on the language set in the end user's Altinn profile. This ensures consistent language display regardless of the user's profile settings.

2. Customizable Text Labels: Provide developers with the ability to customize the text labels of the address component using language files. This flexibility allows developers to tailor the text labels according to the specific language requirements of their application.

### Steps To Reproduce

1. Log on to tt02 and set the langue to English.
2. Open an app that do not support English langue and use the AddressComponent.

**Comment by adamhaeger** [comment]
Solution number 2 is implemented here: https://github.com/Altinn/app-frontend-react/pull/1880
Therefore closing the issue.
