### ISSUE TITLE
Finish up Altinn Community file for release

### ISSUE THREAD

**Issue by Edavda** [Altinn/app-frontend-react#1813]
The Apps team is taking over responsibility for the Altinn community file in Figma. 
In order to release a first version to the public, we need to go over the contents and add the necessary examples and components that are missing. 

- The community file should be a simple component library for those that want to build something in Figma.
- It can contain components from both Apps and Studio. Components that are only available in Apps will be marked. 
- The file should contain examples of good practices in use of the available components. 

https://www.figma.com/file/vbj2Gii5KY8vV16Oyr92xw/Community%3A-Altinn-Studio-Apps?type=design&node-id=811-24258&mode=design&t=9wIGtKLkv9lO9DjX-4

UPDATE - Released 22.02.24
https://www.figma.com/@Altinn

**Comment by Annikenkbrathen** [comment]
Kan denne lukkes? @Edavda @olavflar

**Comment by Edavda** [comment]
@Annikenkbrathen Ja, den kan lukkes. Første versjon er lansert :)
