### ISSUE TITLE
ReadOnly input felter og read only rader i repeterende grupper og grid v4 av frontend

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1833]
### Description

I dag benyttes read only felter i rowsafter i repeterende grupper og grid.
Rowsafter settes da til read only og får en gulfarge, slik:
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/f4752862-77e1-4847-bd04-c57309f59d28)

Med V4 av front en så vil vi nå få ny inputfelt fra designsystemet som vil gi oss en grå bakgrunn på feltet når det settes til read only:
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/19d2d88b-3520-49e3-809c-a14a0cbd114b)

Det er da viktig at man ikke får gråbokser i gule rader, noe en vil få hvis readonly fargen ikke settes til grå for alle komponenter.

Det beste er om vi faktisk kan styre read onlyfargen sjølv på komponentene, dvs velg gul eller grå. Det kan være tilfeller der man vil ha gul bakgrunn på feltet feks ved en summering av flere enkeltefelter.

**Comment by olemartinorg** [comment]
Jepp, vi må finne ut hvordan vi skal håndtere disse readOnly-fargene på tabell-rader/kolonner når vi bytter ut komponenten med den nyere fra designsystemet. Vi triksa dette til den gang ved at vi brukte samme gulfarge i tabellen som vi hadde i input-feltene, slik at readonly tabell + readonly input-felt = det ser ut som det bare står en verdi i raden.

Ettersom tallformattering bare finnes i Input-felter (ikke når man presenterer data som ren tekst) ble det altså gjort slik, for at man da kunne presentere ting som dette (pent formattert summering i siste rad, hvor summeringstallet ser noenlunde likt ut som input-feltene i tabellen over). Men dette er da altså noe vi må tenke på om readOnly-fargen blir til grå etter #1823.

Tagger @olavflar @Edavda og @adamhaeger, til info.

**Comment by olemartinorg** [comment]
Legger ved et bilde av hvordan dette ser ut etter oppgradering av Input-komponenten fra designsystemet:

![20240311_13h33m09s_grim](https://github.com/Altinn/app-frontend-react/assets/700139/43ed9cf7-b23c-4398-9f9f-ccdf0c616930)

**Comment by Edavda** [comment]
Forstår jeg det riktig da at gulfargen på hele raden kommer av en workaround som skulle få hele raden til å være lik readOnly-feltene? 
Er det et alternativ å endre fargen på summeringsrader til å være grå? 

Fargelegger vi hele raden kun for at den skal skille seg ut (og se mer ryddig ut), eller er det viktig at den er en spesifikk farge?

**Comment by olemartinorg** [comment]
Det ikke viktig med en spesifikk farge, nei - det er fritt frem å foreslå noe annet. I utgangspunktet ble dette laget slik for å matche readOnly-fargen på feltene ja, og vi har ikke eksponert konfigurasjon for å sette en spesifikk farge (dette er ikke satt opp med `"yellow": true`, men med `"readOnly": true`). Med andre ord, ja, vi står vel fritt til å endre fargen.

**Comment by StianVestli** [comment]
Ellers så er det ikke noe i veien for å gi oss muligheten til å styre readonly fargen heller mellom grå og gul. Men man må kunne matche de slik at summeringsraden og feltene er like.

**Comment by Edavda** [comment]
Skjønner! 👍 

Jeg foreslår at summeringsraden bruker samme farge som readonly feltene. Så nå som feltene har blitt grå, så tenker jeg at raden burde også være grå. Jeg er redd for at overskriving av readonly-fargen vil innføre unødvendig kompleksitet, så lenge dette kan løses på denne måten. 

Da vil fargene først og fremst matche og vi beholder et ryddig uttrykk i summeringsraden. 
I tillegg så vil dette være et prinsipp som gjør det lettere å forholde oss til denne typen endring i fremtiden. Summeringsraden er i prinsippet en readOnly rad, så jeg tenker det gir mening at den følger samme mønster som feltene. 

Legger ved en skisse på hvordan det kan se ut 👇 


![Image](https://github.com/Altinn/app-frontend-react/assets/2195512/3461a9e6-8b77-4979-824c-b25c658b50cf)

**Comment by Magnusrm** [comment]
@adamhaeger Tested the new read-only row, it looks and works very well! 👏 . I think maybe it would be nicer if the focus style of the read only field would be equal to the other components. And maybe even inflate the height of the element to match the height of the inputs.

Sidenote: The element is focusable because the field can have validations and we need to focus the field when navigating from a reported relevant validation error.

<img width="610" alt="image" src="https://github.com/Altinn/app-frontend-react/assets/32294735/162b139d-f3c5-4c88-91c2-2613c6666eeb">
<img width="529" alt="image" src="https://github.com/Altinn/app-frontend-react/assets/32294735/2a41e92e-6d54-43bc-997e-023928e347af">
