### ISSUE TITLE
Dynamic codelists not working in repeatable groups.

### ISSUE THREAD

**Issue by JohanGuntherKrogevoll** [Altinn/app-frontend-react#184]
## Description
Initially i wanted to have a dynamic codelist on a checkbox-component based on data selected in a radiobutton. Both of these components is inside a nested repeatable group. I tried to do this like this: 
```
"optionsId": "injuries",
"mapping": {
  "Victims{0}.Injuries{1}.BodyPart": "bodypart"
}
```
But it seems like this is not supported. 

While i was experimenting with this i noticed that this still don´t work even if i used data that was not nested as input to the OptionsProvider, like this: 
```
"optionsId": "injuries",
"mapping": {
  "Remarks": "bodypart"
}
``` 

I´m not sure if i should have reported this as a feature request instead as it seems like dynamic codelists in nested repeatable groups is not supported. That is what we initially want to do..

## To Reproduce
1. Set up a layout where there are components with dynamic codelists in repeatable groups:
```
{
  "$schema": "https://altinncdn.no/schemas/json/layout/layout.schema.v1.json",
  "data": {
    "layout": [
      {
        "id": "test",
        "type": "RadioButtons",
        "textResourceBindings": {
          "title": "TEST (Damaged bodypart)"
        },
        "dataModelBindings": {
          "simpleBinding": "Remarks"
        },
        "optionsId": "bodyParts",
        "required": true
      },
      {
        "id": "test-checkbox",
        "type": "Checkboxes",
        "textResourceBindings": {
          "title": "Test checkbox"
        },
        "dataModelBindings": {
          "simpleBinding": "Submitter.Firstname"
        },
        "required": true,
        "optionsId": "injuries",
        "mapping": {
          "Remarks": "bodypart"
        }
      },
      {
        "id": "victimGroup",
        "type": "Group",
        "dataModelBindings": {
          "group": "Victims"
        },
        "maxCount": 20,
        "children": [
          "test-checkbox-in-group",
          "injuryGroup"
        ],
        "textResourceBindings": {
          "add_button": "addNewPerson"
        }
      },
      {
        "id": "test-checkbox-in-group",
        "type": "Checkboxes",
        "textResourceBindings": {
          "title": "Test checkbox in group"
        },
        "dataModelBindings": {
          "simpleBinding": "Submitter.FirstName"
        },
        "required": true,
        "optionsId": "injuries",
        "mapping": {
          "Remarks": "bodypart"
        }
      },
      {
        "id": "injuryGroup",
        "type": "Group",
        "children": [
          "test-checkbox-in-group-in-group"
        ],
        "maxCount": 10,
        "dataModelBindings": {
          "group": "Victims.Injuries"
        }
      },
      {
        "id": "test-checkbox-in-group-in-group",
        "type": "Checkboxes",
        "textResourceBindings": {
          "title": "Test checkbox in nested group"
        },
        "dataModelBindings": {
          "simpleBinding": "Submitter.Firstname"
        },
        "required": true,
        "optionsId": "injuries",
        "mapping": {
          "Remarks": "bodypart"
        }
      },
      {
        "id": "73a3192c-16d2-4e4a-834a-08a29ec1cfef",
        "type": "NavigationButtons",
        "textResourceBindings": {
          "next": "next",
          "back": "back"
        },
        "dataModelBindings": {},
        "showBackButton": true
      }
    ]
  }
}
```
2. Change the data used as input for the OptionsProvider.

## Expected behavior
All checkbox components should change codelists based on the input.

## Screenshots
![Kapture 2022-05-31 at 13 13 12](https://user-images.githubusercontent.com/66003225/171160928-ccc60890-7d37-4e5d-b134-0d3271d56d53.gif)

## Additional Info
- [Relevant slack discussion](https://altinn.slack.com/archives/C02EJ9HKQA3/p1653652016361529)
- [Link to app where we want to implement dynamic codelist based on input from radiobuttin in the same nested group.(on the last commit when this is published)](https://altinn.studio/repos/dsb/uhell-med-fyrverkeri/src/commit/10da449faf062c4302e83c88f25df9e3e629cdfb)
- We want the behavior of the "Test checkbox" in the GIF above in the nested group demonstrated below ↓
![Kapture 2022-05-31 at 13 24 53](https://user-images.githubusercontent.com/66003225/171162946-bb1b4115-20ff-4dff-89fe-248cc5bd85eb.gif)

**Comment by Magnusrm** [comment]
Tested ok for demo app and implementation in own test-app 🥇
