### ISSUE TITLE
Dynamiske uttrykk for å sette "required" fungerer ikke som forventet i v4

### ISSUE THREAD

**Issue by lundjoakim** [Altinn/app-frontend-react#1876]
### Description of the bug

Når jeg setter en komponent til å være "required" med dynamikk, fungerer ikke dette som tiltenkt i v4.
Dersom en input-komponent blir satt som "required": true dynamisk, fungerer ikke valideringen når man ønsker å gå videre til neste side med mindre du først skriver noe inn i feltet og deretter tømmer feltet før du går videre.
Samme kode fungerer derimot fint i v3.

### Steps To Reproduce

1. Lag en input-komponent hvor "required" blir satt dynamisk basert på et felt i datamodellen.
Slik ser dette ut hos meg:
        "required": [
          "if", ["dataModel", "SkjemaData.Handel.solgteHandelsvarerJaNei01"], true,
          "else", false
        ]
2. Lag en radioknapp med binding til datamodellfeltet som blir brukt i dynamikken. ingen default verdi.
3. Legg til validering på navigasjonsknappene
4. Lag en ny side
5. Med radioknappen, sett input-komponent "required": true og forøsk å gå videre i skjema.

Resultat:
V3 - du kommer ikke videre i skjema (riktig oppførsel)
V4 - du kommer videre i skjema. Dersom du går tilbake i skjema og gjør dette, vil validering fungere:
1. skriv noe inn i inputfeltet
2. fjern deretter det du skrev i inputfeltet
3. naviger  til neste side

### Additional Information

Dersom du ønsker å teste dette i mitt repo, og sammenlikne v3 med v4:
https://altinn.studio/repos/Joa-lun/ra1100-01
Branches:
Master (v3)
v4 (v4)

Dette problemet dukker opp på side f10_S06_FordelingAvOmsVirks. Her vil radioknappen toggle "readOnly" og "required" på siste kolonne i repgruppa.

(Husk autoCreate= true og sett testdata i InstantiationProcessor.cs)

**Dette repoet er under arbeid og kan ha blitt endret siden denne rapporten ble skrevet**

**Comment by mikaelrss** [comment]
Det virker som om denne feilen har blitt fikset av denne commiten `6bb901857929ecf49368f8240d5493df86f3e56a`, så dette issuet burde være i orden ved neste release av v4.
