### ISSUE TITLE
As a user I would like to see my progress in the application

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#188]
## Description
We should look into including a progress bar as component for our forms. For longer / more complex application it might give the user an extra feeling of progressing trough the form. 

## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
How would we calculate the progress? 
It might change depending on branching in the form. 

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
> Add tasks here

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by olemartinorg** [comment]
Foreslår at vi lukker denne saken, ettersom fremdriftsindikatoren som foreslått over ble implementert i #221. Hva gjelder videre arbeid rundt fremtidige fremdriftsindikatorer, bør det først og fremst foregå i designsystemet (som jeg ser @mrosvik har lenket til over).
