### ISSUE TITLE
Semantiske html-elementer på sidene

### ISSUE THREAD

**Issue by Janingetjosvoll** [Altinn/app-frontend-react#1885]
### Description

UU-nr.102:"Det er brukt semantiske html-elementer som f.eks. header, tabell, skjema, nav, footer og em for å tydeliggjøre informasjonsinnholdet i området."

Semantiske elementer som H1, H2, p, sectiom, aside etc hjelper assistende verktøy å analysere nettsiden og hvordan den er bygget opp og hva intensjonen med de diverse delene/elementene er ment å bli brukt til. De skal derfor kun være brukt unntaksvis ettersom det ikke gir noe ekstra informasjon om hva den delen er.

### Additional Information

Relevant dokumentasjon for UU-krav 102:

https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html
https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11
https://www.w3.org/WAI/WCAG21/Techniques/html/H101
https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G115
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H49

**Comment by Febakke** [comment]
@Janingetjosvoll 
Kunne du lagt ved noen eksempler på hvor dere har funnet feil på dette?

**Comment by Janingetjosvoll** [comment]
![image](https://github.com/Altinn/app-frontend-react/assets/141420368/35757fa2-20b8-49d6-8a7d-748dd47bc18f)

I eksempelet over er "main" den mest granulerte landemerke. For en skjermleser vil det bety at bruker ikke får oversikt over inndelingen innenfor selve main, som en seende person vil ha. Dette gjelder alt i skjemaet da det ikke er landemerker under "main" noen steder.

**Comment by Febakke** [comment]
@Janingetjosvoll 
Jeg er usikker på hva du legger i mer granulerte landemerker. Har du noen eksempler på hvordan dette er gjort andre steder? Det fins ikke så mange standard landmarks man kan bruke og `main` skal brukes på hovedinnholdet på siden. Som i vårt tilfelle vil det som ligger inne i modalen. 

Du kan se liste over landmarks og eksempler her: https://www.w3.org/TR/WCAG20-TECHS/ARIA11.html

Om vi skal granulere opp innholdet med egendefinerte landmarks burde det være en god grunn til det og opp til å app-utvikler å sette det der det er fornuftig. Jeg ser ikke for meg at vi kan få dette til på en god måte automatisk.

Også relevant fra Aria dokumentasjonen:
> Use these sparingly. Too many landmark roles create "noise" in screen readers, making it difficult to understand the overall layout of the page. [Kilde](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#3._landmark_roles)

Med tanke på hvor lite innhold det skal være på disse sidene tror jeg ikke vi burde granulere opp landmarks. Jeg er redd det vil skape mer kaos enn brukervennlighet. Ekstra granulering burde skje ved hjelp av gode overskrifter som også brukes av skjermlesere. 

Vi har oppgaget noen rare landmarks vi må fikse opp i. Dokumentert her: https://github.com/Altinn/app-frontend-react/issues/1925

**Comment by Febakke** [comment]
@Janingetjosvoll 
Jeg har laget et løsningsforslag her: https://github.com/Altinn/app-frontend-react/issues/1925
Gjerne kom med innspill 🙌 
Om det ikke er mer enn landmarks denne issuen handler om foreslår jeg at den lukkes og at dette blir fikset i #1925
