### ISSUE TITLE
For store tallverdier viser også påkrevd-validering (v4)

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#1890]
### Description of the bug
Dette gjelder skjema i v4 av front en og 8.0.0 av backend.

Jeg har satt validering på inputfelter på schema og component. feltet som det går mot har en felt begrensing på 13 tegn.
```
"showValidations": [
          "Schema",
          "Component"
        ]
```

Når jeg skriver inn et stort tall over 13 tegn kommer denne som er greit:
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/8ebfba8b-363f-48f7-b242-6a2a3fb42bc2)

Når vielegger inn flere tall så kommer denne feilen, som fortsatt er greit nok sjølv om den første feilen burde stått der fortsatt:
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/b2040f31-ca58-4fe7-af72-fef86b3f5411)
Dette er når en typisk får en verdi som er alt for stor , overflow.

Hvis jeg velger å gå videre i skjema til neste side, slik at validering av siden trigges, så får jeg flere feilmeldinger:
![image](https://github.com/Altinn/app-frontend-react/assets/91887041/148388de-86a9-45d0-9176-3718aa601541)

Her er det da dobbelt opp med feilmeldinger fordi en blanker verdien i bakkant, den står i feltet , men hvis jeg refresher siden så er feltet tomt.

### Steps To Reproduce

se over

**Comment by Magnusrm** [comment]
Tested the fix and it seems to work! 🎉
