### ISSUE TITLE
Find alternative to moment.js 

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#191]
## Description
As moment.js has nearly declared itself dead (https://momentjs.com/docs/#/-project-status/)

> In most cases, you should not choose Moment for new projects.
> We may choose to not fix bugs or behavioral quirks, especially if they are long-standing known issues.

We should find an alternative project to handle date/time in app-frontend. 
Some alternatives may be: https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/

## Acceptance criteria
A viable alternative is identified and has replaced moment.js where used.

## Specification tasks

- [ ] Identify where moment.js is used
- [ ] Test design / decide test need

## Development tasks
- [ ] Replace with new library
- [ ] Regression test

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by RonnyB71** [comment]
Moving this to later this year as we would like to use the new date picker implementation from the design system. The date picker is currently not top priority on neither backlogs, so waiting is fine.

cc: @mrosvik

**Comment by mikaelrss** [comment]
We've added a `formatDateLocale` function in this pr https://github.com/Altinn/app-frontend-react/pull/1610 which uses the native browser API to format dates. This would probably reduce the efforts of refactoring away from moment.

**Comment by RonnyB71** [comment]
https://github.com/Altinn/app-frontend-react/issues/602

**Comment by bjorntore** [comment]
Just for info, not a strong recommendation by any means: In a previous project the team moved from moment.js to day.js, and that was very easy to do. Exactly the same API, so fixed most of it using Find and replace "momen()" with "dayjs()" (and imports).

**Comment by altinnadmin** [comment]
> In a previous project the team moved from moment.js to day.js, and that was very easy to do

Yeah, also according to [the reccomendations from the moment team](https://momentjs.com/docs/#/-project-status/recommendations/), Day.js seems like the simplest replacement. Are there any good reasons for not just doing that?

**Comment by mikaelrss** [comment]
I am not sure if this is a show stopper, but the only thing I can think of at the top of my head is i18n and different date formatting for different locales. We support essentially any language in our apps, and would therefore have to preload every known locale (or default to norwegian/english for ones we decide to not support). I guess we might be able to solve this with code splitting and dynamically loading locales, but I think that might be a big complex. 

If we were able to rely on the native browser Intl API instead, we could be able to support any locale, but I am not sure if we can use this API to replace our current usage of moment.
