### ISSUE TITLE
"help"-bubble looks different for headers with "1." or similar in the title

### ISSUE THREAD

**Issue by CelineTrammi** [Altinn/app-frontend-react#1916]
### Description of the bug

If you are using a help-bubble in your header with "1. " in the title or similar, the help bubble is placed weirdly. 
```
{
   "id": "5-Header.title",
   "value": "5. Premier og inntekter fra megling"
},
```

![image](https://github.com/Altinn/app-frontend-react/assets/61122289/083b4a61-41a3-4465-8ef6-9e28bb2a9047)

Fix around this is to put asterisk in the value for the title. 
```
{
   "id": "5-Header.title",
   "value": "**5. Premier og inntekter fra megling**"
},
```

![image](https://github.com/Altinn/app-frontend-react/assets/61122289/b0d9e681-ab4a-4568-879f-9c200ea9c8aa)

### Steps To Reproduce

1. Create a Header component
2. Add `title` and `help` to the `textResourceBindings`
3. In title, add any type of text that has a number followed by `.`. I.e: "title":` "1. hei hei"`

### Additional Information

Previously, there was an issue with the numbers being removed in the title unless you added asteriks around the text. I saw that it was fixed in v4. However, this seems to be a new(?) bug that got introduced with it.

**Comment by olemartinorg** [comment]
@CelineTrammi We support markdown in texts resources, and I'm not aware of any changes that were meant to directly affect this. What I think happens here is that your "<number>. <text>" is interpreted as a numbered list, which probably is the reason it 'looks weird'.

Some tips:
- Wrapping in double asterix is how you mark text as **bold** in markdown, and not the way you escape a numbered list.
- Try writing `5\. Premier og inntekter fra megling` as a way to escape the numbered list

Let me know if that solves anything for this problem. :pray:

**Comment by CelineTrammi** [comment]
Thanks for the clarification, I did not know that it was interpreted as a numbered list!
Regarding the asterisk, it has just been passed down as a workaround for getting the desired behaviour in the title. But I won't pass that "tip" on further given this info ;)

This worked btw 😊  Many thanks!
```
{
  "id": "5-Header.title",
  "value": "5\\. Premier og inntekter fra megling"
},
```
