### ISSUE TITLE
Schema validation does not work with `-` in datamodel path

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#1918]
### Description of the bug

A field with a `-` in the datamodel path will not get any schema validations. This seems to be due to an edge-case in the `jsPropertySyntax` we get from `Ajv` which is not handled correctly.

Working example:
Path: `Oppgave.rapporteringsenhet.kontaktperson.epost_1`
Instance path from Ajv: `.Oppgave.rapporteringsenhet.kontaktperson.epost_1`
Result: `Oppgave.rapporteringsenhet.kontaktperson.epost_1`

Buggy example:
Path: `Oppgave.rapporteringsenhet.e-post`
Instance path from Ajv: `.Oppgave.rapporteringsenhet["e-post"]`
Result: `Oppgave.rapporteringsenhete-post`

This can be fixed either by fixing the `processInstancePath()` function on `jsPropertySyntax` or switching to using `jsonPointer` and using a new parsing method. (`jsPropertySyntax` has been deprecated in `Ajv` for some time anyways)

### Steps To Reproduce

.

### Additional Information

- We should also add some unit tests to check all kinds of edge cases when fixing this

_No response_

**Comment by olemartinorg** [comment]
Related, and would be nice to just fix at the same time, then:
- #166

**Comment by kentare** [comment]
Also discussed here: https://altinn.slack.com/archives/C02EJ9HKQA3/p1715846728479179
