### ISSUE TITLE
Drop down component: Auto complete

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#193]
## Description
As an app developer I would like to include auto complete in the drop down component. Some lists might be long and it would be a lot easier for the user to search rather than to navigate a drop down list. An example would be a list of all the countries.
 
## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations
> Describe input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
> Add tasks here

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by bjosttveit** [comment]
It is possible to search in dropdown now thanks to the `Select` component from the design system. Closing this as completed. Repoen if you disagree @Febakke
