### ISSUE TITLE
The help text icon remains visible even when the help text is empty

### ISSUE THREAD

**Issue by mlqn** [Altinn/app-frontend-react#1940]
### Description of the bug

The help text icon remains visible even when the help text is empty

### Steps To Reproduce

https://github.com/Altinn/altinn-studio/assets/24462611/2b58d9a0-e17c-4a3c-8e08-47179fe05939

**Comment by paal2707** [comment]
Tested and discussed. When it comes to help text text-resources with an empty value, it is not something we are going to check or do anything about.
