### ISSUE TITLE
Template for app frontend

### ISSUE THREAD

**Issue by nkylstad** [Altinn/app-frontend-react#195]
## Introduction
The app template is set up such that it is easy to use a custom app frontend instead of the standard one that we create. However, setting up a custom app frontend is not necessarily so easy. This would be much improved by setting up a template for a custom app frontend, with build, references to relevant libraries and documentation to get developers started.

## In scope

- Setting up a template for a custom react app frontend

## Out of scope

- Templates for other languages

## Product requirement
> Give an understanding of what should be designed, built, tested and released.

A ready-to-use template for a custom app frontend. 

## Design requirement
> UX and other requirements for the end result.

Lorem ipsum

## Technical/Engineering requirement
> How to build the feature technically, APIs to use/build, database storage etc?

Should be a fully functioning app, with build scripts set up. Need to decide how much of the base functionality of an app we should include here. 

## Dependencies
> Specify any dependencies by clicking "add dependency" below.
> NB! Dependencies can only be added and are only visible when the issue is viewed through Zenhub.

**Comment by haakemon** [comment]
Closing in favor of #200 which seems to be about the same topic, but with more details
