### ISSUE TITLE
Can not chose generated options from source

### ISSUE THREAD

**Issue by NathalieFroissart** [Altinn/app-frontend-react#1959]
### Description of the bug

I can not chose/click on the generated options from source datamodel 
link to repo: https://altinn.studio/repos/pat/endringsskjema/src/branch/master/App/ui/form/layouts/04_05_Lien.json

![image](https://github.com/Altinn/app-frontend-react/assets/39302088/c664e035-03b3-4132-a796-d79550fcbe0b)
![image](https://github.com/Altinn/app-frontend-react/assets/39302088/453ae8da-4c05-41da-a2be-5620cd2b2d61)

### Steps To Reproduce

1.choose "Patent" in radioButton
2.choose "Pant" in dropdown
3. write "20230058" in the Saksnummer field
4. click next button or use navigation button on top(4.Pant)
5. choose an option in rabiobutton
6. "FORTELL OSS HVEM SOM ER PANTSETTER" appears as checkboxes"
7. try to click on the checkbox---> Not possible
![image](https://github.com/Altinn/app-frontend-react/assets/39302088/c664e035-03b3-4132-a796-d79550fcbe0b)
![image](https://github.com/Altinn/app-frontend-react/assets/39302088/453ae8da-4c05-41da-a2be-5620cd2b2d61)

**Comment by olemartinorg** [comment]
I see you've linked your `value` property to `name`, which is the same property from the data model used to display the name. It would be better to use an ID or similar for the value, as right now you're trying to store multiple comma-separated strings in the data model that already contains commas(!). Storing value-strings that contains commas is not supported at the moment.

Relevant:
- #273

**Comment by NathalieFroissart** [comment]
Thank you for your answer. Do you mean that I should link my value to a text resource id instead of the name element from datamodel? If I understood you correctly this maybe won't help since I store a string with commas?
