### ISSUE TITLE
As a user I am confused by the loading message 

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#197]
## Description
User test show that some user take the text shown while the app is loading as an indication that the form is complex or hard to submit. 

Sidenote: In some cases where the app is of a sensitiv or particular serious nature it might be inappropriate with a humorous loading text.

We should consider changing this into a more generic text.

## Screenshot 
![Skjermbilde 2021-08-27 kl  09 33 19](https://user-images.githubusercontent.com/33222679/131090323-1d4b594f-f2a0-466f-89f9-cfa35648d095.png)

**Comment by FinnurO** [comment]
Should as flexible as  #171

**Comment by olemartinorg** [comment]
Diskusjon på Slack: https://altinndevops.slack.com/archives/C03L53RFPRU/p1668073309830899 (svar under, ikke i tråd)
Forslag til standardverdier:
1. Vent litt, vi henter X for deg (hvis vi et hva det er vi henter)
2. Vent litt, vi henter innholdet du trenger.
3. Vi henter innholdet du trenger.
4. En liten pause mens vi henter ting du trenger.
5. Bare vent litt, så får du det du trenger for å gå videre.
6. Vent litt, snart kommer det du trenger for å gå videre.
7. Vi henter det du trenger for å fortsette.

Ser ut til at valget har falt på nr 2 til nå. Enig i at at dette bør være fleksibelt, @FinnurO - men det kan være problematisk (overstyringer av språket er blant de tingene vi laster, så meldingen vil potensielt vises litt før vi har kommet så langt som å laste det ferdig).

**Comment by mrosvik** [comment]
Hva med å i første omgang endre den faste teksten? Det bør vel være ganske fort gjort? Så kan vi se om det dukker opp behov for å kunne tilpasse denne teksten til spesifikke tjenester? 

"Vent litt, vi starter opp tjenesten for deg" høres greit ut.

**Comment by bjosttveit** [comment]
> Vent litt, vi starter opp tjenesten for deg

Hva med på engelsk?

**Comment by olemartinorg** [comment]
Discussed on Daily: We should add documentation for this, with a page describing how the app starts(?) or a page describing standard texts in the app (if we don't have one already), where we also note that this text cannot be changed. We should partly do this for something to point to when people ask if they can override this text, and partly to have some documentation we can update at some point when it becomes possible to override the text.
