### ISSUE TITLE
Forhindre gjenbruk av innhold i dropdownliste på tvers av rader i repeterende tabell

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#1971]
### Description

I dropdownliste som brukes i repeterende tabell ønsker man ofte å sørge for at man ikke kan velge det samme fra dropdownlista flere ganger, på tvers av radene. Det er altså behov for en type filtrering av valgene i dropdownlista, eller en annen metode som forhindrer tilfeller som i bildet nedenfor: 

![image](https://github.com/Altinn/app-frontend-react/assets/43333852/3ed945e1-81d7-447e-bfd6-63e9146a9507)

Man kunne sett for seg en mer avansert knapp for "legg til rad", der trykk på denne knappen åpner dropdownlista og gir deg mulighet til å velge hvilken "kommune" man ønsker å legge til i lista. Da kan man slippe å filtrere vekk tidligere valg fra dropdown, men man må kunne gi en OK feilmelding dersom man forsøker å opprette duplikater.

**Comment by olemartinorg** [comment]
Relevant diskusjon:
- https://digdir.slack.com/archives/C0760NPT2BE/p1732269415134579

**Comment by olemartinorg** [comment]
- [x] Implement support for `optionFilter` as an expression on option-components
- [x] Implement `["value"]` expression function
- [ ] Implement support for `["value"]` in expression validation, as an alternative to `["argv", 0]`
- [ ] Output warnings/errors if a selected option is filtered away in the next run
- [ ] Docs for new expression functionality
- [ ] Detailed docs for `optionFilter` with good examples and gotchas
