### ISSUE TITLE
Group component missing title in the generated PDF

### ISSUE THREAD

**Issue by hanneline** [Altinn/app-frontend-react#1973]
### Description of the bug

The title shows up in the page when we run the app, but not in the generated PDF. 

![image](https://github.com/Altinn/app-frontend-react/assets/47357434/50b24729-ca89-4bdb-a43c-a62d97e71530)

![image](https://github.com/Altinn/app-frontend-react/assets/47357434/379c2a27-675f-430d-8c8a-ae8e4692657e)

### Steps To Reproduce

1. Add a Group component with title to an app
2. Add a Panel component, and add it to the Group component
3. Run the app
4. Check that the Group component shows on page with the title
5. Submit the data 
6. Check the generated PDF for the Group title

### Additional Information

```
      {
        "id": "H-01-Group-Virksomhet",
        "type": "Group",
        "textResourceBindings": {
          "title": "H-01-Group-Virksomhet.title"
        },
        "children": 
        [
          "H-01-Panel-Virksomhet"
        ] 
      },
      {
        "id": "H-01-Panel-Virksomhet",
        "type": "Panel",
        "textResourceBindings": {
          "title": "H-01-Panel-Virksomhet.title",
          "body": "H-01-Panel-Virksomhet.body"
        },
        "variant": "success",
        "showIcon": false
      },
```

**Comment by bjosttveit** [comment]
Slack thread: https://altinn.slack.com/archives/C02EJ9HKQA3/p1711097239720639

The problem seems to be in how the group component is handled in summary, likely the case where the `GroupComponent` is used with the prop `isSummary: true`
