### ISSUE TITLE
Mandatory asterisk showing up beneath text

### ISSUE THREAD

**Issue by magnusrf** [Altinn/app-frontend-react#1986]
### Description of the bug

![image](https://github.com/Altinn/app-frontend-react/assets/32111471/436d2d88-eecd-48b4-85c5-e7cbadd2f62e)
When using markdown syntax for formatting the title text such as "### Vedlegg" the mandatory * shows up underneath

### Steps To Reproduce

see file attachment component at https://pat.apps.tt02.altinn.no/pat/forundersokelse/

**Comment by olemartinorg** [comment]
Removing `good-first-issue` here. This is a long-standing issue we've had when headers are used in component titles. We recommend avoiding using headers here, thus following our default styling more closely. Also related:
- #393

**Comment by RonnyB71** [comment]
Lukker denne ref. anbefaling om ikke å benytte heading elementer i komponent titler og at evt. support for dette vil løses gjennom #393 og dermed er en duplikat.
