### ISSUE TITLE
Validation on maximum value fails in frontend

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/app-frontend-react#199]
## Describe the bug
This is in extension of Altinn/altinn-studio#4348, found after the fix. Validation on maximum value fails in frontend

## To Reproduce
1. Login to SBL and start an app instance of `ttd/apps-test`
2. Enter a number bigger the maximum value
3. Frontend saying maximum value is `7766279631452242000` but it accepts value until `7766279631452242432`

## Expected behavior
When the validation says maximum value is one, it should show errors on all values above that.

## Screenshots
Error:
![image](https://user-images.githubusercontent.com/49391725/97556755-28065280-19da-11eb-85b6-7ab999baab6c.png)
Accepting higher value:
![image](https://user-images.githubusercontent.com/49391725/97556813-3e141300-19da-11eb-89c8-5ce0ab3cba80.png)

## Additional info
Env: ttd/apps-test
Browser: Chrome 86
Env: At22

**Comment by nkylstad** [comment]
The restriction `totalDigits` no longer uses some arbitrary number with that number of digits, but a specific regex.
This bug is no longer relevant, closing.
