### ISSUE TITLE
Hjelpeknapp tekst, feil font

### ISSUE THREAD

**Issue by DanRJ** [Altinn/app-frontend-react#2002]
### Description of the bug

Hjelpeknapp tekst har font family Times New Roman selv om det står Inter i htmlen, jeg funderer på om Inter aldri blir lastet inn.
![image](https://github.com/Altinn/app-frontend-react/assets/3437949/1439b278-97c2-42bf-bce7-2b49a2258bc1)

### Steps To Reproduce

Åpne en hjelpeknapp og se på teksten, evt se bildet ovenfor

**Comment by olemartinorg** [comment]
Reprodusert lokalt, jeg får samme problem. Det ser ut til at designsystemet tvinger `inter`-fonten her, men i apps har vi ikke gått over til den fonten (enda). Dumt om font blir overstyrt fra designsystemet sin side.

Det kan også nevnes at denne feilen bør brukes som en anledning til å instruere Cypress til å klikke åpen en hjelpetekst i minst ett av skjermbildene som tas med Percy, slik at vi hadde fått et varsel om slike feil som dette (bør nok kombineres med et klikk på en lang/flerlinje-hjelpetekst, slik at vi får med hvordan det ser ut i samme slengen.

**Comment by Magnusrm** [comment]
Will get fixed by: https://github.com/Altinn/app-frontend-react/pull/2009

**Comment by olemartinorg** [comment]
Great! Does that mean that the issue I created in the design system (https://github.com/Altinn/altinn-design-system/issues/339) is no longer an issue there, then? Or are we overriding the font in app-frontend?

Remember the previous point about creating Percy tests for this as well. :pray:

**Comment by Magnusrm** [comment]
It seems it is no longer an issue 😊 Tested with the same app-frontend app version. And the new DS version fixes it.
I'll remember to add a percy test! 👍
