### ISSUE TITLE
maxCount på RepetatingGroup fungerer ikke i V4

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#2004]
### Description of the bug

I V3 fungerte maxCount på repeterende gruppe slik at "legg til ny rad" ble skjult når antall rader passerte maxCount satt på gruppa. I V4 skjer absolutt ingen ting når man passerer grensen på max rader satt i maxCount. 

### Steps To Reproduce

Opprett en RepeatingGroup med maxCount satt til 2, legg til 3 eller flere rader.

**Comment by olemartinorg** [comment]
Jeg tillater meg å legge til `good-first-issue` på denne, men den er kanskje hakket mer komplisert enn som så. Her ville jeg sett over koden, som ligger i `RepeatingGroupContainer.tsx` sin `AddButton`-komponent, og sett om problemet kan reproduseres. Vi må isåfall også få på plass en automatisk test (gjerne med Cypress) for å verifisere at dette fungerer (noe jeg forsåvidt trodde vi hadde allerede).

@rvessb Har du et eksempel på en app hvor dette ikke fungerer? Gjerne en som er enkel for oss å få opp og teste.

**Comment by rvessb** [comment]
@olemartinorg dere kan teste på RA-0574 som ligger på mitt repo (https://altinn.studio/repos/rvessb/ra0574-01). Her har jeg lagt maxverdi på tabellen (max 2 rader) på side 2 - Lisensfelling , du må svare "Ja" på spørsmålet for å få frem tabellen.

**Comment by HauklandJ** [comment]
@rvessb Hei, dette skjer fordi `edit.alwaysShowAddButton: true` overstyrer `maxCount`. Det vil fungere dersom denne settingen fjernes.


https://github.com/Altinn/app-frontend-react/assets/42615991/741c18fb-2419-4993-9b76-97b607607c65

@olemartinorg Er det slik oppførselen er tiltenkt, eller skal vi gjøre noe med dette?

**Comment by olemartinorg** [comment]
@HauklandJ Nice find! :raised_hands: No, that's not the intention - `maxCount` should still be effective regardless of that setting. The setting description gives a hint: `If set to true, the "Add" button will always be shown, even if the user is currently editing another row` (otherwise, the add button would only be visible when not in edit-mode).
