### ISSUE TITLE
RuleConfiguration does not work in v4

### ISSUE THREAD

**Issue by violaguttorm** [Altinn/app-frontend-react#2025]
### Description of the bug

In our app, we have a mix of RuleConfiguration and dynamic expressions for showing or hiding elements (due to dynamic expressions not existing when we began development on this app). However, after upgrading to v4 the elements affected by RuleConfiguration just simply do not show up any more, no matter if we swap "Hide" and "Show" on any given element. Even when using development tools to view hidden elements as greyed out, they do not show up. 

If I delete the RuleConfiguration file, all elements show up as expected (but obviously all are shown). 

Our app is https://altinn.studio/repos/brg/rrh-innrapportering (v4 branch is `379-migrer-til-v4`) , but it might be tricky to get up and running locally due to multiple calls against Brønnøysundregistrenes internal apps which an outside computer can't necessarily reach. 

### Steps To Reproduce

1. Write a rule in RuleConfiguration to show or hide an element, with a rule in RuleHandler.js
2. Observe it not showing up.

**Comment by RonnyB71** [comment]
Closing this as the ruleConfiguration file was missing from the deployment. Fixed by the Studio team and verified.
