### ISSUE TITLE
v4: Kan ikke velge underenhet

### ISSUE THREAD

**Issue by SimenRokaas** [Altinn/app-frontend-react#2033]
### Description of the bug

Hei, jeg har oppgradert skjema [elvirksomhet](https://altinn.studio/repos/dsb/elvirksomhet) til v8/v4. Skjemaet skal bare brukes av org-underenheter, eller overordnet enhet hvis ingen underenhet finnes. Konfig i `applicationmetadata.json`:
```
  "partyTypesAllowed": {
    "bankruptcyEstate": false,
    "organisation": true,
    "person": false,
    "subUnit": true
  },
```
Her er jeg logget inn som test-org-bruker 30874995556. Når jeg velger underenhet burde skjema initieres (ref [dok](https://docs.altinn.studio/community/changelog/app-frontend/v4/#most-users-will-be-prompted-for-party-each-time)) - men istedet bare kollapses valget.

https://github.com/Altinn/app-frontend-react/assets/5219898/3b23c7fb-df03-4202-9ae2-bfee776363e3

### Steps To Reproduce

1. Log in to tt02 as 30874995556
2. Go to https://dsb.apps.tt02.altinn.no/dsb/elvirksomhet
3. Try to select sub unit
4. Observe that it does not work - it is just collapsed

**Comment by SimenRokaas** [comment]
Hei @bjosttveit , hva er pri for denne? Feilen gjør at vi ikke kan deploye oppgradert versjon til TT02 for skjemaer som krever underenhet.

**Comment by olemartinorg** [comment]
Jeg la til `good-first-issue` på denne, med forbehold om at det bare gjelder selve klikkingen på elementet som oppfattes galt her.

**Comment by HauklandJ** [comment]
Not able to reproduse the issue:

https://github.com/Altinn/app-frontend-react/assets/42615991/3dcd7696-3be7-48f5-9956-5ab933030d4a

**Comment by HauklandJ** [comment]
Reprodusert.
