### ISSUE TITLE
Analysis: get rid of stringified form data in frontend? Produced JSON invalid against JSON-schema.

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#205]
## Description
When we fetch form data from our backend we stringify it and store it in redux. Why do we have to do this? Is there any reason for this implementation?

Take the following C# class:
```
public class Journalnummerdatadef33316{
[Range(1,Int32.MaxValue)]
    [XmlAttribute("orid")]
    [BindNever]
public decimal orid {get; set;} = 33316;
[Range(Int32.MinValue,Int32.MaxValue)]
    [XmlText()]
public decimal value { get; set; }
}
```

When fetched this is returned as a number:
```
"Journalnummer-datadef-33316":{"orid":33316,"value":200}
```

This is so stringified before we store this in our redux store see `flattenObject` in `databindings.ts`:
```js
      toReturn[i] = data[i].toString();
```

Which is in turn passed as a string when saving the data (we somehow tolerate type coercion on the backend when parsing the JSON to our C# model):

```
"Journalnummer-datadef-33316":{"orid":"33316","value":"2000"}
```

This does lead to a correct XML that validates against the XSD. BUT, this does leave an invalid JSON object (form data passed into the API) according to our JSON schema (numbers, for instance, are not strings, hehe). App frontend handles validating the stringified JSON (as type coercion is enabled in AJV). But this does seem unnecessary?

Why do we have to store stuff as strings? 

Related PR: https://github.com/Altinn/altinn-studio/pull/4432/files 

## In scope
- Any reason we should use stringified form data?
- How should we determine format when storing input from an input field 
  - fetch type from json schem and save accordingly?
  - defined at component level?

## Analysis

Lorem ipsum

## Conclusion
> Short summary of the proposed solution.

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by FinnurO** [comment]
Is #549 a duplicate @olemartinorg ?

**Comment by olemartinorg** [comment]
Completed in #1742
