### ISSUE TITLE
Issues with our main error message

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#206]
## Description
Both the header and the paragraph in the main error message are headers. The paragraph should be changed to a paragraph. I am unsure if a page can start with a h2  and then have it followed by a h1. Need to have an extra look at this.

Do we need some kind of error message around the submit button? For long formpages it might be weird to have the error message and button so far apart. Its also a lot of movement in the form when an error is introduced. I think it would be smart to have an extra look at the validation component.

## Screenshots
![Skjermbilde 2021-11-03 kl  15 26 34](https://user-images.githubusercontent.com/33222679/140079166-99a0fc66-91ed-46e5-beca-13c0cc744c01.png)

## Considerations
> Describe input (beyond tasks) on how the user story should be solved can be put here.

### Ops requirements
> Are there any requirements for monitoring? What is being built and what could go wrong? 
> Are there any requirements related to backup? 

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [ ] Is the header in the error message allowed
- [ ] Do we need to make bigger changes to our error message?

**Comment by olemartinorg** [comment]
This component is gone now, after #100 got implemented
