### ISSUE TITLE
There are two issues seen with `dat/innkvartering` app

### ISSUE THREAD

**Issue by nkylstad** [Altinn/app-frontend-react#208]
There are two issues seen with `dat/innkvartering` app 
1. with the steps described in the issue, when the focus is active on postal code and when one click on yes radio button, the value is registered but the value from the calculation is not updated.

2. Enter postal code -> tab -> click on yes radio button -> the radio button is selected after the slow calculation is complete. @nkylstad 

This bug on overwrite of values is not experienced anymore.

_Originally posted by @jeevananthank in https://github.com/Altinn/altinn-studio/issues/5754#issuecomment-815825970_

**Comment by FinnurO** [comment]
The app is no longer in use. Furthermore stale. Closing issue.
