### ISSUE TITLE
Verdi fra "editInTable" dropdownliste i "onlyTable" vises ikke i oppsummering

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#2099]
### Description of the bug

Dersom man setter en repeterende gruppe til `"onlyTable":True`, og denne inneholder en dropdownliste satt til `"editInTable":False`, vises ikke dropdownlisten i oppsummering.

![image](https://github.com/Altinn/app-frontend-react/assets/43333852/c8100897-dece-4969-bece-75965fb187bb)
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/1a70f431-7ec1-47d3-90fa-8940b66cdd4f)

### Steps To Reproduce

Se beskrivelse..
Oppsett av repeterende gruppe:
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/0b0f376c-367a-4777-b7d5-ecb7f2881cd2)

Gruppekomponent i summary:
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/ccb0e748-a57f-42d7-a410-398dc9b844b0)

**Comment by magnusrf** [comment]
Tidligere issue her: https://github.com/Altinn/app-frontend-react/issues/1703

**Comment by rvessb** [comment]
Ser det i #1703 er kommentert at det som løsning foreslås å settet feltet i tabellen til "utfyllbart men skrivebeskyttet". Ikke bare er dette lite brukervennlig, det vil ikke fungere i det hele tatt for dropplister:
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/7516adbc-4722-43c6-818d-e4f031848824)

**Comment by olemartinorg** [comment]
Lukker denne som duplikat av #1703, og setter heller `org/ssb` på den saken også.
