### ISSUE TITLE
Markdown for linjeskift fungerer ikke 

### ISSUE THREAD

**Issue by hanneline** [Altinn/app-frontend-react#2145]
### Description of the bug

Markdown for nytt avsnitt (dobbel linjeskift) "\n\n" lagt inn i tekst i tekstressursfil, ga ikke nytt avsnitt.

Denne teksten ble brukt i InstantiationValidator. Prøvde også i en hjelpetekst. Fungerte ikke der heller.

Byttet ut markdown med htmlkode for linjeskift, det fungerte. 

Det står i dokumentasjonen at "Alle tekster kan formateres med markdown".

### Steps To Reproduce

1. Legg inn "\n\n" inn i en tekst i ei tekstressursfil for å få linjeskift i teksten
2. Bruk teksten feks i en hjelpetekst (eller InstantiationValidator)
3. Kjør appen
4. Se hjelpeteksten (eller sørg for at teksten i InstatiationValidator blir brukt)
5. Teksten vises uten avsnitt
6. Bytt ut markdown med htmlkode for linjeskift
7. Se hjelpeteksten (eller sørg for at teksten i InstatiationValidator blir brukt)
8. Teksten vises med avsnitt

**Comment by RonnyB71** [comment]
Closing this as not reproducable for the description provided. Tested with 4.4.1 (currently latest stable version).

Both help text, paragraph and generalt text usage within a panel supports "\n\n" for providing a linebreak.
