### ISSUE TITLE
Support for multiple data models of same type (repeating data models)

### ISSUE THREAD

**Issue by HauklandJ** [Altinn/app-frontend-react#2146]
Part of the [Underskjema Epic](https://github.com/Altinn/app-frontend-react/issues/2137)

A [SubFormTable](https://github.com/Altinn/app-frontend-react/issues/2144) needs support for multiple data models of the same type.

**Comment by danielskovli** [comment]
I think this is no longer an issue, at least the sub-form table and creation of dataelements works as required.
