### ISSUE TITLE
Create new action type for 'continue in main form' button

### ISSUE THREAD

**Issue by HauklandJ** [Altinn/app-frontend-react#2152]
Part of the [Underskjema Epic](https://github.com/Altinn/app-frontend-react/issues/2137).

For sub forms, we need a button to "complete sub form and return to main form". The button may need to invoke a new type of action. In scope for this issue is 
- [x] Investigating whether an existing action may be applied
- [ ] If not, create a new action
- [ ] Deciding the button text (suggestions: english - "Add", Norwegian - "Legg til")
- [ ] Adding the button

**Comment by danielskovli** [comment]
I can investigate 🕵️

**Comment by danielskovli** [comment]
## Backend

As far as I can see in the app-lib-dotnet code, we're only ever using three types of `action` types:
Verbatim `reject` and `sign`, along with default action which indicates "whatever comes next according to `process.bpmn`.

Both the [ProcessController](https://github.com/Altinn/app-lib-dotnet/blob/1ac59d83211eae2d37ad8998cbc1c10c52c54632/src/Altinn.App.Api/Controllers/ProcessController.cs#L319) and subsequently [ProcessEngine](https://github.com/Altinn/app-lib-dotnet/blob/1ac59d83211eae2d37ad8998cbc1c10c52c54632/src/Altinn.App.Core/Internal/Process/ProcessEngine.cs#L372) implements `action` as a nullable `string`, which means there's no hard limit or guidance on what this value should be.

App developers can also hook in their own [action handlers](https://github.com/Altinn/app-lib-dotnet/blob/1ac59d83211eae2d37ad8998cbc1c10c52c54632/src/Altinn.App.Core/Internal/Process/ProcessEngine.cs#L157), but in this context these are only able to produce a success/fail result, not necessarily alter the navigation context.

At various other parts in the code, there are concepts of `read`, `write` and `confirm` action types. I see no direct mention of these in the navigation pipeline, but my findings here are not necessarily exhaustive.

**Comment by danielskovli** [comment]
It seems appropriate to leverage the existing [ActionButton](https://github.com/Altinn/app-frontend-react/blob/main/src/layout/ActionButton/ActionButtonComponent.tsx) component for this implementation.

In which case the extent of frontend changes is limited to minor config and language changes. The [ProcessNavigationContext -> doProcessNext](https://github.com/Altinn/app-frontend-react/blob/main/src/features/instance/ProcessNavigationContext.tsx#L28) already contains the hooks and logic required to send the new `action` to the backend. 

Note: Studio Designer would eventually require an update as well﻿
![bilde](https://github.com/Altinn/app-frontend-react/assets/21328986/04c64752-5724-42f4-82fa-e0b4faf680f4)

**Comment by danielskovli** [comment]
After investigating how the `RepeatingGroup` component works, and speaking with the frontend team, it's no longer so clear that this should be hooked in the `ActionButton`. Or rather, what we don't want to have happen is for the button to call the `process/next` endpoint. 

I believe we may want to tell the backend that we are closing out of sub form, which will provide an opportunity to run user hooks and perform some (meta)data storage. But the frontend essentially just wants to do an internal router navigation back to the "main form".

**Comment by danielskovli** [comment]
Note to self after discussing with Ole Martin: `CustomButton` might be the way to go.

**Comment by danielskovli** [comment]
New [CustomButton action type](https://github.com/Altinn/app-frontend-react/commit/e9e527c1aaa9d16d197a9abe7340d0e7eb9acef5#diff-6a33006b3579fa0600a56f746b3acef556548328cec1588e0cdda1fa8cb468e3R39-R44) looks promising.

[Navigates back to the main form, using the current main form page key](https://github.com/Altinn/app-frontend-react/commit/e9e527c1aaa9d16d197a9abe7340d0e7eb9acef5#diff-9bee3039265969862eb769672908cb7e227f5d48075e87852b5e769933f8509fR313-R320), and can be combined with other CustomButton actions as required (eg. serverside hooks and whatnot).
