### ISSUE TITLE
Page Hijacking for components

### ISSUE THREAD

**Issue by HauklandJ** [Altinn/app-frontend-react#2165]
Part of the [Underskjema Epic](https://github.com/Altinn/app-frontend-react/issues/2137)

Page Hijacking for components consists of asking marked components whether the URL navigated to is relevant for them.
A prerequisite for this is [expanding urls with component info](https://github.com/Altinn/app-frontend-react/issues/2153). 

![hijacking drawio](https://github.com/Altinn/app-frontend-react/assets/42615991/37736848-fd8e-41ee-acca-ba78c8609e96)

This is relevant for sub forms as when a subform is being filled out it should have its own view. The sub form should be rendered as its own form.

**Comment by danielskovli** [comment]
This has been implemented slightly differently than anticipated in the Router engine instead.
