### ISSUE TITLE
Summary view for Likert component (in group) shows option value instead of display value/label

### ISSUE THREAD

**Issue by nkylstad** [Altinn/app-frontend-react#217]
## Description
Bug from likert component implementation (#72)
Summary view  ([Summary](https://docs.altinn.studio/app/development/ux/pages/summary/)) for Likert is rendered, but the _value_ of the selected option is shown and not the _display value/label_. I believe we have implemented this for regular radio buttons (so that the label of the option is shown) making the summary view more readable. This should be the case for Likert as well.

## To Reproduce
1. Go to an app with likert component (w/group) and summary for likert component.
2. Select some values in likert component
3. See that summary component is updated with the selected values, but showing the stored value of the selected option rather than the display value/label.

## Expected behavior
Should render the display value (label) of the selected option rather than the stored value.

## Screenshots
![image](https://user-images.githubusercontent.com/1636323/172343585-5f0e37f4-1771-4454-9750-aa47050469e1.png)

## Additional info
Check out the SummaryComponent.tsx and see how this has been solved for f.ex. regular RadioButtons.
Tested in Chrome.

**Comment by nkylstad** [comment]
@lasseklovstad Somehow we completely missed another bug here, which is that the question text does not appear in the summary. `{0}` should be replaced by the relevant question text for the row, but it seems like variables in text is not working here. Could you take a look?

**Comment by lasseklovstad** [comment]
@nkylstad It takes some time for me to test this so I won't have time right now. But I have done some investigating and it looks like this line 118 in `SummaryComponent` should change the implementation to what `GenericComponent` is doing. As you can see the `selectComponentTexts` has a third param `tryNesting` which is key for the Likert component. 

SummaryComponent (118):
```
  const label = useAppSelector((state) => {
    const titleKey = formComponent.textResourceBindings?.title;
    if (titleKey) {
      return getTextFromAppOrDefault(
        titleKey,
        state.textResources.resources,
        state.language.language,
        [],
        false,
      );
    }
    return undefined;
  });
```

GenericComponent (128):
```
  const texts = useAppSelector((state) =>
    selectComponentTexts(
      state.textResources.resources,
      props.textResourceBindings,
      props.type === 'Likert',
    ),
  );
```

**Comment by lasseklovstad** [comment]
It is a bit confusing cause it is multiple implementations of getting texts from text resources. It should maybe be done a cleanup around this.

**Comment by JohanGuntherKrogevoll** [comment]
You probably know this and it will probably be fixed when you fix the summary-page but ill mention it anyway 😉 
The text is also missing in the validation-messages and pdf:
![image](https://user-images.githubusercontent.com/66003225/190587013-99953070-b175-4ff2-acab-306d7b7ad8e9.png)
![image](https://user-images.githubusercontent.com/66003225/190587115-2f855b25-f222-49df-9d97-c3598a755aa5.png)

**Comment by bjosttveit** [comment]
This still not working? In my app this has been working as expected for a while. Don't know when it was fixed though 🤷

**Comment by olemartinorg** [comment]
Agreeing with @bjosttveit! We even have cypress tests for this behaviour now. Closing as completed.
