### ISSUE TITLE
Font størresle for Paragraph

### ISSUE THREAD

**Issue by KatFjo** [Altinn/app-frontend-react#2172]
### Description of the bug

Når man bruker Markdown for å lage en liste i Paragraph komponenten endrer font størelsen seg for hele komponenten til å bli mindre enn vanlige Paragraph'er.

![Screenshot 2024-06-19 at 14 59 56](https://github.com/Altinn/app-frontend-react/assets/116546222/fb9876cf-0c53-4925-bec6-7352e9006bc1)

### Steps To Reproduce

Lag to Paragraph komponenter på en side.
Fyll den ene med en teskt som bare inneholder en setning.
Fyll den andre med teskt som inneholer markdown for liste: <ul/>.
Kjør appen og se støreleseforskjellen.

**Comment by bjosttveit** [comment]
Mener dette skal være løst av https://github.com/Altinn/app-frontend-react/pull/2302. Bare å gjenåpne issuet dersom det fortsatt er et problem.
