### ISSUE TITLE
PRIV & SELN not working in v4

### ISSUE THREAD

**Issue by SimenRokaas** [Altinn/app-frontend-react#2182]
### Description of the bug

Hei, vi har to skjemaer i TT02 som skal kunne startes av innlogget privatperson (PRIV) og av selvregistrert bruker (SELN): [brannaarsak](https://altinn.studio/repos/dsb/brannaarsak) (v3/v7) og [regulerte-yrker](https://altinn.studio/repos/dsb/regulerte-yrker) (v4/v8). Begge fungerer for PRIV, men for SELN fungerer det bare i brannaarsak. Jeg kan ikke se noen forskjell i policy.xml eller hvilke aktører som er tillatt i applicationmetadata.json (alle står til false => alle får lov). Hvorfor får vi da denne ved forsøk på innlogging med selvregistrert bruker i regulerte-yrker? Er det bug i v4/v8?

### Steps To Reproduce

1. Log into TT02 as SELN, start form brannaarsak (v3) - see that it works
2. Log into TT02 as SELN, start form regulerte-yrker (v4) - see that it does NOT work even if policy and allowed parties are the same as for brannaarsak

**Comment by olemartinorg** [comment]
Da er fiks på vei i #2336. Jeg la merke til at appene som er nevnt over har fått en workaround siden issuet ble opprettet, så de fungerte tilsynelatende fint. Det er bare når man begrenser `partyTypesAllowed` i `applicationmetadata.json` til f.eks. bare `person` at dette _ikke_ fungerte. Det skal altså nå være løst når feilrettingen blir merget og lansert ut i en versjon.
