### ISSUE TITLE
Turn off Cypress, CodeQL for draft pr workflows

### ISSUE THREAD

**Issue by HauklandJ** [Altinn/app-frontend-react#2215]
skru av kjøring av cypress og codeql for draft-pr, siden det er relativt dyrt for workerne og vi ser verdien av en oversiktlig diff på en arbeidsbranch der det committes gjevnlig

**Comment by danielskovli** [comment]
🫡

**Comment by danielskovli** [comment]
Etter [diskusjon på Slack](https://digdir.slack.com/archives/C076GU2QHCG/p1720512424113519?thread_ts=1720511203.632239&cid=C076GU2QHCG) så dropper vi denne.
