### ISSUE TITLE
Backend should return dataElements in timestamp order

### ISSUE THREAD

**Issue by danielskovli** [Altinn/app-frontend-react#2226]
`InstancesController.Get` returns an instance object containing a `data` property. This property is an array of objects, in seemingly random order.

To be fair, the order is consistent between reloads, but otherwise completely useless.

We wish for the order of this list to be based on the timestamp when the associated dataElement was created, in ascending order.

**Comment by danielskovli** [comment]
This has been implemented as a proposal in branch `feature/subform` for both [app-localtest](https://github.com/Altinn/app-localtest/commit/aabb6f5de9201ef6d7a4c4462b8fc84afda2b3ca) and [altinn-storage](https://github.com/Altinn/altinn-storage/commit/1a7909df1f532587a07f550edc7c7710e3d26ef0).

The functionality has been verified in `app-localtest`, but as always the testing in `altinn-storage` is a bit more elusive.

@SandGrainOne Do you see any immediate concerns with the approach taken by the two commits linked above? I can't imagine this resulting in a breaking change, since we're going from pseudo-random to ordered results, but I also don't have the whole perspective on situations like these.

As for unit testing in `altinn-storage`, I can't even get them to run so I haven't been able to do much validation there.

**Comment by SandGrainOne** [comment]
Running Storage and the integration tests require a pre configured PostgreSQL database. I can understand it's a bit of a hassle.

The change looks safe enough. Nothing I know of is sensitive to the order of data elements.

**Comment by HauklandJ** [comment]
> Running Storage and the integration tests require a pre configured PostgreSQL database. I can understand it's a bit of a hassle.

What needs to be configured? Does anything need to be populated in the DB for the tests to run? Is there a setup guide somewhere?

**Comment by SandGrainOne** [comment]
@HauklandJ Start with the readme: https://github.com/Altinn/altinn-storage/#setting-up-postgresql

The setup guide we have is for Events, but the pattern is identical. All use of `events` should be replaced with `storage`. E.g `eventsdb` becomes `storagedb` and so on.
