### ISSUE TITLE
"Open" property on accordion

### ISSUE THREAD

**Issue by caroliss** [Altinn/app-frontend-react#2238]
### Description

We would like a property on the accordion component that can be used to set the accordion open by default. This should be a boolean, and should also support dynamic expressions. 
This would be useful to show some info to the user from the beginning, and also to make it possible to add an "open all" functionality.

**Comment by danielskovli** [comment]
This can be implemented by passing a value to [Accordion.Item -> defaultOpen](https://storybook.designsystemet.no/?path=/docs/komponenter-accordion--docs#accordionitem).

Our implementation: [[Accordion](https://github.com/Altinn/app-frontend-react/blob/main/src/layout/Accordion/Accordion.tsx), [AccordtionItem](https://github.com/Altinn/app-frontend-react/blob/main/src/layout/Accordion/AccordionItem.tsx)].

**Comment by olemartinorg** [comment]
Adding to this, I think the AccordionGroup component could have an option to make sure only one of the children Accordion components are open at any point in time. I agree with the option for "open all", but that should not be possible to configure alongside a "only keep one accordion open simultaneously" option.
