### ISSUE TITLE
Browser back button do not apply to app pages

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#225]
### Description of the bug

When using an app with multiple pages you can not go back and forth with the browsers back/forward buttons. Im guessing this is because we are actually not actually loading in a new page. If the user press the back button they will be moved to the page they were before starting the app. Im guessing most people will expect going one page back when using that button.

Im not sure if this is directly a WCAG issue, but i'm guessing that having expected behavior on the browser button will be better for everyone. 

### Steps To Reproduce

1. Go to an app with multiple pages
2. Go to page two
3. Try the browser back button

### Additional Information

Tested with the "Oppstartsveileder" application 
On Mac with Chrome

**Comment by bjosttveit** [comment]
Fixed by https://github.com/Altinn/app-frontend-react/pull/1682
