### ISSUE TITLE
PDF showing hidden fields

### ISSUE THREAD

**Issue by adamhaeger** [Altinn/app-frontend-react#2310]
Recreate:

1. Configure a hidden field in your app.
2. Go to PDF rendering of the page containing the hidden field.

Expected:

The hidden field is not shown

Actual:

The hidden field is shown.

**Comment by Magnusrm** [comment]
Re-tested this issue and it seems to have been solved by using the `useIsHidden` in the ComponentSummary, which was introduced in https://github.com/Altinn/app-frontend-react/pull/2240/files#diff-354bc9cb3fff2b0e17da60b9017b0107a068b1dfa73c7f141d255a8e43463f83
