### ISSUE TITLE
Alternative datepicker

### ISSUE THREAD

**Issue by paal2707** [Altinn/app-frontend-react#2379]
### Description

As we use a deprecated version of material-UI and wish to get away from material-UI we should find alternative datepicker to handle datepicking in app-frontend. 

Alternative: https://daypicker.dev/ 

### Additional Information

Should correspond with change of moment - date/time tools (#191)

### Tasks

- [ ] Replace with new solution
- [ ] Correspond with design sketches
- [ ] Regression tests

### Acceptance Criterias

A viable alternative is identified and has replaced material-UI datepicker where used. Should cover all functionality that exists in the current solution.

**Comment by olemartinorg** [comment]
Accessibility regarding the datepicker was also recently discussed in #1886. Make sure those inputs are considered when implementing the new one. :pray:
