### ISSUE TITLE
Nested group components are not showing when deleting a previously added repeating group index. Stopped working in v.4.8

### ISSUE THREAD

**Issue by walldenfilippa** [Altinn/app-frontend-react#2421]
### Description of the bug

When adding two repeating group indexes (includes nested groups) and you delete the first added repeating group index, the nested group information in the second repeating group index will not show, unless you do a hard refresh. 

**What it looks like in the second repeating group index in the nested group after deleting the first repeating group index:**
![image](https://github.com/user-attachments/assets/dfb239cf-460e-47f3-a571-07bcc9aab79e)
**When adding a new index to the nested group:**
![image](https://github.com/user-attachments/assets/560e0039-0f31-45cb-b928-48c2557e98f2)
**After hard refresh:**
![image](https://github.com/user-attachments/assets/db72c6bf-0f09-4c34-811e-a69a2b42d292)

**Note** that this is only happening when deleting an earlier repeating group index. E.g. if you have index 1 and 2 and delete index 1. 
I tried different versions of frontend and noticed that this works fine in v.4.7.0, and stops working when using v.4.8 and above/including preview versions. 

### Steps To Reproduce

1. Add a repeating group with one or more nested repeating groups.
2. Add two indexes of the repeating group with information in the nested groups
3. Delete the first index.

**Comment by olemartinorg** [comment]
Confirmed to have been fixed in v4.8.2: https://digdir.slack.com/archives/C0760NPT2BE/p1726655063015979?thread_ts=1726214295.152349&cid=C0760NPT2BE
