### ISSUE TITLE
Data in list is "erased" when populated in DataProcessor in v4.8

### ISSUE THREAD

**Issue by tina-ahm** [Altinn/app-frontend-react#2432]
### Description of the bug

This bug may possibly be related to #2429 and #2421.

I have a list of strings that gets populated in the DataProcessor when a value in a RadioButtons component changes, however the data in the list seems to be removed after it is set in v4.8. I have tested the same application in v4.7 and I can see that the data does not change after it is set in the DataProcessor.

### Steps To Reproduce

1. Add a field in the data model of the type `List<string>`.
2. Populate said field in the ProcessDataWrite method of the DataProcessor.
3. In the "Network" tab in the browser inspector (as this field is not connected to any component), see the data in the field get removed after it gets set.

### Additional Information

When comparing v4.8 and 4.7 I can see that in v4.8 there are two PATCH requests made when the field that triggers the population of the list is changed (I have included the field `SF_OpplysningsSted` as this is also set at the same as `SF_BevillingTypeCodes`):
First request & response:
```
Request:
{
  "patch": [
    { "op": "test", "path": "/FlatData/BevillingsType", "value": null },
    { "op": "replace", "path": "/FlatData/BevillingsType", "value": "1" }
  ],
  "ignoredValidators": []
}

Response:
{
  "validationIssues": { "DataAnnotations": [] },
  "newDataModel": {
    "FlatData": {
      "SF_OpplysningsSted": "salgssted",
      "SF_BevillingTypeCodes": ["03SALG", "04SAIT", "15NETT"]
    }
  }
}
``` 
Second response & request:
```
Request:
{
  "patch": [
    {
      "op": "test",
      "path": "/FlatData/SF_BevillingTypeCodes",
      "value": ["03SALG", "04SAIT", "15NETT"]
    },
    { "op": "remove", "path": "/FlatData/SF_BevillingTypeCodes/2" },
    { "op": "remove", "path": "/FlatData/SF_BevillingTypeCodes/1" },
    { "op": "remove", "path": "/FlatData/SF_BevillingTypeCodes/0" }
  ],
  "ignoredValidators": []
}

Response:
{
  "validationIssues": { "DataAnnotations": [] },
  "newDataModel": {
    "FlatData": {
      "SF_OpplysningsSted": "salgssted",
      "SF_BevillingTypeCodes": []
    }
  }
}
```

**Comment by olemartinorg** [comment]
Confirmed to have been fixed in v4.8.2: https://digdir.slack.com/archives/C0760NPT2BE/p1726658729761009?thread_ts=1726214295.152349&cid=C0760NPT2BE
