### ISSUE TITLE
Value from dropdown is not shown on summary page when dropdown shows values from a repeating group.

### ISSUE THREAD

**Issue by RogerKjaernsrod** [Altinn/app-frontend-react#245]
### Description of the bug

A dropdown is showning values from a repeating group in the app like this:
![image](https://user-images.githubusercontent.com/47383888/174057342-05015f25-481f-4a18-885f-7ce1dc068434.png)

Then the selected value is not displayed on the summary page:
![image](https://user-images.githubusercontent.com/47383888/174057943-e3f0e9af-fffd-4cb2-af90-9e78996f832b.png)

The case above is when dropdown is used in a repeating group.

The issue is also present when dropdown is not in a repeating group:
![image](https://user-images.githubusercontent.com/47383888/174060206-630d2269-0419-4e1f-81dd-06fb563b08d7.png)

Summary page:
![image](https://user-images.githubusercontent.com/47383888/174060260-e8c47cfe-0ddd-4fc1-9144-2c248788848b.png)

The summary page should show the same as the dropdown component.

The images are from the mt-3 app:
https://altinn.studio/repos/oko/mt-3.git

### Steps To Reproduce

Create app with a dropdown that is displaying values from a repeating group in the app.
Add dropdown on summary page.
The values is not showing.

**Comment by RogerKjaernsrod** [comment]
@lorang92 Det virker som forventet.

**Comment by lorang92** [comment]
Perfekt. Da lukker jeg denne som løst.
