### ISSUE TITLE
TAB navigating through Dropdown component places the "focus" on weird places

### ISSUE THREAD

**Issue by violaguttorm** [Altinn/app-frontend-react#2486]
### Description of the bug

In our app, we use up to three Dropdowns for selecting a country in a Repeating Group, one in the Repeating Group itself, two within Nested Repeating Groups within it. When tabbing through these and selecting a value for a Dropdown specifically, it behaves weirdly, especially the two in the Nested Repeating Groups (which seem to trigger TAB-navigation as if they were the one in the outer Repeating Group). 

If this description is unhelpful or confusing, see steps. 

The source code is in this app: https://altinn.studio/repos/brg/rrh-innrapportering
URL in TT02: https://brg.apps.tt02.altinn.no/brg/rrh-innrapportering/

### Steps To Reproduce

1. Open the app.
2. Login with foedselsnummer: 01812649198
3. Select organization ALLSLAGS ORIENTAL TIGER AS (311780352)
4. Select that the organization "Har reelle rettighetshavere".
5. Select "No" on "Har fødselsnummer/D-nummer".
6. Use TAB to navigate to "Bostedsland", select a country from the list using the keyboard only. 
7. Press enter.
8. Observe that the tab disappears, and if you press TAB now, you are at the very top of the document.
9. Fill out "Statsborgerskap" with any value. 
10. TAB back to "Bostedsland" (or TAB there from the top). Fill out any value and press enter. 
11. Observe that the TAB navigation now takes you to Statsborgerskap as expected. 
12. Select "Ja" on "Har posisjon eierskap", select 25.01%, select "Indirekte" on grunnlag.
13. Select "Ja" on "Er utenlandsk virksomhet?"
14. TAB to Land, select any value. 
15. Observe that you're now placed in Statsborgerskap above (this also happens with mouse navigation, the form jumps up to focus on Statsborgerskap). 
16. Select "Ja" on "Har posisjon kontroll...?", select 50%, select "Indirekte" on grunnlag. 
17. Do steps 13-15 here. 
18. Observe the same odd behavior.

**Comment by Magnusrm** [comment]
Might be related to: #1039

**Comment by Magnusrm** [comment]
@violaguttorm We have relased a fix that we think will solve this issue in the version `v4.9.0-preview.3`. Do you think it would be possible for you to test if the issue has been solved to verify the fix?

**Comment by violaguttorm** [comment]
@Magnusrm Did a test locally on version `4.9.0-preview.3`. Looks like it works now, thank you! 😄
