### ISSUE TITLE
Likert - WCAG Brudd - 4.1.2 Namn,rolle, verdi (Nivå A)

### ISSUE THREAD

**Issue by olavflar** [Altinn/app-frontend-react#2508]
### Description of the bug

![Image](https://github.com/user-attachments/assets/cfd96733-953b-4edd-a11d-65fa0212ef9b)
![Image](https://github.com/user-attachments/assets/c73e2064-a7a0-43be-9e03-5ad012fb53a9)

Notat;
Oppdatere tilgjengelighetserklæring;
Likert komponenten fungerer ikke med skjermleseren JAWS. Vi har startet arbeidet med å se på hva som foresaker feilen og vil rette dette så fort vi har funnet feilen. (Hentet fra Tilgjengelighetserklæring til Altinn) https://uustatus.no/nb/erklaringer/publisert/950eb7c8-1317-46c0-b6e4-eba359ac2f9e

### Steps To Reproduce

Test ned JAWS eller ARC toolkit

**Comment by Magnusrm** [comment]
Tested this, and the issue has been resolved 🥳
