### ISSUE TITLE
Display of checkbox value on summarypage is wrong when the checkbox is in the outer group of a "group in group" setup.

### ISSUE THREAD

**Issue by RogerKjaernsrod** [Altinn/app-frontend-react#257]
### Description of the bug

Display of checkbox value on summarypage is wrong when the checkbox is in the outer group of a "group in group" setup.
When you add the group that contains another group to the summary page like this:
{
  "id": "SummaryComp1",
  "type": "Summary",
  "componentRef": "MainGroup1",
  "pageRef": "7_objekt",
  **"largeGroup": true**
}
and the outer group ("MainGroup1" here) contans a checkbox component, the value is displayed like this:
![image](https://user-images.githubusercontent.com/47383888/174006846-46c08444-06f7-4265-aefa-c77fadd8f3d4.png)
It is displayed like this on the "filling out" page:
![image](https://user-images.githubusercontent.com/47383888/174006960-34ae20f4-9bcc-42da-b799-94e635a0f545.png)

The bug can be seen on the Økokrim app mt-3:
https://oko.apps.tt02.altinn.no/oko/mt-3/

### Steps To Reproduce

Create an app that has a checkbox in the outer group of a group in group setup.
Add the checkbox on the summary page.

**Comment by olemartinorg** [comment]
@RogerKjaernsrod The fix for this should now have landed in the latest frontend version (v3.44.3 and later), could you test it to make sure it works? Let me know it anything unexpected happens, or close the issue. Thank you! 😊

**Comment by RogerKjaernsrod** [comment]
It works.
