### ISSUE TITLE
Support for binding an attachment control to a repeating element in the data model

### ISSUE THREAD

**Issue by RogerKjaernsrod** [Altinn/app-frontend-react#259]
In the App MT-3 (Økokrim) Altinn/apps-backlog#5 there is a need for the possibility of binding attachments to a repeating element in the data model. Økokrim would like to have the user add extra information about each attachment. Like this:
![image](https://user-images.githubusercontent.com/47383888/145976867-acd029b3-6fc6-46da-a198-95a369945db6.png)

## What needs to be solved?
A change of the attachment control to support binding it to an element in a repeating group in the datamodel would solve this.

## How do you want it solved?
Adding the option of binding an Attachment control to an element in the datamodel. Should support both repeating and single instance elements.

## Additional context
Currently the App crashes if you add an attachment control to a repeating group in the designer.
It does not crash designtime. It crashes when you open the App an click the "Add new" link to add a new row to the repeating group.

#### Reference to the data element from group element

In this scenario, the data model for the form would need a list of strings connected to the group element. 
In this way, each element in the group will have a reference to the connected data element. 

#### Reference from dataelement to group element

In this scenario, each element would need a reference to the correct group and element

The hypothesis is that option 1 is best.

### Are there a need for multiple types of documents related 

If there is a need for more than one type of attachment for one group?  

Currently, if there is a need for that that would require multiple file uploads per row in the group

**Comment by olemartinorg** [comment]
This should now be solved, and I'm assuming the testing on your end was successful, @RogerKjaernsrod. If not, let me know!
