### ISSUE TITLE
Use new endpoint for POST when saving attachments

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-frontend-react#2596]
### Description

In https://github.com/Altinn/app-lib-dotnet/issues/850, we add a new endpoint for POST, so that service owners can write code that modifies instance data (mutate form data or add/remove elements) when attachments gets uploaded.

Frontend needs to use the new endpoint and update its internal state when the backend version is new enough (likely 8.5.0 (not preview), we will see)

**Comment by olemartinorg** [comment]
Assigning myself for testing.
