### ISSUE TITLE
Mapping two form inputs to the same model field breaks custom validation

### ISSUE THREAD

**Issue by torbjokv** [Altinn/app-frontend-react#261]
## Describe the bug

We have a form where we would like two variants of a form by using dynamics. The two forms elements uses the same model field, but at different places/order in the layout. This works fine until you add custom validation.

## To Reproduce
1. Get example repo https://altinn.studio/repos/t_kvaale/hidden-validation-bug and run it
2. Select variant B
3. Fill the two text boxes
4. Send
5. Observe that validation fails, but error is not attached the form input as it should
6. Select variant A and observe that the error message is attached to the wrong input box

## Expected behavior
Expected validation message to show for only visible elements or all matching.

## Screenshots
![image](https://user-images.githubusercontent.com/554713/122040212-d4fdd600-cdd7-11eb-9f46-c7f041a0e666.png)
![image](https://user-images.githubusercontent.com/554713/122040332-f52d9500-cdd7-11eb-8003-d6ecfc633659.png)

## Additional info
> Add any other relevant context info about the problem here.
> For example OS (Windows, MacOS, iOS), browser (Chrome, Firefox, Safari), device (iPhone, laptop), screen-size, etc.
* Test with https://github.com/Altinn/app-frontend-react/issues/726 to see if this fixes the issue

**Comment by bjosttveit** [comment]
Fixed by #1281 
Server validations are now mapped to all components with a matching datamodelBinding, and hidden components are filtered out first.
