### ISSUE TITLE
Frontend rules are not supported for repeating groups

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#263]
## Describe the bug
Frontend rules are not supported for repeating groups. 
This can however be solved with backend calculations.

## To Reproduce
1. Go to an app with a repeating group
2. Try adding a rule targeting rep group
3. See that this is not possible.

## Expected behavior
This should work as expected. See implementation for dynamics.

**Comment by olemartinorg** [comment]
Mulig løst via #355 (ny dynamikk via uttrykk, som har støtte for rep.grupper). Denne dynamikken har støtte for vis/skjul, men den har fortsatt ikke støtte for kalkuleringer (men det er planlagt støttet).

**Comment by FinnurO** [comment]
Lukker fordi kalkulering er eget issue. #646
