### ISSUE TITLE
Textarea utvidelse

### ISSUE THREAD

**Issue by KatFjo** [Altinn/app-frontend-react#2658]
### Description of the bug

Når man utvider Textarea boksen så den blir større utvider ikke resten av skjema seg med den. Det fører til at den dekker til tekst og andre komponenter under seg.

![Image](https://github.com/user-attachments/assets/b53194a8-03a2-4670-95c6-b582d442e67b)

![Image](https://github.com/user-attachments/assets/023f5d8a-a9d6-4aa9-bffd-e032477eefa7)

### Steps To Reproduce

Lag et skjema med Textarea og andre felt undet den.

Prøv å utvid input boksen til Textarea.

**Comment by olemartinorg** [comment]
Bekreftet at dette ikke skjer på samme måte [i designsystemet](https://next.storybook.designsystemet.no/?path=/docs/komponenter-textarea--docs), så da bør vi undersøke videre i app-frontend. Takk for feilrapporten! 🙏

**Comment by olemartinorg** [comment]
Ser nå at dette er en duplikat av #2502, så lukker denne.
