### ISSUE TITLE
Party selection is not shown even though the user wants to see party list with every instantiation

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/app-frontend-react#268]
## Describe the bug
Party selection is not shown eventhough the user wants to see party list with every instantiation

## To Reproduce
1. Login to AT21 and navigate to profile and uncheck the checkbox 'Jeg ønsker ikke å bli spurt om aktør hver gang jeg starter utfylling av et nytt skjema' under Advanced settings
2. Start a deployed app that can be started by a person, organisation
3. The party selection page is not shown to select a different actor 

## Expected behavior
- [ ] The party selection should be shown with every instantiation (since in profile advanced settings, it is set that user will be asked to choose party with every instantiation). 
- [ ] If the user doesn't have multiple parties to represent the party selection should not be shown.
- [ ] This fix should only apply when creating a new instance, not when opening an existing instance.

## Additional info
Browser: Chrome 76
App: partydisplaytest
Env: AT21

**Comment by olemartinorg** [comment]
Closing these duplicates:
- https://github.com/Altinn/altinn-studio/issues/9363
- https://github.com/Altinn/altinn-studio/issues/7901

Be sure to look into these two when implementing this, as there might be additional info/requirements in duplicate issues.

**Comment by bjosttveit** [comment]
Relevant slack thread: https://altinndevops.slack.com/archives/C045EB3JA9X/p1683111081853389

**Comment by RonnyB71** [comment]
Snapshot of settings from the profile:
![image](https://user-images.githubusercontent.com/5430430/235936589-0997dcf9-10e2-49fb-920e-421800f88c30.png)

**Comment by elenagustafsson** [comment]
Hei! Dette er fortsatt et problem for vår app RF-1551. Saken jeg opprettet på det opprinnelig ble lukket som duplikat, og denne er lukket også - noe jeg ikke var klar over - uten at problemet er løst. Vi får en del brukerhenvendelser på dette her, da appen er i produksjon

**Comment by bjosttveit** [comment]
Hei, dette har blitt fikset, men er ikke aktivert som standard enda siden denne innstillingen ikke har vært respektert til nå i Altinn 3, og ville dermed påvirket alle apper i produksjon. Det kommer til å bli standard i neste major versjon av app-frontend (versjon 4). Men det går an å aktivere nå for en enkelt app ved å legge til følgende script i `Index.cshtml` til appen:
```html
<script>
window.featureToggles = window.featureToggles || {};
window.featureToggles['doNotPromptForPartyPreference'] = true;
</script>
```

**Comment by elenagustafsson** [comment]
Da har vi testet denne @bjosttveit Det er delvis fikset, men en del småbugs i det. RF-1551 tillater kun orgnr, da bør ikke fnr vises i den lista av avgivere man skal velge blant. Nå vises alle avgivere, og om jeg velger fnr så får jeg beskjed at jeg mangler rettigheter, noe som er feil, det er jo fordi skjema ikke skal kunne åpnes av fnr. I Altinn 2 i den boksen med Start opp tjeneste så vises det kun fnr hvis skjema er kun for dem, og orgnr hvis skjema bare kan startes av orgnr.
Og fnr i lista vises med org ved siden av og ikone for organisasjon, det er noe jeg har klaget på før i en annen sak 
![image](https://github.com/Altinn/app-frontend-react/assets/80962333/3f7551fa-88d6-495c-b9ae-9aca4a3209c8)
![image](https://github.com/Altinn/app-frontend-react/assets/80962333/edff9c6c-302f-4a18-90f1-133af700ce93)
