### ISSUE TITLE
Adding a "validation" trigger on a group component ignores "component"-specific validaitons

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#269]
## Describe the bug
Setting the `validate` flag in `triggers` on a group will run data model/required validations but seems to ignore component-specific (defined in formlayout) validations.

## To Reproduce
1. Add a group with a date picker component
2. Add a max date for the component
3. Use the keyboard to fill out a date later than  max
5. Save the group 
6. See that group saves

## Expected behavior
User should be prevented from saving when saving and `validateFormComponentsForLayout` should validate correctly.

**Comment by bjosttveit** [comment]
Not relevant anymore, focusing on #600 instead.
