### ISSUE TITLE
Misleading standard text in our error message

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#270]
## Description
Our standard text for generic error message are misleading. 

> Skjemaet inneholder feil eller mangler som hindrer oss fra _å sende det inn_. Når du har rettet feilene, kan du sende inn skjemaet på nytt.

The text gives the impression that the user is about to send in the form, while they might be trying to go to the next page. We need to replace the text with a more generic text. 

## To Reproduce
1. Go to an application with multiple pages and validation 
2. try to go to the next page with errors on the page
3. See error -->

## Expected behavior
The validation text should not confuse the user, but give them guidance to how they can proceed. 

Proposed text:

## Screenshots
![image (12)](https://user-images.githubusercontent.com/33222679/148223851-36544db7-98e1-4cd5-bf60-fbe5e2bf8f8c.png)
## Tasks

- [ ] Create a new generic text

**Comment by olemartinorg** [comment]
This text no longer exists, as #100 stopped using it and #475 removed it entirely. :partying_face:
