### ISSUE TITLE
Users can paste data into readOnly Input fields

### ISSUE THREAD

**Issue by tina-ahm** [Altinn/app-frontend-react#2772]
### Description of the bug

In Input fields that are readOnly and have the formatting property set, it is possible to paste in data which will change the previous data in the field. The expected behaviour is that it should not be possible to paste in any data.

### Steps To Reproduce

1. Add an Input field to the form with the following properties:
```json
"readOnly": true,
 "formatting": {
    "number": {
      "suffix": " kr"
   }
```
2. Copy some numbers (for this case) and paste it into the field.
3. See the previous data replaced by the pasted data.

### Additional Information

Here is a video showing the bug:
https://github.com/user-attachments/assets/d85a327f-fd08-4d40-bbf2-437387dbcc74

**Comment by olemartinorg** [comment]
@adamhaeger 
I would assume this is the case for other inputs as well? For instance:
- `Address`
- `Datepicker`
- `TextArea`

**Comment by olemartinorg** [comment]
Seems like my point above is moot, none of the components above have number formatting.
