### ISSUE TITLE
Double and/or swapped error messages when custom and frontend model validation interact

### ISSUE THREAD

**Issue by torbjokv** [Altinn/app-frontend-react#279]
## Describe the bug

Two similar but different cases when doing validation with simple type restrictions in XSD.

### Case 1:
1. Go to https://dat.apps.tt02.altinn.no/dat/innkvartering
2. Enter more then 50 characters in bygningsnummer and set focus outside
3. See correct error message for a while
4. See it translates to english when server side validation trigger returns

Expected behavior: It should keep Norwegian error message

![image](https://user-images.githubusercontent.com/554713/121344678-54952c00-c924-11eb-9360-3a77dc36e9e0.png)
![image](https://user-images.githubusercontent.com/554713/121344692-56f78600-c924-11eb-81cc-60909792b76a.png)

### Case 2:
1. Go to https://dat.apps.tt02.altinn.no/dat/innkvartering
2. Enter more then 50 characters in bygningsnummer and set focus outside
3. Fill all other required fields and post
4. Post form
5. Observe weird empty grey box under the correct error message

Expected behavior: No grey box

![image](https://user-images.githubusercontent.com/554713/121344714-5bbc3a00-c924-11eb-953b-b1a8fd6c1d72.png)

**Comment by olemartinorg** [comment]
@bjosttveit Is this among the problems we've recently fixed?

**Comment by bjosttveit** [comment]
This should not be an issue anymore. Besides, this issue (and app) is so old now that it is hard to even reproduce what happened here.
