### ISSUE TITLE
FE-komponenter: Mulighet for dynamiske uttrykk i "readOnly"-property'en

### ISSUE THREAD

**Issue by Hedda-ro** [Altinn/app-frontend-react#2798]
### Description of the bug

Hei! 

Vi har en Dropdown-komponent som bør være 'preselected' og 'readOnly' for nesten alle organisasjonsformer som bruker applikasjonen (er bare en organisasjonsform skal få lov til å endre verdi). 

Foreløpig fungerer ikke dette ved å legge inn et dynamisk uttrykk i 'readOnly' - som illustrert her:

![Image](https://github.com/user-attachments/assets/1c10ecb8-dd09-4f0c-bb0e-6c4d14f4d5e7)

Uttrykket funker heller ikke ved å fjerne datamodell-ID'en som her vises som tredje parameter (vi er i underskjema og bruker datamodell for hovedskjema i dette tilfellet). 

Både BE og FE her har de nyeste versjonene (8.5.0-rc9 og 4.10.0).

### Steps To Reproduce

Lenke: https://altinn.studio/repos/brg/aarsregnskap-bank-202404.git

Layout-side: ui/underskjema/layouts/01aarsregnskap.json -> linje 76.

**Comment by adamhaeger** [comment]
@Hedda-ro Ser ut som dette var en konfigurasjonsfeil som nå er løst?

Ser configen nå ser slik ut:

```
      {
        "id": "U-01-Dropdown-Valuta",
        "type": "Dropdown",
        "dataModelBindings": {
          "simpleBinding": "Rapport-RR0003U.regnskapsoppsett.valuta.value"
        },
        "required": true,
        "readOnly": ["notEquals", ["dataModel", "Innsender.enhet.organisasjonsform"], "NUF"],
        "preselectedOptionIndex": 0,
        "textResourceBindings": {
          "title": "U-01-Dropdown-Valuta.title",
          "requiredValidation": "U-01-Dropdown-Valuta.requiredValidation"
        },
        "optionsId": "valuta"
      },
```

I appen ser det riktig ut når jeg sender inn for et AS:

![Image](https://github.com/user-attachments/assets/93991280-a88a-4fa8-bb30-4eb2dd7c4c44)

Ser ut til at strengen "3228-50150" var feilen?

**Comment by Hedda-ro** [comment]
Hei! 

Takk for rask oppfølging her. 

Det stemmer at AS skal ikke ha mulighet til å endre dette Valuta-feltet, det er helt korrekt slik som du legger det frem. Derimot - når du sender inn for et NUF, så skal du ha mulighet til å endre verdi for Valuta (skal ikke være read-only). Får ikke denne dynamikken til å fungere ved å fjerne strengen "3228-50150" (datamodell-ID for hovedskjema) her. Beklager uklar formulering fra min side.

**Comment by bjosttveit** [comment]
1. Det er nødvendig å ha med referansen til dataTypen i uttrykket (`"3228-50150"`) som var der opprinnelig.
2. Tok en titt på datamodellen og det ser ut som du bare mangler en `.value` på slutten av stien.

Dette skal funke: `["notEquals", ["dataModel", "Innsender.enhet.organisasjonsform.value", "3228-50150"], "NUF"]`

**Comment by Hedda-ro** [comment]
Det funker nå, det stemmer! Tusen takk. Beklagelig med den glippen av ".value" vist ovenfor
