### ISSUE TITLE
Group component should be configurable with minOccurs in app-frontend

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#285]
## Description
Currently the group component in app-frontend is configurable with `maxCount` which is connected to the `maxOccurs `prop in the `.xsd `model. We should have a similar configuration for `minOccurs`

```
{
  "id": "demo-gruppe",
  "type": "Group",
  "children": [ ... ],
  "maxCount": 3,
  "dataModelBindings": { ... }
}
```
## Acceptance criteria
- Design for minOccur error 
- Validation is implemented in app-frontend
- Designer adds minOccurs when connecting group to datamodel

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
> Add tasks here

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by RonnyB71** [comment]
Closing, duplicate of https://github.com/Altinn/app-frontend-react/issues/1098
