### ISSUE TITLE
Implement support for copying an instance from old in app frontend

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/app-frontend-react#286]
## Description

The workflow should be that triggering copy in SBL should send a request to app frontend. That again builds the request to app backend and renders the newly created instance. 

## Considerations
> Describe input (beyond tasks) on how the user story should be solved can be put here.

### Ops requirements
> Are there any requirements for monitoring? What is being built and what could go wrong? 
> Are there any requirements related to backup? 

## Acceptance criteria
- [ ] Frontend respons to an endpoint that triggers creation of a new instance based on an old

## Specification tasks

- [ ] Development tasks are defined

## Development tasks
> Add tasks here

## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by FinnurO** [comment]
Digital gravferdsmelding

**Comment by olemartinorg** [comment]
Relevant:
- https://www.altinn.no/hjelp/innboks/arkiv/
- https://github.com/Altinn/altinn-roadmap/issues/67
- https://github.com/Altinn/altinn-studio/issues/1566

**Comment by annerisbakk** [comment]
Tatt ut av gr.leggende funksj. Følges opp i App

**Comment by RonnyB71** [comment]
Closing, solved by https://github.com/Altinn/altinn-platform/issues/355
