### ISSUE TITLE
Design signing view

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-frontend-react#291]
## Description

We need to design the signing view 

## Screenshots
> Screenshots or links to Figma (make sure your sketch is public)

## Considerations

- It should be possible to look at PDF for the forms that are signed
- It should be possible to open documents attached
- It should be possible to configure the service so that user can select what kind of documents. The view need to support "checkboxes" to select which part that is signed
- SKD want to be able to sign on field level. Is it possible to imagine a view supporting that?

## Acceptance criteria

- A view is designed
- It contains links to PDF and attachments
- It support that it can enable user selection
- It supports that some elements is forzed to sign

## Specification tasks

- [ ] Design the view

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] View is designed

**Comment by olemartinorg** [comment]
Related to?
- #175

**Comment by Annikenkbrathen** [comment]
This is the issue that is updated. This include signing view for PDF 
https://github.com/Altinn/altinn-studio/issues/8944 t

**Comment by olemartinorg** [comment]
Closing this one, then.
