### ISSUE TITLE
Sufix på inputfelt i repeterende tabell gir feil tall ved endring av verdien

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#294]
### Description of the bug

Hvis man har satt opp et inputfelt til å ha sufix i formatet " 000 kr", og man setter opp tusenskilletegn til å være en space så blir tallet feil hvis man endre tallet etter første input. feks man taster 1 noe som da viser 1 000 kr i feltet, man markere  bare 1 tallet da man vil endre dette til 2 for eksempel, da endres tallet til 2 000 000 kr, det ser u tat dette skjer pga spacen først i sufixen. Endres denne til "000 kr" så funker det som det skal, men formateringen blir da feil. Feilen er oppdaget i en repeterende tabell men kan god være den er ellers og.

### Steps To Reproduce

Opprett et input felt i en repeterende gruppe:
```
{
        "id": "Side2-Spm2c3-7c2c337c-7644-4621-b98d-0d9a3a3679d8",
        "type": "Input",
        "textResourceBindings": {
          "title": "lang.s2.tittel.tjenesterkjopt"
        },
        "dataModelBindings": {
          "simpleBinding": "SkjemaData.repMiljovernOmr.miljoOmrTjenesterKjopt"
        },
        "required": true,
        "readOnly": false,
        "grid": {
          "xs": 12,
          "innerGrid": {
            "xs": 4
          }
        },
        "formatting": {
          "number": {
            "suffix": " 000 kr",
            "thousandSeparator": " "
          },
          "align": "right"
        }
      }
```
kjør skjema og åpne en rad i den repeterende gruppa:
![image](https://user-images.githubusercontent.com/91887041/175478618-c700ccdb-3b02-4e23-af38-58695f100252.png)
skriv inn feks 5:
![image](https://user-images.githubusercontent.com/91887041/175478735-f6c88589-7c11-49a2-b488-56ff2db26a7d.png)

Marker 5 og endre til 6:
![image](https://user-images.githubusercontent.com/91887041/175478829-ced68349-0da6-478f-92b3-d91be5752e44.png)
![image](https://user-images.githubusercontent.com/91887041/175478870-0079f90f-f0d2-4b21-97ad-4c0f270e1600.png)

**Comment by olemartinorg** [comment]
I suspect this has been fixed now, as a side-effect of #328? I'm unable to reproduce it myself (although I'm testing outside of a repeating group, in a field only using space as a thousands-separator). We should probably investigate and add a cypress test for this, if possible.

**Comment by StianVestli** [comment]
Jeg testa hos meg nå og har fortsatt samme oppførsel i feltet i den repeterende gruppa. Hvis det var fiksa så skulle det vel rette seg sjølv siden det ligger i frontend?

**Comment by olemartinorg** [comment]
Ok, beklager støy! :blush: Det har nylig skjedd en del endringer rundt tallformatering, så jeg tenkte det var sannsynlig at dette ble fikset som en konsekvens av det. Helt riktig at det skulle ha rettet seg selv siden dette skjer i frontend. Jeg regner med det er [ra0514](https://altinn.studio/repos/ssb/ra0514-01) du reproduserte dette i, så jeg lenker den opp her for sikkerhetsskyld.

**Comment by bjosttveit** [comment]
Etter litt testing, så virker det som om dette er et problem med `react-number-format` som brukes i design-systemet. Klarte å reprodusere denne feilen veldig enkelt i en sandbox ved å bruke samme suffix som her, med versjon 4 av `react-number-format` som er den versjonen som brukes per i dag. Det har derimot kommet en ny major versjon av denne pakken (v5), der det ser ut som at denne feilen er fikset. Klarte i alle fall ikke å reprodusere feilen med den nyeste versjonen av pakken.

For å løse dette problemet må man altså migrere over til versjon 5 av `react-number-format`, de har en migration guide her: https://s-yadav.github.io/react-number-format/docs/migration/. Det virker som det ikke vil kreve noen store endringer, men dette må i så fall testes grundig.

**Comment by bjosttveit** [comment]
Sandbox v4 (bug): https://codesandbox.io/s/suffix-v4-xdq6ik?file=/src/App.js
Sandbox v5 (fikset): https://codesandbox.io/s/suffix-v5-u8zuwb?file=/src/App.js

**Comment by bjosttveit** [comment]
Oppdaget dessverre en annen bug i versjon 5 som ikke eksisterer i versjon 4 😩 

https://user-images.githubusercontent.com/47412359/196427823-08411e60-b29b-4a35-ac89-045ee9118576.mov

**Comment by bjosttveit** [comment]
PR designsystem: https://github.com/Altinn/altinn-design-system/pull/156

**Comment by StianVestli** [comment]
Ser ut som denne funker som den skal nå
