### ISSUE TITLE
Flexible validation text for standard required field

### ISSUE THREAD

**Issue by xmrsa** [Altinn/app-frontend-react#295]
### Description

Jeg testet dette med "shortName" nå for litt egendefinert tekst for obligatoriske felt. Jeg skjønte til slutt at jeg måtte legge det inni **textResourceBindings**-elementet (som var logisk selvfølgelig), men jeg ble skuffet over resultatet: 
![image](https://user-images.githubusercontent.com/42466346/175272747-1e582be3-6c42-4376-ad07-c499760d04a7.png)

Jeg skulle gjerne sett at jeg stod helt fritt til å velge hele valideringsteksten, altså at jeg slapp å få "Du må fylle ut" først. "Du må fylle ut" gir jo bare mening for tekstbokser/tallfelt, mens det for radioknapper f.eks. vil det være naturlig å bruke noe annet som "Du må velge minst ett alternativ" eller "Spørsmålet må besvares". I mitt tilfelle med kun en avkrysningsboks gir det heller ikke noen mening med en standard tekst av typen "Du må huke av for minst én tekstboks". Jeg tror dere ser poenget her...

### Additional Information

We would like to have an element f.ex. called "**validationText**" where we can choose the text freely. This option should also be available in **Altinn Studio** as a dropdown list so it's easy to refer to the defined texts.

Forslag til navn: requiredValidation

**Comment by xmrsa** [comment]
De komplette feilmeldingstekstene som man kan legge inn i datamodellen direkte, fungerer dårlig siden vi ofte har et behov for å oppdatere datamodellene. Da blir jo disse tekstene borte.

Hvordan er det med det nye datamodelleringsverktøyet i Altinn Studio... skal man kunne ta utgangspunkt i en _eksisterende_ SERES-modell og så _modifisere_ denne, eller må man begynne "fra scratch"? Vil man kunne "oppdatere" den eksisterende datamodellen direkte, uten å laste den inn som en "ny" datakilde? Vil man da kunne **beholde valideringstekstene** som eventuelt er definert rett på datamodellen?

**Comment by olemartinorg** [comment]
@xmrsa Hmm - jeg ser ikke for meg at løsningen i denne saken blir å legge inn noe tekst i datamodellen. Det bør heller inn i layout. Hva gjelder resten av spørsmålene er det nok best å spørre om disse i slack-kanalen og få svar fra noen av dem som jobber med det nye datamodelleringsverktøyet (jeg kjenner lite til det).

**Comment by rvessb** [comment]
@olemartinorg Vi har hatt et internt møte (i SSB) og avklart hva vi ber om i første omgang for å oppnå det som etterspørres i denne saken når det gjelder feilmeldinger for **påkrevde felt**. Vi behov for 2 ting:

1. Dersom "shortName" benyttes til feilmeldingstekst vil vi at feilmedingsteksten IKKE tar med default feilmedingstekst (Du må fylle ut {0}). Dersom vi først registerer egen "shortName" så greier vi å legge til "Du må fylle ut" i denne teksten dersom det er behov for det.
2. Vi har ofte spørsmål i tittelfeltene på svarfelt som passer dårlig inn med "Du må fylle ut....". Vi ønsker mulighet for å overstyre defaulttekst på skjemanivå (i første omgang) slik at vi gjennom hele skjemaet kan bruke en annen tekst enn "Du må fylle ut".  Dette inkluderer da å kunne "disable" funksjonen som endrer første bokstav i "tittel" til lowercase.

Jeg er usikker på om noe her må tas ut i egen issue, men fint om du sier i fra dersom du gjør det slik at vi får knyttet saken(e) opp til apps backlogg ;-)

**Comment by olemartinorg** [comment]
For meg ser det ut som nr 1 hører til her, og at vi kanskje bør innføre noe annet enn "shortName" som gjør dette. Når det gjelder nr 2 vil jeg tro den dekkes av [denne saken](https://github.com/Altinn/altinn-studio/issues/4791) som blir en del av endringene rundt språk som er på vei.

**Comment by FinnurO** [comment]
@nkylstad issuet som @olemartinorg mener dekker del 2 her er lukket. Kan vi avklare om del 2 har en løsning for SSB?

**Comment by olemartinorg** [comment]
Det var kanskje misvisende av meg da, heller. Overstyring av tekster som er definert i app-frontend virker til å være kjernefunksjonalitet som er viktig å få med for det nye språkhåndeteringsprosjektet, så det behovet vil uansett bli dekket på en eller annen måte - det er iallefall ikke glemt.
