### ISSUE TITLE
Input felt med skjul vis regel i repeterende gruppe valideres ikke som det skal

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#296]
### Description of the bug

Hvis man har et felt i en repeterende gruppe som styres med skjul/vis regel, og som er satt som et påkrevd felt, så valideres den ikke når man lagrer gruppa på lik linje som resten av komponentene i gruppa.

### Steps To Reproduce

Opprette en repeterende gruppe med flere input felter, feks 3 alle påkrevd og et med en vis skjul regel hvor da feltet er default skjult.
feks:
```
 {
        "id": "Side2-Spm2c2-dcb307b9-41d5-40ee-a266-ee3ca9394e67",
        "type": "Input",
        "textResourceBindings": {
          "title": "lang.s2.tittel.driftsutgifter"
        },
        "dataModelBindings": {
          "simpleBinding": "SkjemaData.repMiljovernOmr.miljoOmrDriftUtg"
        },
        "required": true,
        "readOnly": false,
        "grid": {
          "xs": 12,
          "innerGrid": {
            "xs": 4
          }
        },
        "formatting": {
          "number": {
            "suffix": " 000 kr",
            "thousandSeparator": " "
          },
          "align": "right"
        }
      },
      {
        "id": "Side2-Spm2c3-7c2c337c-7644-4621-b98d-0d9a3a3679d8",
        "type": "Input",
        "textResourceBindings": {
          "title": "lang.s2.tittel.tjenesterkjopt"
        },
        "dataModelBindings": {
          "simpleBinding": "SkjemaData.repMiljovernOmr.miljoOmrTjenesterKjopt"
        },
        "required": true,
        "readOnly": false,
        "grid": {
          "xs": 12,
          "innerGrid": {
            "xs": 4
          }
        },
        "formatting": {
          "number": {
            "suffix": " 000 kr",
            "thousandSeparator": " "
          },
          "align": "right"
        }
      },
      {
        "id": "Side2-Spm2c5-d520c88e-ae1c-41f2-9466-8d10c46e919c",
        "type": "Input",
        "textResourceBindings": {
          "title": "lang.s2.tittel.andreomraader"
        },
        "dataModelBindings": {
          "simpleBinding": "SkjemaData.repMiljovernOmr.miljoOmrAndreOmr"
        },
        "required": true,
        "readOnly": false
      }
```
inputfelte styrer om kort tekst feltet skal vises.
Ved åpning av gruppe ser det slik ut:
![image](https://user-images.githubusercontent.com/91887041/175481594-0f38cbb5-3b77-4407-a927-5e33979a95e0.png)
Slik vis skjul er satt opp skal siste felt vises hvis vi angir noe i et av feltene over:
![image](https://user-images.githubusercontent.com/91887041/175482081-8e2f3229-5f30-4a5c-b8ca-aaea1837a9df.png)
Trykk så på lagre:
![image](https://user-images.githubusercontent.com/91887041/175482361-9b9f00a0-fb2d-44b8-be13-ebf1b517bae2.png)

som man ser valideres det feltet som var synlig hele tiden, vis skjul feltet er ikke validert sjølv om dette også er påkrevd. Trykk lagre en gang til og den lukker raden:
![image](https://user-images.githubusercontent.com/91887041/175482536-64b04414-2934-443a-a92e-ff62c82cf09c.png)
Hvis en trykker rett feil på raden og åpner den igjen vises fortsatt bare feilen på det feltet som var synlig heletiden:
![image](https://user-images.githubusercontent.com/91887041/175482666-1250d7aa-5fc3-49ee-be67-28cd4e1cc443.png)
Lagre på nytt gjør ingen forskjell.
Men må fysisk klikke på feltet eller trykke neste side for at den skal validere dette feltet og:
![image](https://user-images.githubusercontent.com/91887041/175483012-a1d1f44e-16c4-48a0-b32d-f11bba9d8d0c.png)

![image](https://user-images.githubusercontent.com/91887041/175483041-bfd333ff-ce18-44d4-b0d4-d4d222b62aba.png)

**Comment by olemartinorg** [comment]
Jeg tror kanskje dette løses i forbindelse med #355 (som snart er ferdig), og om ikke det gjør det endres i alle fall koden betraktelig. Kan være verdt å vente litt med denne, og heller prøve å reprodusere feilen etter #355 er ferdig. Den innfører også ny type dynamikk for vis/skjul, og det kan hende problemet ikke oppstår på samme måte der.

**Comment by bjosttveit** [comment]
Ved bruk av expressions ser ikke dette ut til å være et problem lengre. Jeg brukte en slik regel for å skjule dato-feltet når adressefeltet var tomt: `"hidden": ["equals", ["dataModel", "Innflytter.TidligereBosteder.Gateadresse"], null]`

https://user-images.githubusercontent.com/47412359/201102361-70d6af4c-a9d7-4a7c-9552-b064ac87c65d.mov

@StianVestli vil du se om du klarer å reprodusere dette med ny dynamikk?

**Comment by StianVestli** [comment]
Men det vil bety at vi må løfte skjema til v7 da for at vi skal bli kvitt denne her i såfall? For ny dynamikk vil den støttes i v6?

**Comment by olemartinorg** [comment]
@StianVestli Ny dynamikk med uttrykk støttes også i v6 (men da bare i app-frontend, og der må man jo foreløpig bruke main eller en alpha-release). Backend-støtten som kommer i v7 gir deg automatisk sletting av data som hører til skjulte komponenter ved innsending, men det er ikke et krav om å ha v7 for å støtte ny dynamikk i frontend.

**Comment by StianVestli** [comment]
Har testa litt på et v6 skjema men ser ikke ut til at jeg får reprodusert det, selv med de gamle skjul vis reglene, ser ut som den validere "riktig" når en setter at gruppen skal trigge validation. Skrur man av dette funker det normalt. Og med validaterow funksjonaliteten så ser det ut til å funke som tenkt.

Nå har vi skrudd "validation" så får jeg ikke lukket gruppen selv om alle felter er lukket, dette er kun når vi har satt triggers: "validation". Dette har jeg ikke opplevd før.

![image](https://user-images.githubusercontent.com/91887041/201339524-0f5b0b52-a41d-4ec9-a861-a502b5cb39a6.png)

**Comment by olemartinorg** [comment]
Jeg meldte inn dette problemet som #653, så får vi se videre på det der (det virker som en ny sak). Lukker denne som fullført. :partying_face:
