### ISSUE TITLE
Oppstilling av statiske enkeltfelter i datamodell slik at de fremstår som tabell i GUI

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#298]
Det er behov for å kunne kombinere oppstilling av forskjellige skjemakomponenter, som er knyttet til statiske felter i datamodellen, i en tabellstruktur. 

- Må kunne utnytte full skjermbredde
- Støtte kolonneoverskrifter
- Kunne bruke Radioknapp, Avkrysning, Nedtreksliste, Kort svar og Paragraf

## What needs to be solved?

Denne typen tabeller i Altinn2 (bestående av enkeltfelter i datamodellen) må kunne gjenskapes som tabeller i Altinn3:
![image](https://user-images.githubusercontent.com/43333852/167856841-b06a341c-f2da-4b30-bba6-a008293575bd.png)
![image](https://user-images.githubusercontent.com/43333852/167858095-6a09a07c-0cc3-4b9b-9365-e8512b795b5c.png)

## How do you want it solved?

Utvidelse av funksjonalitet i "tabellkomponenten" som er under utvikling, slik at denne støtter statiske enkeltfelter i datamodellen
## Alternative solutions

En helt ny skjemakomponent kun laget for å håndtere tabeller bygget opp av enkeltelementer.

**Comment by olemartinorg** [comment]
Ai, her laget jeg en duplikat med #583 etter vi hadde et møte om refinement av #107. Siden den oppgaven er ferskere og har fått med seg noen andre beskrivelser av funksjonalitet som trengs (og er litt mer utvikler-sentrisk), lukker jeg denne og poengterer der at alt som er diskutert her også må tas med. #583 er også prioritert over denne i prosjektet deres, så den hadde vel sånnsett dukket opp først.. :wink:
