### ISSUE TITLE
Navigationbar component does not trigger "calculatePageOrder"

### ISSUE THREAD

**Issue by sondre-ma** [Altinn/app-frontend-react#306]
### Description of the bug

Adding "calculatePageOrder" to triggers in settings.json, or directly onto the navigationbar component has no effect, even though the trigger works as intended on the navigation buttons component.  

### Steps To Reproduce

1. Implement dynamic tracks.
2. Add "calculatePageOrder" to triggers in settings.json or directly onto the navigationbar component.
3. Launch app and try triggering dynamic tracks through navigation bar.
4. The form will simply go to the page you clicked on, without activating dynamic tracks.

**Comment by andreas-didriksen** [comment]
[Dynamic expressions ](https://docs.altinn.studio/app/development/logic/expressions/#viseskjule-hele-sider) will solve this issue. "calculatePageOrder" is still supported but in time it will be replaced with dynamic expressions.
