### ISSUE TITLE
Repeating lists/groups: Entries don't disappear when removed programatically

### ISSUE THREAD

**Issue by allinox** [Altinn/app-frontend-react#319]
### Description of the bug

We are currently trying to populate a repeating list/group based on a choice the user has made previously in the form. The user can then add additional information to these choices previously made in the repeating group.
Populating the list works fine, and is done through DataProsessingHandler. However, removing them does not.

For some reason, the front-end still displays entries that are removed, even though the blob-storage has correctly removed them from the list. And in some cases, it does remove the data from the removed entires, but refills and displays the entry as a copy of one of the actual valid ones. A refresh of the page seems to fix the issue.

What's strange is the fact that the C#-model seems to be remembering the same (wrong) state of the list as the front-end does, even though the blob-storage contains the correct list and values.

### Steps To Reproduce

1. Use an app which populates and depopulates a repeating group based on some previous question in the app.
2. Choose multiple options so as to cause multiple entries to show up in the repeating group
3. See that these show up in the repeating group
4. Go back and de-select one or more of the previous choices
5. Observe that the deselected choices have not been removed, and/or still remain but with the wrong data.

### Example

Say I check all available options in which child I want to apply for here:
![image](https://user-images.githubusercontent.com/22012997/177298584-15b6dbda-3d8e-4238-bb8f-e2351c570a60.png)

This will (correctly) load prefilled values over to the repeating list so that I can add the additional required information to each child.
![image](https://user-images.githubusercontent.com/22012997/177298770-7e0f5596-d748-487b-a484-b839b14cc0cd.png)

But then, say I change my mind, and go back to uncheck the two first children.
![image](https://user-images.githubusercontent.com/22012997/177298943-258eb63b-f01c-46d6-9e51-bb785fa2d93a.png)

One would expect this to cause the data and entries of the two first children to be removed from the list and for only the third (Falsk Talltegn) to remain. And indeed, this is what is stored in the blob. But when I move on to the next page, it is not what I see as a user. Instead, I get an incorrect list, with two entries of the one child I actually checked off for, and one unchecked child.
![image](https://user-images.githubusercontent.com/22012997/177299292-a056f518-0aad-447d-8f13-f5a067e23f19.png)

**Comment by olemartinorg** [comment]
This problem should now be solved, and released in the latest frontend version [v3.48.0](https://github.com/Altinn/app-frontend-react/releases/tag/v3.48.0). However, most of the bug was in backend library code, and requires your app to be ported to v6.0.1 (or newer) of the app nuget packages. When possible, please have a look at the breaking changes for [v5](https://docs.altinn.studio/community/changelog/app-nuget/v5/) and [v6](https://docs.altinn.studio/community/changelog/app-nuget/v6/) for details on how to port your app. If you're having issues upgrading, do not hesitate reaching out! I'm looking forward to hearing if these fixes solves the problem. :blush:

**Comment by allinox** [comment]
Wonderful! Thank you so much! 😄

I'll see about upping the app to v6 so we can test the changes.
I'll let you know how it goes 🤞

**Comment by allinox** [comment]
@olemartinorg 
It works! 🤩
Thank you so much for the fix! 😁
