### ISSUE TITLE
Delete-row-button should be moved out of the group and into the table.

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#322]
### Description

Today our delete button is inside each element in the repeating group. We should move it out of the group and place it next to the edit button.

## Sketches
![Skjermbilde 2022-07-05 kl  14 49 37](https://user-images.githubusercontent.com/33222679/177331477-42f6ef5c-61c7-4295-b783-770ab6f14cf4.png)
![Skjermbilde 2022-07-05 kl  14 50 17](https://user-images.githubusercontent.com/33222679/177331597-a9314dc5-b75c-4c9e-9e92-e5c07ec05a3a.png)

[Figma link](https://www.figma.com/file/wnBveAG2ikUspFsQwM3GNE/Altinn-Studio-Apps?node-id=13550%3A9415)

## Acceptance criterea
- [ ] the edit and delete buttons should show as icons only when screen is smaller than 768. 
- [ ] The button is moved outside of the group

**Comment by lorang92** [comment]
@Magnusrm functionality tested ok. I see that our icons in the table header cells 
![image](https://user-images.githubusercontent.com/10416981/187204429-c19babe5-a119-497c-83c8-1452d352fc41.png)
 does not have aria-labels 
![image](https://user-images.githubusercontent.com/10416981/187204279-9dc87dd8-971b-4006-8cc5-c555ba97a002.png)

I guess this should be added before we close this issue.

**Comment by Magnusrm** [comment]
Thanks! I will add the aria-labels then 👍
