### ISSUE TITLE
The focus/active-indicator for edit-button should stay activated when you edit inputs in the group. 

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#324]
### Description

When a group is open and in "edit" mode. The "rediger" button should be in an active state.

## Sketches
Example on how it should look 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/1464915/188106954-d182bc6b-b7bc-4207-9772-0680ec1942fd.png">

**Comment by olemartinorg** [comment]
@Magnusrm: Tested this change now, and it works as advertised. I still find it a bit confusing, though.

1. When clicking the button (using the mouse) to close editing mode, the button stays active until you shift focus away from it:

![20220902_10h47m21s_grim](https://user-images.githubusercontent.com/700139/188102295-4d72bf3f-1d75-495d-8d1e-b5cf42b48d44.png)

2. Also, when using the keyboard to navigate to the button, it uses the same active state:

![20220902_10h48m56s_grim](https://user-images.githubusercontent.com/700139/188102964-5c6f42d2-5eae-4c9b-b31c-a1d8e3167c4f.png)

In contrast, hovering with the mouse pointer uses another state:

![20220902_10h51m23s_grim](https://user-images.githubusercontent.com/700139/188103075-57496d22-4965-40f1-841d-37e2e0b40d57.png)

@Febakke has the final word, but my suggestion would be to:
1. Remove any extra styling/state on focus (unless that breaks other things)
2. Use the same focus/active state as when hovering with the mouse (except for highlighting the row, maybe)

**Comment by mrosvik** [comment]
@olemartinorg  

The icons in the table header should not show. That is a mistake in Figma, I corrected it now. 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/1464915/188106747-479bcb7b-8fb0-4c28-9c2b-d3a7d2ad61da.png">

**Comment by mrosvik** [comment]
@olemartinorg Sorry, det var visst ikke en del av denne oppgaven :) Vet ikke når denne feilen har kommet inn... Får lage en ny issue på det.

**Comment by Febakke** [comment]
This is apparently something we havent thought good enough trough on the design side!

The worst error with the design is like @olemartinorg pointed out, there are no focus change when using keyboard navigation. In reality we need a toggle button/switch for this, and we have not designed that. 

This button will be switched with this button when at some point it is ready in the design system. So it might not be smart to do special styling before that time. 
![Skjermbilde 2022-09-02 kl  11 35 59](https://user-images.githubusercontent.com/33222679/188111007-c334db71-c3d0-4ea8-a3f1-f2fd9b9e5d85.png)

Also this will look kind of weird until we have https://github.com/Altinn/app-frontend-react/issues/243 fixed. Then the group will be better connected with the button. As shown in the screendump in the issue description.

Im not sure what our best option is. 
1. Like @olemartinorg suggested and use a hover state. Then we will have a visible change when using keyboard navigation. 
2. Take this issue back to the drawing board, look into if we need to create some kind of toggle button. 

@mrosvik Any thought on whats best? 😇

**Comment by Magnusrm** [comment]
@mrosvik Regarding the header-icons, i removed them in another PR as i was fixing a WCAG issue for the header-icons. 
https://github.com/Altinn/app-frontend-react/pull/411

**Comment by mrosvik** [comment]
@olemartinorg Is it possible to add an **_active_** state that only shows when a group is open in edit-mode? I don´t think active and focus should look the same, since there have to be a visual change when using keyboard navigation.

**Comment by olemartinorg** [comment]
@mrosvik Yes, that should absolutely be possible! :smile:

**Comment by Magnusrm** [comment]
@mrosvik Kunne kanskje "pressed" stilen bli brukt som aktiv?
<img width="998" alt="image" src="https://user-images.githubusercontent.com/32294735/188567227-b494466d-f0cb-4bbf-b4fd-28abbe453487.png">

**Comment by Magnusrm** [comment]
After discussions with @mrosvik and @Febakke, we have agreed that this issue should be solved by implementing issue #243 as well as implementing the buttons from altinn-design-system.
