### ISSUE TITLE
Change repeating group "lagre" button to the secondary button design

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#327]
### Description

User tests show that user where confused by the icon button with the green checkmark. Thinking it was an indication that the page was saved. The secondary button has a more typical button design and should not compete with the primary (next) button on attention. 

## Sketches
![Skjermbilde 2022-07-06 kl  10 35 00](https://user-images.githubusercontent.com/33222679/177507343-5164107f-08b1-4071-908d-904bdbb5d6a4.png)

![Skjermbilde 2022-07-06 kl  10 35 13](https://user-images.githubusercontent.com/33222679/177507390-b6d216ef-3ab5-404e-8460-5f611a12d485.png)

**Comment by SimenRokaas** [comment]
Fare for at noen vil tro at knappen lukker hele skjemaet... hva med bare "Lagre"?

**Comment by Febakke** [comment]
**Tastaturnavigasjon: Feil fokusvisning**
Rammen rundt knappen forsvinner og det blir ikke vist vår standard fokusvisning.
![Skjermbilde 2022-08-09 kl. 12.54.27.png](https://images.zenhubusercontent.com/5c8b643d6e79732923030a9c/61c1ee54-7934-49d4-b841-a5285a49a493)

**Styling: Den er litt nærme elementet over. Her skulle vi gjerne hatt 24px mellomrom.**
![Skjermbilde 2022-08-09 kl  12 56 32](https://user-images.githubusercontent.com/33222679/183636923-52d9b6f4-182e-4a6d-83d1-d98962fa2570.png)

Skjermleser: Ok (VoiceOver) 
Små skjermer: Ok

**Comment by Febakke** [comment]
Tested ok!
Both focus and spacing is fixed 👌
![Skjermbilde 2022-08-18 kl. 16.12.05.png](https://images.zenhubusercontent.com/5c8b643d6e79732923030a9c/44861c6f-5ab7-40de-899a-d6e31ed2c06f)
