### ISSUE TITLE
Improve handleDataChange API

### ISSUE THREAD

**Issue by haakemon** [Altinn/app-frontend-react#332]
### Description

We have a change event `handleDataChange` which has gotten several new parameters lately, making the API for it a bit cumbersome to read and use. The name of the event is also a bit confusing, since it doesnt `handle` anything.

![image](https://user-images.githubusercontent.com/2082481/178212300-6feca244-ffed-403c-a896-f8ee8a4ed3da.png)

To understand what the parameters mean, we would need to go to the function definition. Some IDE's give good hints for this, but there are other usecases as well f.ex browsing the code on Github, or during code reviews. It also is problematic if you only want to assign a different value for the last boolean parameter. With the current API you need to pass all parameters to be able to set the last one.

A better API would be an object:

```jsx
onDataChange({
    value: 'updatedValue',
    key: 'propertyName',
    skipValidation: false,
    checkIfRequired: true,
});
```

### Additional Information
Additional reading about [RORO pattern](https://www.freecodecamp.org/news/elegant-patterns-in-modern-javascript-roro-be01e7669cbd/) (Receive an Object, Return an Object)

### Tasks

- [ ] Rename `handleDataChange` event to `onDataChange`
- [ ] Change the signature to accept an object instead of multiple parameters

**Comment by olemartinorg** [comment]
Closing this as solved by #528 (noticed this issue afterwards)
