### ISSUE TITLE
WCAG/contrast issues with green-500 

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#361]
### Description of the bug

We have two issues with the green color we use for our submit button. Both of these are breaking [1.4.11 Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)
1. Green-500 (#17C96B) have to low contrast to a white background.
2. Our new error summary gives the lower part of the page a light red background. This must be taken into consideration when finding a new color

 

### Steps To Reproduce

Check #17C96B with a contrast checker

**Comment by Febakke** [comment]
This is probably not a WCAG error

> If a button with text also has a colored border, since the border does not provide the only indication there is no contrast requirement beyond the text contrast 
[Source](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)

As long as the button text has good enough contrast to the background. 
Either way, we must solve the green on red issue. It does not look good, but it is not a critical error.

**Comment by bjosttveit** [comment]
The button has changed now, it now uses the design-system button with the color #0D6D3A. Is this still an issue?
