### ISSUE TITLE
App enters a retry loop when InstantiationHandler.RunInstantiationValidation returns negative result

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/app-frontend-react#370]
### Description of the bug

The issue occur if custom validation in `InstantiationHandler.RunInstantiationValidation` returns an `InstantiationValidationResult` with `Valid == false`. The app front end will correctly display the reason message, but will continue to attempt the POST request to create a new instance over and over indefinetly.

![image](https://user-images.githubusercontent.com/2217340/183652069-724a535e-c367-4aac-90d7-b44700552068.png)

### Steps To Reproduce

Test can be performed in the TT02 environment. 

1. Sign in as 02014300549
2. Pick to represent 910597493
3. Start the app: https://dat.apps.tt02.altinn.no/dat/bilpleie-soknad

The app should now display the reason for why you can't create a new instance. If you instead got a new instance, contact DAT and ask them to turn on the "dørvakt" or create your own app to test with. In the network log (dev tools) you should see the app attempting to create an instance over and over again.

### Additional Information

The issue was originally reported by DAT on the [dat-bilpleie-soknad](https://altinn.studio/repos/dat/bilpleie-soknad/src/commit/22656ceeb121e84c58e86b68a8736e9507e6805d/App/logic/InstantiationHandler.cs#L73) app, but it should be easy to create a simple app to recreate the issue.

**Comment by torbjokv** [comment]
This issue seems to have disappeared. Maybe the PR https://github.com/Altinn/app-frontend-react/pull/354 fixed it (sounded relevant in its description)? Feel free to close this issue @SandGrainOne

**Comment by SandGrainOne** [comment]
Yes, I agree. We can always reopen the issue should the problem resurface.
