### ISSUE TITLE
Objects in redux state for validations crashes the app

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#371]
### Description of the bug

In [this discussion on slack](https://altinn.slack.com/archives/C02ESDSC929/p1659963042393879), it was reported that simple operations on a group could cause the app to crash.

### Steps To Reproduce

1. In a repeating group with required fields, add a new row
2. Do not fill out the required fields
3. Try to save the row, observe there are validation errors since these fields have not been filled [note 1]
4. Delete the row with the validation errors present
5. Observe the crash

### Additional Information

Submitting this error report after triaging and fixing the bug.

This turned out to be an onion revealing multiple bugs. The root cause of this seems to be because some objects persisted in the validation state (originally React nodes) fail to render as react nodes, as React would crash with a cryptic message. When I cleaned up the redux state to not include react nodes/objects, that fix seem to have corrected the problem - but I was still unable to reproduce this in `frontend-test` and failed to write a regression test for it. It turns out the validation code did not correctly handle the repeating group in `frontend-test`, as it contains multiple pages. So, originally this bug failed to reproduce at [note 1] in `frontend-test`.

**Comment by Magnusrm** [comment]
Tested following the reproduction steps and the issue seems to be fixed.

**Comment by olemartinorg** [comment]
Thanks, @Magnusrm! I had some trouble reproducing this at first. (Mainly because our `frontend-test` app had a `multiPage` repeating group. For unrelated reasons, that skipped validation of required fields even with validation triggers.) I'll also contact the person who reported this to me on Slack as soon as this is released.
