### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by mjulstein** [Altinn/app-frontend-react#374]
### Description

If this project will be responsible for all the non-api-routes Altinn/app-template-dotnet#121
then there will be a need add a 404 page for the pages that do not exist.
@Febakke might have some ideas?

**Comment by Annikenkbrathen** [comment]
Studio had a issue for this
https://github.com/orgs/Altinn/projects/36/views/12?pane=issue&itemId=40564749

Can we use the same design?


![Image](https://github.com/Altinn/app-frontend-react/assets/100292724/86c02273-fab4-47df-a1b4-ae06d3bc1788)
