### ISSUE TITLE
PDF-generator needs a "page render completed" indicator 

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/app-frontend-react#388]
### Description

The new PDF-generator currently being planned will be using puppeteer and chrome to convert an app-page to PDF. To do this as flexibly as possible, puppeteer needs a "hook" on the page(s) being rendered that indicate that the page is ready.

In puppeteer this is called the [waitForSelector](https://pptr.dev/api/puppeteer.page.waitforselector/).

Ideally the PDF-generator should be able to wait for the same element regardless of page being rendered. There might already be such a DOM element, but the platform team will need help identifying what to use. 

We would like to find such a DOM element on all pages instead of restricting what pages that can be used to create a PDF.

**Comment by olemartinorg** [comment]
Closing, as this has been tested OK by @SandGrainOne
