### ISSUE TITLE
Kunne fremstille repeterende gruppe som enkeltstående sider i skjemaet (en side pr. rad i tabell)

### ISSUE THREAD

**Issue by lompa94** [Altinn/app-frontend-react#391]
SSB ønsker funksjonalitet for å vise hver rad i repeterende gruppe som en separat side.

Dette kan gjøres som en utvidelse av repeterende grupper, eller som en helt ny komponent.

Her er noen bilder:
![image](https://user-images.githubusercontent.com/17925860/143418492-896eb039-f5ec-471f-9c0e-4ea80e584d7f.png)
![image](https://user-images.githubusercontent.com/17925860/143418611-37e9ec89-46d3-4959-a2ab-5724000ef967.png)
![image](https://user-images.githubusercontent.com/17925860/143418635-c7de8b87-2f02-4925-9242-16108be696f9.png)

**Comment by olemartinorg** [comment]
@altinnadmin Litt sent å svare nå - men det ser ut til at behovet som ble løst den gang på mange måter var det motsatte. Man kan dele opp en gruppe slik at redigering av en gruppe/rad kan vises som flere sider (aka [multiPage](https://docs.altinn.studio/app/development/ux/fields/grouping/alternatives/#multiple-pages-within-group-display)). Hele tabellen til rep.gruppa vises fortsatt på en side/layout i skjemaet, men man får altså interne knapper for forrige/neste inni gruppa (og bare noen av komponentene i gruppa vises på hver side).

Dette behovet virker til å ligne litt mer på det behovet som er løst med [`saveAndNextButton`](https://docs.altinn.studio/app/development/ux/fields/grouping/alternatives/#saveandnextbutton) i #559.

**Comment by rvessb** [comment]
Behovet er dekt gjennom https://github.com/Altinn/app-frontend-react/issues/559. Fint om du lukker saken @olemartinorg

**Comment by olemartinorg** [comment]
Flott! Lukker saken, men drar også med meg @RonnyB71 her og spør om dette ikke også har litt overlapp med noen av ønskene for 'underskjema'-funksjonaliteten vi har diskutert..? 🤔 Ser spesielt for meg at det kunne være slik om man åpner raden for redigering i et modalt vindu/en overlay - da er man mistenkelig nærme brukeropplevelsen jeg ser for meg underskjema skulle kunne tilby.

**Comment by RonnyB71** [comment]
@olemartinorg det har definitivt litt overlapp med underskjema, og kan være et alternativ der hvis underskjemaene er relativt små, men samtidig såpass store at det gir mening i å ha de på en side. Underskjemaene vi ha sett på ifm. ny funksjonalitet dreier seg om fulle skjemaer, med mange sider, sidelogikk etc. så for de er nok ikke dette et alternativ.

**Comment by altinnadmin** [comment]
Enig, litt overlapp men husk at underskjema også må kunne tilgangsstyres og kunne benyttes via API. Så underskjema som "konsept" har flere aspekter enn kun brukergrensesnitt og visning.
