### ISSUE TITLE
Automatisk åpning av neste element i repeterende gruppe når man trykker på knappen lagre/lukk

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#395]
### Description

For å få bedre flyt for den som skal fylle ut preutfylte "elementer" i "repeterende gruppe" er det ønskelig med et option på "lagre" knappen (satt av utvikler) inne i gruppa som gjør at den gruppa du står i lukker seg og automatisk åpner neste gruppe (dersom den finnes).

Dette er i høy grad tenkt brukt kombinert med https://github.com/Altinn/app-frontend-react/issues/396 og i en del tilfeller også "mode" satt til "hideTable".

**Comment by Magnusrm** [comment]
@mrosvik Kan det tenkes at lagre-knappen bør se annerledes ut dersom man har skrudd på denne featuren? Tror du det ville vert best at rediger og lagre-knappen fortsatt fungerer likt, eller at kun lagre-knappen åpner neste rad?

**Comment by mrosvik** [comment]
@Magnusrm Ja, det bør stå noe annet på den om den utfører noe annet. 

Til vanlig står det vel "Lagre og lukk":
<img width="925" alt="image" src="https://user-images.githubusercontent.com/1464915/191419378-0cdc8e51-bd75-4c42-ab2e-cfd6b80f3789.png">

Er det hensiktsmessig å tvinge brukeren til å åpne neste (dersom det finnes en neste)?
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1464915/191419417-134e11b9-ebf7-4d4c-87d4-a845bfe30ce3.png">

Eller kan det være tilfeller der bruker har gått inn for å kun endre èn av gruppene? i Så fall bør det gjerne være mulig å velge å lukke den også? Ser for meg det kan oppleves irriterende om man kommer inn for å endre en enkelt gruppe, og blir tvunget til neste. En vil forsåvidt kunne lukke den fra headeren uansett, så mulig det holder. @Febakke Noe relevant som kom frem i brukertest rundt dette? :)  
<img width="927" alt="image" src="https://user-images.githubusercontent.com/1464915/191419633-5f7cf35e-c400-4110-9c2a-8eec65ec79f9.png">

**Comment by StianVestli** [comment]
Lagre og åpne neste funker ikke hvis man har satt filter på repgruppa slik at felter er skjulte, den går ikke til neste rad automatisk når dette er satt.

**Comment by StianVestli** [comment]
Vi ser vel at vi bør har muligheten til å styre om "lagre og lukk" skal vises eller ikke når vi har aktivert knappen "saveAndNextButton", dette fordi vi vil i noen situasjoner tvinge bruker til å gå gjennom alle rader feks. ved hideTable er true.
