### ISSUE TITLE
Close button not hidden when specified in layoutsettings

### ISSUE THREAD

**Issue by lasseklovstad** [Altinn/app-frontend-react#401]
### Description of the bug

- When the page is loading the close button is by default visible.
- When you refresh the receipt-page the close button becomes visible, even though you have specified to be hidden.

This is an important issue for Udir (Elevundersøkelsen) because the close button leads the user to Altinn, which we don't want. 

### Steps To Reproduce

1. Open altinn studio app with layoutsettingsfile where hide close button is true
2. When the app is loading the close button is still visible.

**Comment by lasseklovstad** [comment]
Det er kommet frem til følgende løsning i en chat på slack (https://altinn.slack.com/archives/C02EVE4TKA6/p1661339211264839). Ref: @nkylstad:
 
> - Det opprettes en ny optional uiSettings property på root (samme nivå som sets i layout-sets.json
> - Denne kan inneholde de samme feltene som kan settes på pages i Settings.json fila
> - Denne filen lastes allerede inn ved oppstart av applikasjonen. Man må da utvide reduceren (ev. opprette en egen action) sånn at disse innstillingene settes på staten.
> - Om man da har en Settings.json fil på en gitt task, så vil denne overstyre disse innstillingene, da denne filen lastes inn på et senere tidspunkt.
> 
> Jeg tror det skal løse problemet deres, for da får man hentet innstillingen FØR skjema osv i det hele tatt lastes. I tillegg skal dette også lastes inn for kvitterings-siden.
> Eneste utfordringen er ev. om vi da skal persistere layoutsets til Cosmos for å kunne gi samme oppførsel for kvittering lastet direkte fra Altinn innboks. Men det er kanskje noe vi kan gjøre om det faktisk blir et problem?

I første utkast tenker vi at settingsfilen ser slik ut : 

```json
{
    "$schema": "[https://altinncdn.no/schemas/json/layout/uiSettings.schema.v1.json"](https://altinncdn.no/schemas/json/layout/uiSettings.schema.v1.json%22),
    "uiSettings": {
      "hideCloseButton": "true",
      "showLanguageSelector": "true"
    }
}
```

**Comment by mjulstein** [comment]
This is merged and fixed... closing the issue
