### ISSUE TITLE
Submitting from confirm step shows no error message if submit fails

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#426]
### Description of the bug

If something goes wrong when submitting an application from the confirm step no error is presented to the user and the operation fails silently.

### Steps To Reproduce

1. Setup an app with a data + confirm step
2. Don't give the user rights to perform write/read on the confirm task
3. See that the validation call fails when submitting, but no error message is presented to the end user

### Additional Information
The backend will in this case respond with a 403 Forbidden which needs to be translated to a useful message to the user saying that they don't have access.

Utilize the unknown error page in app frontend and extend this with enough information to distinguish 403 Forbidden from other unknown error messages.

**Comment by FinnurO** [comment]
Related to #715

**Comment by Magnusrm** [comment]
blocked by https://github.com/Altinn/app-lib-dotnet/issues/241
