### ISSUE TITLE
"Rediger" should be named "Lukk" when open

### ISSUE THREAD

**Issue by Magnusrm** [Altinn/app-frontend-react#441]
@chrhaugland commented on [Tue Jun 15 2021](https://github.com/Altinn/altinn-studio/issues/6432)

## Is your feature request related to a problem? Please describe
In a repeating group each row can be edited (Rediger), but the name is still 'Rediger' when the row is open.

## Describe the solution you'd like
Im my opinion the label shoud be named 'Rediger' when the row is closed, but be renamed to 'Lukk' when a row is open (for editing)

## Describe alternatives you've considered
Since data is saved when you close the row, the label could be called 'Lagre'

## Additional context
![image](https://user-images.githubusercontent.com/7998798/122049648-f3b59a00-cde2-11eb-9ed1-56ff51ee404a.png)

---

@rvessb commented on [Thu Jun 24 2021](https://github.com/Altinn/altinn-studio/issues/6432#issuecomment-867592533)

Teksten på den blå lagre-knappen bør være den samme som vises oppe ved "blyanten". Ellers vil man tro at man kan lukke uten å lagre.

Helst skulle man selv kunne valg hvilken tekst som skal vises for de forskjellige "tilstandene" raden kan ha.  Det gjelder da også teksten på den blå "lagre-knappen".

**Comment by bjosttveit** [comment]
Det er nå mulig å overstyre teksten til rediger-knappen ved å sette `edit_button_open` og `edit_button_close` i `textResourceBindings` til gruppen: https://docs.altinn.studio/nb/app/development/ux/fields/grouping/setup/

I #526 ble det endret slik at standard tekst på rediger-knappen er det samme som lagre-knappen når raden er åpen (dvs. "Lagre og lukk").
