### ISSUE TITLE
FileUploadWithTag does not show tagTitle value in error messages

### ISSUE THREAD

**Issue by MariusLevang** [Altinn/app-frontend-react#444]
### Description of the bug

When not choosing a tag in the fileUploadWithTag component, the error message does not contain the tagTitle value from resources. It either displays "tagTitle" or [object object], depending on how you trigger validation.

### Steps To Reproduce

1. Set up a valid FileUploadWithTag component
2. Set a value for textResourceBinding.tagtitle that is defined as an id in resources 
3. Run and open schema
4. Upload a file to the FileUploadWithTag component
    - Do **NOT** choose a tag
5. Trigger validation by pressing "Lagre" or "Neste"
6. See faulty error message without tagTitle value

### Expected result:
An error message appears that contains the actual value of the resource. 
(In our case "Du må velge datatype" since it is defined in resources as '{"id": "tagTitle", "value": "Datatype"}')

### Actual result:
After clicking "Lagre": error message is "Du må velge [object object]".
After clicking "Neste": error message is "Du må velge tagtitle", where "tagtitle" is the id of the value.
The bottom error message also contains a long ID, where it for other components only contains the error message.

### Tried:
- Using different tagTitle values that are defined -> Same result.
- Entering a string that is not defined as an ID in resources -> The string is displayed in both situations (also instead of "[object object]"). 
    The long ID is still present in the bottom div.
- Updated to newest releases -> Same result.
- Tested locally with newest pushes for studio and frontend -> Same result.

### Notes
The tagTitle value is available to the component as it is displayed as the title of the tag dropdown menu.
I cannot find any obvious errors in the code, but I believe it is related to validation.

### Images
After pressing only "Lagre"
![fileUploadWithTag_lagre](https://user-images.githubusercontent.com/55030714/188833340-019a1d21-d98a-4cb0-9575-4784492cef29.png)

After pressing only "Neste"
![fileUploadWithTag_neste](https://user-images.githubusercontent.com/55030714/188833362-5367a634-3c28-41d7-ad3a-f21a7acccce8.png)

After pressing both "Lagre" and "Neste"
![fileUploadWithTag_both](https://user-images.githubusercontent.com/55030714/188833415-19f8eb56-f95f-492f-a0db-1cacbe4feaec.png)

Example of expected result, (from input field)
![expected_error_input](https://user-images.githubusercontent.com/55030714/188833470-8212b499-4d97-4cae-8811-dd1e487ec1da.png)
![expected_error_input_end](https://user-images.githubusercontent.com/55030714/188833481-2abc7330-cb53-46a7-86d2-f1b13403ff56.png)

**Comment by olemartinorg** [comment]
The `[object Object]` error seems to be fixed, but otherwise this issue is still reproducible. Adding `good-first-issue` to this one, as fixing one (or more) of these should be relatively easy. I might be wrong about that though, but contact me if you try tackling this issue and get stuck! :pray:
