### ISSUE TITLE
Print friendly css

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#445]
### Description

As a part of the new PDF microservice the PDF will be generated based on a "page" in the app. This page can basically be any url, but will typically be a summary page, confirmation page or any data page. The PDF is generated based on using a headless Chrome browser which will call back to the url, wait for the page to render and then create the PDF. This means that using File/Print in the browser on that same page and save it as PDF should give the same result. 

Currently this results in a PDF which needs some adjustments with regards to borders, hiding buttons and other elements that shouldn't be included in the print/PDF version.

### Additional Information

The assumption is that we need to be able to provide a (better) print css for this purpose.

This issue needs to be discussed further before implementation can be started.

**Comment by olemartinorg** [comment]
Linking this to the epic:
- https://github.com/Altinn/app-lib-dotnet/issues/63

**Comment by bjosttveit** [comment]
Can this be closed now?

**Comment by FinnurO** [comment]
Covered by #896?

**Comment by bjosttveit** [comment]
Closing as PDF generator has dealt with the problems raised in this issue.
