### ISSUE TITLE
The info text box overflows the side of the page

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/app-frontend-react#464]
### Description of the bug

![image](https://user-images.githubusercontent.com/47737608/188594971-bc60f5c8-13e0-45c5-b262-af64c5a4a44c.png)

### Steps To Reproduce

1. Go to https://ttd.apps.at21.altinn.cloud/ttd/pdf-test-ui-components
2. Fill out form and submit
3. Open generated pdf

**Comment by olemartinorg** [comment]
Not sure why this was moved here, we did not generate any PDFs in september of 2022. Closing this as I assume this problem doesn't persist in the new PDF solution where we _do_ generate the result. Report a new issue if there are problems with the new PDF generator.
