### ISSUE TITLE
Repeating groups: Validation trigger for single row

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#468]
### Description

Currently, adding `"triggers": ["validation"]` on a repeating group element will trigger validation for **all rows** inside the group when attempting to save/close **one row**. This is not what one might intuitively expect.

### Suggestions

1. Either make the `validation` trigger for repeating groups trigger validation for the row (a breaking change) and optionally introduce a new `validateRows` or `validateAllRows` specifically for groups, where all rows are validated (as they were before), if this is functionality we need.
2. Or introduce a new `validateRow` trigger for repeating groups, which only validates the current row, leaving the `validation` trigger as it is now.

### Example

The current solution leads to lots of noise in the UI when saving a row in a repeating group you haven't started filling out yet. This example is taken from an app that creates semi-filled rows the user have to expand to fill, but saving one of them validates all of them:

![bug-all-rows-validated](https://user-images.githubusercontent.com/700139/190150699-88f2f5e0-0724-4764-8a51-8491e7128a7b.png)

**Comment by Magnusrm** [comment]
Implementing this feature might solve the bug: https://github.com/Altinn/app-frontend-react/issues/296
