### ISSUE TITLE
Repeating groups: Footer med kalkulering for kolonner på repeterende grupper

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#477]
### Description

Det er behov for å kunne sette opp en (muligens også flere) bunnlinje (footer) i oppsummeringstabellen som kan vise kalkuleringer for hver kolonne basert på innholdet i radene i tabellen. 

- Man bør stå forholdsvis fritt til å sette opp kalkuleringsregelen
- Kalkuleringsregelen må kunne benytte datafelter som ligger utenfor den repeterende gruppen i beregningen
- Det bør være støtte for å kunne kalkulere flere kolonner samtidig. 

### Additional Information

Eksempel på kalkulering av en kolonne:
![image](https://user-images.githubusercontent.com/43333852/191027949-62e5361d-f8c6-484f-a68d-e42f4ad11ed9.png)

**Comment by rvessb** [comment]
org/ssb

**Comment by StianVestli** [comment]
org/ssb
