### ISSUE TITLE
Possible to design a confirmation view

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-frontend-react#482]
## Description

For some application owners, it is better to show a designed view of the data and not pdf. See Altinn/apps-backlog#1 

## Screenshots
![image](https://user-images.githubusercontent.com/13309071/140019711-8cbcd8b6-0f3d-49f9-a19f-43839322f124.png)

## Considerations

If we introduce a "confirmation view" design capability this might be used as input for a "receipt generated". This should be input to a more general "Do we need PDF" discussion. 

- Is there any need for components updates to be presented in this view?
- Can this be solved as a backend functionality? Generate HTML based on the layout and data and save it as data just like PDF?

## Analysis

Currently we support the following steps. Here data can be customized with formlayout as you wish, while the confirm step is static. 

```mermaid
stateDiagram
    direction LR
    [*] --> Data
    Data --> Confirm
    Confirm --> End
```

With the following process definition:

```xml
<bpmn2:process id="Altinn_Data_Confirmation_Process" isExecutable="false">
    <bpmn2:startEvent id="StartEvent_1">
      <bpmn2:outgoing>SequenceFlow_1</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:task id="Task_1" name="Fyll ut skjema" altinn:tasktype="data">
      <bpmn2:incoming>SequenceFlow_1</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_2</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:task id="Task_2" name="Bekreft skjemadata" altinn:tasktype="confirmation">
      <bpmn2:incoming>SequenceFlow_2</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_3</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:endEvent id="EndEvent_1">
      <bpmn2:incoming>SequenceFlow_3</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="SequenceFlow_1" sourceRef="StartEvent_1" targetRef="Task_1" />
    <bpmn2:sequenceFlow id="SequenceFlow_2" sourceRef="Task_1" targetRef="Task_2" />
    <bpmn2:sequenceFlow id="SequenceFlow_3" sourceRef="Task_2" targetRef="EndEvent_1" />
  </bpmn2:process>
```

The confirm step looks like this in the applicaiton:

![image](https://user-images.githubusercontent.com/10416981/188440537-b391f6b4-0ad5-4052-997e-9ccf912c1057.png)

BRG has a need to customize this view. How can we support this?

### Alt 1.

Keep the process as is: 

```mermaid
stateDiagram
    direction LR
    [*] --> Data
    Data --> Confirm
    Confirm --> End
```

But extend the `layout-sets.json` (see [docs](https://docs.altinn.studio/app/development/ux/pages/layout-sets/)) and make it possible to setup a layout set for the confirm step, where we would reference the datamodel in the previous step. Example configuration:

```json
{
    "sets": [
      {
        "id": "data-step",
        "dataType": "someDataModel",
        "tasks": [
          "Task_1"
        ]
      },
      {
        "id": "custom-receipt",
        "dataType": "someDataModel",
        "tasks": [
          "Task_2"
        ]
      }
    ]
  }
```

With the following app structure:

```
App:
| ....
├───ui
│   ├───custom-receipt
│   │   └───layouts
│   └───data-step
│       └───layouts
````

Changes needed:
- Frontend
  - If confirm step has setup a connected layout set => render.
  
### Alt 2.

As discussed in slack, another alternative would be to define a seperate data step that acts as a "Confirm" step.

```mermaid
stateDiagram
    direction LR
    [*] --> Data
    Data --> Data_2
    Data_2--> End
```

- What configuration would we need?
- What must be implemented to support re-using the same data model?
- How do we stay backward compat with existing applications using confirm (are there any?)

### Conclusion

After deliberation with the team + lead architect and our product owner we have landed on going forward with **Alt 1.**

### Altinn Studio

How can we add designer capabilities for different tasks? 

How can we map design to a given data model?  Do we need to? Can we make the assumption that it is a data model for the previous data task? 

What if the previous task had several data elements?

### Ops requirements
> Are there any requirements for monitoring? What is being built and what could go wrong? 
> Are there any requirements related to backup? 

## Acceptance criteria

- Possible to design the confirmation view with the elements?
- Still possible to save something that can be used as proof?

## Specification tasks

- [ ] Development tasks are defined

## Development tasks
- [ ] Add design capability in UI designer from another task
- [ ] Update Confirmation view to support uilayout
- [ ] 
## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by knut-olav-hoven-ske** [comment]
Skatteetaten har et behov for å hindre revisorer fra å trykke "Send inn"-knappen fra selve Altinn3-appen til skattemeldingen. Det skal ikke begrenses på rolle - da det skal være mulig å bruke next-API fra et sluttbrukersystem.

Vi har kartlagt noen mulige løsninger for å øke brukeropplevelsen i innsendingsprosessen.

**Mulighet 1: Deaktivere innsendingsknapp i Altinn3-app for revisors bekreftelse**
"Send inn"-knappen (se skjermbilde nedenfor) ikke bør vises i Altinn3-appen i steget for revisors bekreftelse, for å forhindre revisor i å gjøre feil.

Revisors bekreftelse må gjøres i et sluttbrukersystem eller i Skatteetatens Visningsklient (Skatteetatens egen brukerflate). Den åpnes ved å følge lenka "Se opplysninger som er mottatt".

Det er greit om "Send inn"-knappen skjules i begge bekreftelsesstegene. Skatteetatens Visningsklient får støtte for å bekrefte begge steg.

![image](https://user-images.githubusercontent.com/84783397/191499522-ee795fb5-04b7-42eb-80ec-4701cf608d1b.png)

**Mulighet 2: Lenke rett fra Altinn Portal innboks-element til Skatteetatens Visningsklient**
Fra innboks i Altinn Portal (se skjermbilde nedenfor), så kan lenka "Gå til skjema" føre brukeren direkte til Skatteetatens Visningsklient. Dette kan gjøres for begge bekreftelsesstegene.

SIRIUS bruker lite av mulighetene som ligger i brukergrensesnitt i Altinn3-apper. Hvis denne løsningen velges, så ønsker SIRIUS at dette også gjøres for feedback-steg.

Denne løsningen skal ikke endre den arkiverte kvitteringssiden.
![image](https://user-images.githubusercontent.com/84783397/191499622-299395be-bab4-4baa-ba76-64a4685b2485.png)

**Comment by nkylstad** [comment]
Hei @knut-olav-hoven-ske ! Denne endringen er nå merget og tilgjengelig til å tas i bruk. Så vidt vi forstår vil den støtte opp under mulighet 1 som du har beskrevet over, ved at man kan velge å ikke inkludere noen send-inn knapp på siden når man er i confirm-steget. Dere må da bygge opp visningen på siden selv, med de komponentene/tekstene dere ønsker å bruke, akkurat som i skjema. 
Dokumentasjon ligger her: https://docs.altinn.studio/app/development/configuration/process/customize/#custom-form-layout

Ta kontakt på studio-skd kanalen på Altinn-Slack'en om dere har noen spørsmål 🙂

**Comment by lorang92** [comment]
Adding support for this in studio should be handled through https://github.com/Altinn/altinn-studio/issues/2058. Following up SKD and BRG for their use of this. Any other bugs/needs will be reported as seperate issues. Closing issue as done.

**Comment by knut-olav-hoven-ske** [comment]
Hei, er det mulig å bruke dette til å lage tilpassede visninger i feedback-steget? Vi vurderer å bruke flere feedback-steg.
