### ISSUE TITLE
Clicking attachment component does not open file explorer

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/app-frontend-react#493]
### Description of the bug

When clicking the attachment box file explorer does not open up automatically. 
I first encountered this error 28.09.2022, it did not have this behavoir 23.09. 

### Steps To Reproduce

![bug-attachment](https://user-images.githubusercontent.com/47737608/192724847-a0f47227-fc75-4c18-b501-b1a99308f631.gif)

**Comment by olemartinorg** [comment]
Unable to reproduce this (old) issue, closing it as completed. Somebody would probably had complained (a lot more) if this was broken for everyone.
