### ISSUE TITLE
Summary component: Støtte for visning av ikke repeterende gruppe i summary

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#502]
### Description

Pr i dag greier ikke summary-komponenten å vise innhold i "ikke repeterende gruppe" (gruppering av flere statiske felt).
Summary-komponenten bør støtte visning av gruppe-komponenten,  dette vil gjøre det enklere å sette opp oppsummeringssider.

**Comment by rvessb** [comment]
org/ssb

**Comment by bjosttveit** [comment]
@rvessb Skal nå være mulig i siste versjon av main.
