### ISSUE TITLE
Summary component: Dynamikk og sporvalg lagt på skjemakomponentene må gjenspeiles i summary

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#503]
### Description

Dynamikk og sporvalg  som er brukt på skjemakomponentene må gjenspeiles i summary-komponentene. 

Slik det er i dag må det legges på egen skjul-vis-logikk for summary som gjenspeiler dynamikk og sporvalg i selve skjemaet.  Dette medfører en stor ekstra kostnad i utviklingstid og ikke  minst testing da man må teste at skjema og oppsummering fungerer likt.

**Comment by rvessb** [comment]
org/ssb

**Comment by FTLems** [comment]
org/krt

**Comment by olemartinorg** [comment]
Relevant:
- #311

**Comment by olemartinorg** [comment]
@rvessb @FTLems Da skal fiksen være på plass i siste alpha-versjon av app-frontend - kunne dere testet og gitt tilbakemelding om det fungerer som tiltenkt? :pray:

**Comment by olemartinorg** [comment]
@rvessb @StianVestli @FTLems @ivarne

Har noen av dere anledning til å teste denne fiksen og si ifra om det fungerer som dere tenkte? :pray: Som nevnt, tilgjengelig i siste alpha. Vi prøver å være litt mer restriktive med nye releaser (siden ting av og til har gått galt), så vi håper å få denne gjennom litt grundigere testing før vi lanserer endringen (selv om vi åpenbart tester ting internt hos oss også).

**Comment by StianVestli** [comment]
@olemartinorg  Skal denne støtte og at hvis en skjuler en hel side ved sporvalg så vil den ikke dukke opp på summaryen? eller er det bare skjul/vis på enkelt komponter som skal støttes?

**Comment by StianVestli** [comment]
@olemartinorg Det ser ut som det funker som det skal på enkeltfelter , men ikke på helgruppe ser det ut til, og ikke ved sporvalg som du selv sier at det ikke vil funke. Men å skjule en grupper burde funke kanskje?

**Comment by olemartinorg** [comment]
@StianVestli Superdupert, takk for tilbakemelding! :partying_face: Da henter jeg denne tilbake til tegnebrettet. Enig i at skjuling av en gruppe (og repeterende gruppe) skal skjule komponentene under, og det er noe vi har snakket om før - men som dessverre har falt litt ut. God anledning til å fikse på det nå.

**Comment by olemartinorg** [comment]
@StianVestli Nå er dette levert (i [siste release](https://github.com/Altinn/app-frontend-react/releases/tag/v3.55.0)), men jeg setter ikke oppgaven som ferdig enda, da jeg vil legge til automatiserte tester på dette. Se gjerne over og test ut om det fungerer! (Det vil si, skjuling av en ikke-repeterende gruppe vil nå skjule komponentene inni den.)

**Comment by StianVestli** [comment]
@olemartinorg  Da ser det ut som dette funker hvis jeg har klart å teste riktig.
