### ISSUE TITLE
Summary component: Summary komponenten kjører validering på alle sider i skjemaet

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#504]
### Description

I dokumentasjonen på summary står det: "You can choose to have the summary on it’s own page, or on the same page as other form components."

Dersom man velger å endre skjemaet fra "summary" og trykker  "tilbake til oppsummering" valideres alle sidene i skjemaet. Dermed får man valideringsfeil på på påkrevde felt som ligger fremover i skjemaet, noe som er svær uheldig.  Man får også masse feilmelding på eventuelle nye felt/sider som rapportør aldri har vært innom, men som har blitt aktivert som følge av endringen i utfyllingne. 

Det bør endres slik at:
1. "Validate page" kjøres på siden du komme fra dersom dette er satt på "navigationButton"-komponenten for den aktuelle siden.
2. Validering kjøres KUN på de feltene som er referert til gjennom "summary"-komponentene på oppsummeringssiden du kom fra.
3.  "forrige-neste-knappene" vises over "tilbake til oppsummering" (option på NavigatonButton" i håp om at utfyller velger å trykke neste i stedet for å punktutfylle ved å hoppe frem og tilbake mellom skjemasider og summary.

Saken er diskutert i denne tråden: https://altinn.slack.com/archives/C02EVE4RU82/p1664282577172729

### Additional Information

Gif'n nedenfor viser hvordan nytt sporvalg utløses og at man får en lang rekke med feil på sider man aldri har vært på.  Her får man også en feil på kontakt/kommentarsiden som jeg gjern vil ha etter oppsummering.

![image](https://user-images.githubusercontent.com/43333852/192970149-4b7dccfb-6510-4f9b-8775-c51b60035e07.png)

**Comment by rvessb** [comment]
org/ssb

**Comment by bjosttveit** [comment]
Hva om `Tilbake til oppsummering` enkelt og greit kjører `validatePage` istedenfor? Har du noen tanker @olemartinorg ?

**Comment by olemartinorg** [comment]
Tja, jeg er enig i punkt 1 over her:
_"Validate page" kjøres på siden du komme fra dersom dette er satt på "navigationButton"-komponenten for den aktuelle siden._

Mitt inntrykk var at "Tilbake til oppsummering" var en omdøping av neste-knappen (samtidig som at den knappen også da går til riktig side, til der hvor du kom fra). Dermed er det logisk at knappen fortsatt skal trigge det samme som neste-knappen ville gjort. Det er i alle fall ikke logisk i mitt hode at alle sider skal valideres når man trykker på knappen, for det er heller mer logisk at man går rett tilbake til oppsummeringen og _deretter_ valideres alle sider om du prøver å sende inn dataene. Mulig det ble laget med vilje en gang, og isåfall bør man nok lete litt i koden og finne ut _hvorfor_ det ble laget slik, for å finne ut om det ligger et viktig use-case bak dette som vi mister om vi tar det bort.

Etter min mening bør vi gå gjennom hele "tilbake til oppsummering" i denne oppgaven og rydde litt (og gjerne lage cypress-tester på oppførselen). Problemer jeg mener å ha sett med denne knappen inkluderer:
1. Dette med at den validerer alle sider
2. Mulig at den henger igjen om du går til forrige side istedenfor? Altså hvis du navigerer til en annen side (enten via NavigationButtons eller NavigationBar) blir den fortsatt liggende igjen som en omdøpt neste-knapp.
3. Den dukker også opp dersom du trykker på en valideringsmelding i ErrorReport.tsx (den saken som wrapper seg rundt neste-/submitknappen med feilmeldinger). Om du trykker på en av dem (og den peker til en annen side), får du opp "tilbake til oppsummering" (selv om det kanskje ikke var oppsummeringssiden du var på tidligere). Dette henger jo litt igjen med det vi har snakket om rundt `mode` på en side - vi vet ikke egentlig om en layout er en oppsummeringsside eller ikke, så det gir ikke helt mening å påstå at man går "tilbake til oppsummering" alltid.
