### ISSUE TITLE
Using dynamic options in page make it crash when going back to formfilling

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-frontend-react#511]
### Description of the bug

In relle rettigheshavere we use dynamic options (disabled now). When it is enabled for the kontroll størrelse option it crashes when returning to Data task from confirmation. The options provider is not called

altinn-app-frontend.js:2 
        
       TypeError: Cannot read properties of undefined (reading 'index')
    at t.getIndexCombinations (altinn-app-frontend.js:2:2053084)
    at altinn-app-frontend.js:2:2075576
    at Array.forEach (<anonymous>)
    at t.getOptionLookupKeys (altinn-app-frontend.js:2:2075463)
    at d (altinn-app-frontend.js:2:2017417)
    at d.next (<anonymous>)
    at m (altinn-app-frontend.js:2:1697323)
    at l (altinn-app-frontend.js:2:1697655)
    at altinn-app-frontend.js:2:1693835
    at g (altinn-app-frontend.js:2:1690101)

### Steps To Reproduce

Enable dynamic options for this field. 
Fill ot form
Go to confirm
Go back to data

See commit to disable
https://altinn.studio/repos/brg/rrh-innrapportering/commit/e228ecfee1f4f0bb1d070bdab256ff5f1ccd73ff

**Comment by olemartinorg** [comment]
I suspect this has been fixed now, as a consequence of #575 and #576. @TheTechArch, could you re-test this with [v3.54.0-alpha2](https://github.com/Altinn/app-frontend-react/releases/tag/v3.54.0-alpha2)? I've made some attempts to reproduce it now, but I haven't managed to do it (but I'm unsure if I used the app correctly).

**Comment by allinox** [comment]
@olemartinorg 
I tested this just now - seems to me like it works 😊

**Comment by olemartinorg** [comment]
@allinox Fantastic! Sadly, the fix is a bit risky - and along with the #540 PR, the next release is scheduled to have a lot of (risky) changes. I'm wanting to delay it until I can look over #556 and clean up a little as well. You'll hear from me soon!

**Comment by olemartinorg** [comment]
Closing as it is tested OK, but my point about the delayed release remains.
