### ISSUE TITLE
MultipleSelect laster ikke inn språket når optionlista har kobling til språkfila

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#516]
### Description of the bug

Når en opprette en MultipleSelect med kobling til en optionliste som er definert som JSON så laster den ikke inn språket, når elementene i lista linker til språkfila.
![image](https://user-images.githubusercontent.com/91887041/194066306-1bfd0b03-2385-4a8c-9a82-162b5eb3c071.png)
dette funker fint hvis man bruker checkboxer:
![image](https://user-images.githubusercontent.com/91887041/194066609-6c3feafb-3419-4a97-9711-c72679813626.png)

### Steps To Reproduce

Opprett en MultipleSelect:
{
        "id": "Side4-Spm2-lknjas87-c032-495d-8cc6-0fbc55ae9d30",
        "type": "MultipleSelect",
        "textResourceBindings": {
          "title": "Velg blant kjente arbeidskonflikter i listen"
        },
        "dataModelBindings": {
          "simpleBinding": "SkjemaData.Hjelpefelter.hjelpefelt1"
        },
        "required": true,
        "optionsId": "JaNei"
      }

Optionliste ser slik ut:
[
    {
      "label": "lang.option.ja",
      "value": 1
    },
    {
      "label": "lang.option.nei",
      "value": 0
    }
  ]

der teksten ligger i språkfila.
    {
      "id": "lang.option.ja",
      "value": "Ja"
    },
    {
      "id": "lang.option.nei",
      "value": "Nei"
    }

### Additional Information

![image](https://user-images.githubusercontent.com/91887041/194066342-a8bd8702-63d6-4110-80fd-06751139c408.png)
https://github.com/Altinn/app-frontend-react/issues/56
https://github.com/Altinn/app-frontend-react/pull/505

**Comment by StianVestli** [comment]
org/ssb

**Comment by bjosttveit** [comment]
Fikset i #517
