### ISSUE TITLE
Anonym frontend for stateless

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#52]
## Beskrivelse
Når vi tillater anonyme brukere (ikke logget inn på noen som helst måte) i tilstandsløse skjema (stateless) så må vi reflektere dette i applikasjonen - både i visuelt og der vi har kodelogikk som baserer seg på at du er logget inn.

## Akseptansekriterier
- [x] Når du starter et tilstandsløst skjema som anonym bruker skal du ikke se lenke til profil
- [x] Når du er i et tilstandsløst skjema som anonym bruker skal det ikke gjøres kall til backend for å refreshe tokens.

## Oppgaver
- [x] Skjule profil når man ikke er logget inn
- [x] Ikke gjøre kall for å refreshe token
- [x] Se over andre deler av kodebasen hvorvidt det er kall som ikke vil håndtere anonym bruker
  - [x] HomeController
- [x] Dokumentere hvordan man konfigurerer at en applikasjon aksepterer anonyme brukere

## Begrensninger
Gjelder kun for stateless endepunktene.

## Ferdig ferdig
- [x] Documentation (docs.altinn.studio) is updated (if relevant)
  - [x] Technical documentation
  - [x] User documentation
- [x] QA
- [x] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by tjololo** [comment]
Testet anonym frontend i en app deployet til et at-miljø, men med referanse til lokal frontend som beskrevet i README.
Fungerte fint å få opp skjemaet, men får feilmelding hvis man trykker på (X) oppe til høyre, virker som handleModalCloseButton  forsøker å hente party.
