### ISSUE TITLE
Layout for repeating group with "filter" and "showAll"

### ISSUE THREAD

**Issue by xmrsa** [Altinn/app-frontend-react#545]
### Description of the bug

When using **filter** and **showAll** for an ordinary group (not just a likert-group), it is possible to hide individual rows to produce a table-like structure. On every row I have a single field that indicates if it should be hidden or not, so filter works fine, but the layout is bad. Every "row" is shown as a rather big box. The box has a strange line in it when the window is wide.
![image](https://user-images.githubusercontent.com/42466346/195858165-ca2922c6-dbc0-4cb2-9d4e-bac41e5cf0eb.png)

When the window is smaller, the line disappears:
![image](https://user-images.githubusercontent.com/42466346/195858653-45f8d419-3c6c-4ce3-8e13-352924c998ec.png)

If it were possible to make the layout "tighter", more like a likert-group, it would start looking more like a table.

### Steps To Reproduce

Look at app https://altinn.studio/repos/xmrsa/ra0749-vare-01
on page 04_Omsetning to see the code behind the screenshots above. The checkboxes are on the two pages 02_Naering and 02_Binæring. There is also a similar case on page 08_IKT_Investeringer where the radiobuttons being answered with Yes in a likert group decides which repeating group is shown bellow (on the same page).
![image](https://user-images.githubusercontent.com/42466346/195860709-e6a7b14c-86b3-459c-8b77-4ae57eab429a.png)

**Comment by rvessb** [comment]
Ønsket om å kunne skjule den "grå stipla linja" som et option på skjemaobjektet står seg nok. Men slik totalt sett burde man muligens heller satse på dynamisk tabell for å løse dette behovet, det foregår vel litt planlegging i denne saken: https://github.com/Altinn/app-frontend-react/issues/107

**Comment by xmrsa** [comment]
Det som er veldig trist med denne filter-løsningen er at den ikke oppdager at en rad er skjult (og dermed IKKE skal ha obligatoriske felt).... jeg får nå en masse valideringer på felter man ikke kan fylle ut i det hele tatt. Ikke gøy. Jeg venter i spenning på at dynamisk tabell skal bli løst, for det er det vi egentlig vil ha. Så blodrødt som i skjermdumpen ble det.
![image](https://user-images.githubusercontent.com/42466346/196172494-963574fd-9eef-41b9-9350-bba7e2159086.png)

**Comment by rvessb** [comment]
@xmrsa Behovene/svakhetene du beskriver her vil vel bli fikset gjennom disse sakene:
https://github.com/Altinn/app-frontend-react/issues/389
https://github.com/Altinn/app-frontend-react/issues/355
https://github.com/Altinn/app-frontend-react/issues/477

I så fall kan du lukke denne. (sørg for at de ligger som behov i app-migration-saken).

**Comment by olemartinorg** [comment]
Her må vi sjekke om dette styling-problemet fortsatt opptrer ved bruk av `hiddenRow`, ellers lukke saken.
