### ISSUE TITLE
Support for dynamic rule configuration in repeating groups that are nested

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/app-frontend-react#55]
## What needs to be solved?
It should be possible to configure dynamic rules for components inside nested repeating groups.

## How do you want it solved?
-  Configure the repeating group in the rule configuration with the nested group id and the input value configuration similar to existing dynamic
      "7831f53f-7ede-4b27-941e-2643a92c1713": {
        "selectedFunction": "showWhenPersonIsSelected",
        "inputParams": {
          "value": "A{0}.B{0}.X"
        },
        "selectedAction": "Show",
        "selectedFields": {
          "56edae00-478d-482a-8443-ec285c6a55f4": "B-dropdownY{0}"
        },
        "repeatingGroup": {
          "groupId": "A",
           "nestedGroupId": "B"
        }
      },

**Comment by lorang92** [comment]
@acn-dgopa this feature has now been implemented. Would you mind taking a look and verifying the need? 
See related docs: https://docs.altinn.studio/nb/app/development/logic/dynamic/#n%C3%B8stede-repeterende-grupper

**Comment by acn-dgopa** [comment]
@RogerKjaernsrod  @ingunnjv FYI

**Comment by RogerKjaernsrod** [comment]
Testet ok for mt-3 (Økokrim)

**Comment by lorang92** [comment]
Closing issue as done.
