### ISSUE TITLE
Component: Multiple selection dropdownlist

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#56]
## Description
In some cases a user have to select more than one value form a large list of values. 
Example: Select all countries you have visited
This cannot be handled by checkboxes as the list would be too long. 

**NEW DESIGN**: https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=7538%3A45627

## Screenshots
Screenshot taken from NSM sketches: 
![Skjermbilde 2020-10-05 kl  14 43 50](https://user-images.githubusercontent.com/33222679/95080973-2fa74400-0719-11eb-9ee5-f0294a21a450.png)

## Considerations
Is this something we should support? If not we need a pattern or functionality to satisfy the need for this component.

How do we store multiple values?

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [x] Development tasks are defined
- [x] Test design / decide test need

## Development tasks
- [x]  add to app-frotnend
- [x] support comma seperated string

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [x] Documentation is updated (if relevant)
  - [x] Technical documentation (docs.altinn.studio)
  - [x] User documentation (altinn.github.io/docs)
- [x] QA
- [x] Manual test is complete (if relevant)
- [x] Automated test is implemented (if relevant)
- [x] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by mjulstein** [comment]
🤔 Functionality wise this is more like an accordion with checkboxes... A dropdown would typically collapse when clicking inside. @Febakke
