### ISSUE TITLE
Count and give feedback on the number of characters left in TextArea

### ISSUE THREAD

**Issue by akselhmadslien** [Altinn/app-frontend-react#565]
### Description

In a TextArea-field we would like to give feedback to the user on how many characters they have left before the maximum number is reached.

In Altinn 2 this looks something like this:
![image](https://user-images.githubusercontent.com/113341457/196692096-07fd045f-b380-4a1f-9353-8b1d87b0d4af.png)

### Additional Information
Given no custom validation in backend, and that the schema has information about the length the counter can be shown. If no length limit is set then the counter should be hidden. In the case of custom validation and length limit then "you are on your own"!

This triggers the need for better access to the datamodel and the properties set on the various components. See #990

The user should be allowed to toggle this on/off, and default is off. 

This is currently not included in the design system. This estimate includes updating the design system.

**Comment by FinnurO** [comment]
@mrosvik Er ikke dette dekket av ny tekstkomponent?

**Comment by RonnyB71** [comment]
@framitdavid take a look at the resize property as well if you don't mind. For text area fields we should be able to resize at least the height. Ideally we should be able to set number of initial lines and expand as you type and need more space, but that's for another story.

**Comment by framitdavid** [comment]
@RonnyB71 what about something like this? The text area has an initial height and then auto-resizes based on the content while the user is typing. Then I think we do not need the manually resize property on the `<textarea/>`? 🤔 



![Image](https://user-images.githubusercontent.com/46874830/236123394-dbdefe98-4e9d-4efc-971a-069fdc8b82f1.gif)

**Comment by framitdavid** [comment]
This was blocked because we needed a new release of the design system which is now released. 💯 

https://www.npmjs.com/package/@digdir/design-system-react/v/0.12.0?activeTab=readme

**Comment by framitdavid** [comment]
This is blocked again due to some bugs within @digidr/designsystem. I have fixed the bug and merged the [PR](https://github.com/digdir/designsystem/pull/456). Waiting for next release.

**Comment by framitdavid** [comment]
@bjosttveit @Magnusrm @lassopicasso, please feel free to update the @digdir/designsystem dependency if a new release is made while I'm on holiday. 💯
