### ISSUE TITLE
openByDefault = "first" does not work with filters

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#569]
### Description of the bug

openByDefault = first sets the editIndex to 0 regardless of filters. If the index 0 is filtered out, no item will be opened. Additionally this leads to the add new element button disappearing. Probably also applies to openByDefault = "last".

![image](https://user-images.githubusercontent.com/47412359/196905141-b0f8862d-b04f-47a1-8476-b34d8bd81275.png)

### Steps To Reproduce

1. Set up a repeating group with a filter that hides the first element, and uses openByDefault = 'first'.

```json
"edit": {
    "openByDefault": "first",
    "filter": [
      {"key": "Innflytter.TidligereBosteder.Postnr","value": "0102"}
    ]
},
```

**Comment by StianVestli** [comment]
Ser ok ut nå etter det man kan se.
