### ISSUE TITLE
Formattering av datoer i summary

### ISSUE THREAD

**Issue by akselhmadslien** [Altinn/app-frontend-react#573]
### Description

Jeg ønsker at datoen på summary-siden vises på samme format (f. eks. DD/MM/YYYY)  som er spesifisert i DatePicker-objektet. I dag virker det som datoen i summary følger formen fra datamodellen, noe som kan virke merkelig og forvirrende for brukeren dersom denne er på en annen form (i vårt tilfelle YYYY-MM-DD).

**Comment by margrav** [comment]
Her er det vel greit om altinn defaulter til datoformat anbefalt av språkrådet i både DatePicker feltet og i summary? https://www.sprakradet.no/sprakhjelp/Skriveregler/Dato/

De åpner vel både for DD.MM.YYYY og YYYY-MM-DD (ISO 8601)
Men ettersom DD.MM.YYYY er klart mest brukt bør vel vi også bruke det?

**Comment by bjosttveit** [comment]
Datoformattering i summary ble fikset her: https://github.com/Altinn/app-frontend-react/pull/585. Det er ikke laget noen ny release siden denne kom ut, men ved neste release vil altså dato i summary (og i tabellvisning) formatteres på samme måte som i date-picker komponenten.

**Comment by olemartinorg** [comment]
Ah - det fikk jeg tydeligvis ikke så nøye med meg! Takk, @bjosttveit!
@margrav @akselhmadslien Det vil si at dere kan overstyre lokal versjon og teste med siste alpha: https://docs.altinn.studio/app/testing/local/debug/#using-other-frontend-versions

**Comment by olemartinorg** [comment]
@margrav @akselhmadslien Fungerer fiksen, og kan vi lukke saken? 😄

**Comment by margrav** [comment]
@olemartinorg Denne virker forsåvidt, men det er fortsatt et problem at datepicker følger språket i nettleseren og ikke språket i altinn profilen. Mulig det er en separat bug

**Comment by olemartinorg** [comment]
Supert - da lukker jeg denne. Språkproblemet trackes i #602
