### ISSUE TITLE
Repeating groups: Pagination

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#581]
### Description

In repeating groups, we'd like to add the option to limit the currently visible rows via pagination. This is only a visual effect, and does not change the content in the data model in any way. The design system components for pagination in a table will arrive soon via an external contribution.

### Blocked by
- #580 

### Related issue(s)
- #107
- #578 (Use the same configuration options for pagination as in this issue)

**Comment by olemartinorg** [comment]
Additional considerations:
- Validation
  - Make it possible to prevent pagination when there are validations for the currently visible rows
  - Make sure it is possible to navigate to the validations even if they are on a different pagination page than the current one
  - Make sure validations on "hidden" rows still show up when navigating between different (form) pages - pagination should just be a visual thing, and should not affect which rows are actually considered hidden.
- PDF/Summary
  - It is important that PDF/Summary still shows all rows in the group
  - If we would like to have pagination in Summary as well, that should be registered as a separate issue
- Positioning
  - I would assume it's best to place the pagination row after `rowsAfter`, but we might want to have an option to place the pagination row somewhere else.

**Comment by bjosttveit** [comment]
## Notater fra møte 06.05.24

- Paginering bør kunne plasseres før rowsAfter. rowsAfter gjelder som regel for alle radene uavhengig av side, så kan være forvirrende om rowsAfter vises før pagiering.
- Konfig kan gjerne ligne på det som er i `List`-komponenten
- Positiv til [paginerings-komponenten](https://storybook.designsystemet.no/?path=/docs/komponenter-pagination--docs) i nye design-systemet, highlighte sider med validerings-feil.
- Kan hardkode antall rader per side i komponent-konfig, må ikke nødvendigvis ha dropdown som i List
- Konfigurere om man skal vise page numbers eller bare forrige og neste(?)
- Validering skal fungere som forventet med "usynlige" rader, dvs. kun en visuell sak, validering på navigasjon skal fortsatt skje om en "usynlig" rad har feil
- Fortsatt mulighet for hidden-row som før
- Skjule paginering når antall rader er <= rader per side

Summary:
- Utgangspunktet er at alt skal vises, paginering i summary ikke så viktig i første omgang så lenge ytelsen er grei
- Dersom summary har paginering, må alt fortsatt vises i PDF
