### ISSUE TITLE
Expressions: Filtering rows in repeating group

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#584]
### Description

It should be possible to use expressions to hide an entire row inside a repeating group. This functionality should deprecate the existing [filters for repeating groups](https://docs.altinn.studio/app/development/ux/fields/grouping/alternatives/#filter), which has been deemed too inflexible.

### Functional requirements
- [ ] It should be possible to use expressions to hide an entire row of a repeating group, including using lookups into components/the data model for the specific row. It might be possible to use the first node inside the group row as the `LayoutNode` when evaluating the expression.
- [ ] Hiding the entire row should also mark every component inside it as hidden, and the row should not render in the table at all. This includes nested groups.
- [ ] Updating the data used to evaluate the expression should immediately hide/unhide the row(s)

### Other tasks
- [ ] Add the new property needed to control this into the JsonSchema for layouts
- [ ] Implement support for this in `app-lib-dotnet` as well (or create issues for extending the expression engine to properly hide components inside hidden rows of the repeating group) 

### Additional Information

- #540 
- #569 
- #558

**Comment by bjosttveit** [comment]
How will this handle adding / editing elements? In the current implementation of filters, it is impossible to add new elements unless they match the filter on creation, the editcontainer is filtered out. Additionally, if you edit the field that is filtered on, and make the element no longer match the filter, the element and editContainer will disappear instantly without clicking save. Maybe the `repeatingGroupsEditContainer` should not be hidden automatically as it is with filters today?

**Comment by StianVestli** [comment]
org/ssb

**Comment by StianVestli** [comment]
Filter funksjon bør støtte flere regler samt, and, or,>,<,=,!=, contains osv. 
Den må ta hensyn til at ting er skjult med tanke på valideringer.
Hvis det settes opp kalkuleringer av felter i en repp gruppe så må denne også ta hensyn til filter som settes.
Man må kunne legge til nye rader som dere sier og slette rader, uten at filterte rader dukker opp slik det gjør i dag.

**Comment by StianVestli** [comment]
Den må også takle å vise en tom repgruppe hvis filteret fjerne alle rader, det ser ut til at den i dag, viser alle elementer hvis filtert ikke treffer noen rader.

**Comment by olemartinorg** [comment]
Lukker som duplikat av #389
