### ISSUE TITLE
Custom components are hidden in repeating groups

### ISSUE THREAD

**Issue by nkylstad** [Altinn/app-frontend-react#592]
### Description of the bug

When adding a custom component (`type: Custom`) to a repeating group, the component is not visible in the repeating group container. 

### Steps To Reproduce

1. Go to an app with a repeating group that contains a custom web component.
2. Set up the component outside the repeating group as well
3. See that the component is rendered outside the repeating group, but not within. 

### Additional Information

This is happening because `hidden="false"` is passed as an attribute to the html element. Since `"false" !== false`, the browser interprets this as `hidden` attribute being set on the element, and hides it.
The `hidden` attribute comes from a prop that is passed to the `CustomWebComponent` react component. The solution is to extract this prop in `CustomWebComponent` and handle the logic for hiding the component there.

The `hidden` prop only seems to be passed for components within repeating groups.

**Comment by olemartinorg** [comment]
@JohanGuntherKrogevoll Would you mind letting us know if the fix in #591 worked?
Also, is #596 a duplicate, or just related to this issue? :blush:

**Comment by JohanGuntherKrogevoll** [comment]
The fix in [#591](https://github.com/Altinn/app-frontend-react/pull/591) fixed the issue with the component not being displayed. 🎉  I dont see [#596](https://github.com/Altinn/app-frontend-react/issues/596) as a duplicate since the problem there is related to hiding the component again 😉

**Comment by olemartinorg** [comment]
Great! I'll close this one then, and we'll look into the rest of the problem in #596.
