### ISSUE TITLE
Repeating groups/Grid/List: Column configuration options for table 

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#603]
We'll soon have 3 components displayed as a table, those being [repeating groups](https://github.com/Altinn/app-frontend-react/issues/580), [Grid](https://github.com/Altinn/app-frontend-react/issues/583), and [List](https://github.com/Altinn/app-frontend-react/issues/578). All of these components could benefit from using a common configuration object for how to display columns. This includes support for:

- [ ] Changing the label for a given column (as an alternative to #68)
- [ ] Changing the width of the column to:
  - A fixed width (unless that interferes too much with a responsive design)
  - A fixed percentage width (where a combined 100% still reserves room for the buttons)
  - Auto width (the default)
- [ ] Controlling the text alignment in a column
- [ ] Controlling text overflow, using:
  - Ellipsis without line-wrapping (the default)
  - Line-wrapping and no overflow limitations
  - Line-wrapping with a max height (ellipsis or fade-out if the text overflows the max height)

**Comment by StianVestli** [comment]
org/ssb

**Comment by andsjo-svv** [comment]
org/svv

**Comment by Magnusrm** [comment]
Options:
`"width"`: Sets width of column to a fixed percentage, ex. `"25%"` if the space is available or `"auto"`, which equally distributes remaining width that is not set yet among columns with `"auto"`. Default: `"auto"`.
`"alignText"`: Sets text alignment to `"left"`, `"right"` or `"center"` for text content. Default: `"left"`.
`"textOverflow"`
- `"lineWrap"`: Toggles line wrapping for text content to `true` or `false`. Default `true`.
- `"lineHeight"`: Sets the number of lines displayed for text content before hiding overflow with an elipsis(...). Default: `2`.

### Proposed format for configuration options for Repeating Groups:

`tableHeaders` exists already, which, specifies which fields should be displayed in the table when the group is closed and in which order.
`tableColumns` will not determine any header ordering but will add column formatting options to headers based on the id's of the components in the header.
```
"tableHeaders": ["currentValue", "newValue", "mainUploaderSingle", "mainUploaderMulti"],
"tableColumns": {
  "currentValue": {
    "width": "25%",
    "alignText": "right",
    "textOverflow": {
      "lineWrap": true, 
      "maxHeight": 2
    }
  },
  "newValue": {
    "width": "shrink",
    "alignText": "center",
    "textOverflow": {
      "lineWrap": false
    }
  }
},
```

### Proposed format for configuration options for Grid:

This format adds configuration options to the `row` format used in [Grid](https://github.com/Altinn/app-frontend-react/issues/583)

```
{
  "id": "myGrid",
  "type": "Grid",
  "rows": [
    {
      "header": true,
      "cells": [
        {
          "text": "My header text",
          "columnOptions": {.            // new configuration determines column format
            "width": "30%",
            "alignText": "left",
            "textOverflow": {
              "lineWrap": true,
              "maxHeight": 3
            }
          }
        },
        {
          "component": "myFirstRowComponent1",
          "columnOptions": {.            // new configuration, determines column format
            "width": "70%",
            "alignText": "right",
            "textOverflow": {
              "lineWrap": false
            }
          }
        }
      ]
    },
    { "cells": [
      {
        "text": "my.text.key",
        "alignText": "center",           // new configuration for text cells, overrides column format for cell
        "textOverflow": {              // new configuration for text cells, overrides column format for cell
          "lineWrap": false,
        }
      },
      {"component": "mySecondRowComponent1"}
    ]},
    {
      "readOnly": true,
      "cells": [
        {"text": "texts.sum"},
        {"text": ["sum",
          ["component", "myFirstRowComponent1"],
          ["component", "mySecondRowComponent1"]
        ]}
      ]
    }
  ]
}
```

For reference: @olemartinorg
