### ISSUE TITLE
Local date-format is slow to load

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#607]
### Description of the bug

It appears that `moment.localeData().longDateFormat('L')`, which is used to get the users local date-format is not returning the users actual date-format immediately. ~~It seems to return a default at first. This results in showing the wrong dateformat on refresh, and then getting fixed when the component rerenders.~~

The cause was that the global moment locale was set inside of the datepicker component, so it would not load until a datepicker had been instantiated.

logging `moment.localeData().longDateFormat('L')` to the console on refresh:
![image](https://user-images.githubusercontent.com/47412359/199463327-0a79de4f-1d69-43f4-b79c-63cd3d79c09c.png)

On refresh:
![image](https://user-images.githubusercontent.com/47412359/199463065-e0c0ae19-e93c-4506-8c46-d0ecff15a62c.png)

After rerender:
![image](https://user-images.githubusercontent.com/47412359/199463118-4af44542-997e-4265-aa27-67b0846c27c2.png)

### Steps To Reproduce

1. Have the browser configured to use non-english language with a different date-format (like norwegian)
2. Have a date-component in a repeating group
3. Fill in some data
4. Refresh (should now show incorrect format)
5. Open and save a row (should now show correct format)

**Comment by StianVestli** [comment]
org/ssb

**Comment by StianVestli** [comment]
Ser ut som det funker som det skal nå.
