### ISSUE TITLE
Aktivere skrivebeskyttelse av inputfelt gjennom regler/logikk i skjemaet

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#614]
### Description

Pr. i dag kan man skrivebeskytte innputfelt gjennom å sette "readOnly": true på komponenten i layout.json. Det må være mulig å legge logikk på denne settingen, slik at feltet kun er skrivebeskyttet i gitte situasjoner.

En tenkt måte å løse det på kan være å utvide funksjonaliteten i skjulv/vis (renderingsreglener) med ett nytt valg for "skrivebeskyttet" under "velg handling".
![image](https://user-images.githubusercontent.com/43333852/185309345-b1a5ae2c-5e37-4e8c-b68a-1aad0cfeaba1.png)

**Comment by olemartinorg** [comment]
@rvessb Dette skal være løst nå, via dynamiske uttrykk som kan settes på `readOnly`. Kan dere teste, slik at vi kan lukke denne saken om det fungerer for scenarioet dere ønsket det til?

@Hannott Vi har ikke tatt med funksjonalitet for å tømme data ved innsending for låste felt, og jeg er usikker på hvordan nøyaktig vi skal gjøre det - og om det er noe som vi ønsker å tilby av standardfunksjonalitet. Hvis jeg har skjønt deg riktig er det ønskelig å kunne vise frem data fra datamodellen til brukeren å lese-modus, hvor gitte data blir fjernet fra datamodellen automatisk ved innsending? Kan jeg be deg heller opprette en egen sak (med en use-case-beskrivelse) på dette behovet, slik at vi får sett det i en større sammenheng. Det høres ut som noe som potensielt løses med [shadow fields](https://github.com/Altinn/altinn-studio/issues/8620), og jeg er uansett usikker på om vi vil blande inn datamodellen her.

**Comment by StianVestli** [comment]
Set ut som at dette skal funke som tiltenkt , bare sjekket equals og notEquals, regner med at resten av sjekken også funker som de skal. Testet både mot component og datamodel.
