### ISSUE TITLE
Valgfri plassering av help text icon og støtte for flere icon for samme skjemaelement

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#616]
## Is your feature request related to a problem? Please describe
Hjelpetekst-iconet ligger i gitte tilfeller for langt unna teksten du trenger hjelpetekst for. feks i bildet nedenfor burde iconet ligget til høyre for orgnummer.
![image](https://user-images.githubusercontent.com/43333852/84516894-c1082b80-acce-11ea-994f-eff3d49a031d.png)

## Describe the solution you'd like
En hvilken som helst måte å kunne styre plassering av hjelpetekster/iconer.
Man kan feks se for seg å kunne knytte ett, eller helst flere, hjelpetekster til nøyaktig plassering i tekster i resource.xx.json fila.
Feks noe slikt:
![image](https://user-images.githubusercontent.com/43333852/84517674-e8132d00-accf-11ea-90a8-09cfb87c6cc8.png)

## Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

## Additional context
> Add any other context or screenshots about the feature request here.

**Comment by olemartinorg** [comment]
Closely related to (if not duplicate of):
- #615

**Comment by RonnyB71** [comment]
Closing, duplicate of #615 and not an Epic.
