### ISSUE TITLE
Single field validation does not run on fields when loading the form

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#628]
### Description of the bug

If you're loading existing instance data, fields may appear valid even though [single field validation](https://docs.altinn.studio/app/development/logic/validation/#single-field-validation) would have marked it as invalid. This is because app-frontend will not run single field validation on fields that hasn't been changed in any way - it will just assume validation was successful.

To fix this, we might have to run server-side validation as soon as we load the instance (possibly only if instance data was found).

### Steps To Reproduce

1. Open the `frontend-test` app
2. Type `test` in the first name field, it gives an error
3. Refresh the page, the error is gone until you try to submit the form

### Attempted fix
When fixing #617, I tried fixing this problem at the same time, but my solution was problematic. What I did was extending the saga for `checkIfConditionalRulesShouldRun` to run `FormLayoutActions.updateCurrentView` to update the current view to the current view (hacky!) while telling it to run page validations (and I added a parameter to skip empty field validations). This way validations would run when the page loads (because the saga for `checkIfConditionalRulesShouldRun` runs after the page loads, and after dynamically hidden fields have been hidden when the page loads).

However, this leads to a breaking change (as single field validations can be set up to complain when required data is missing, and running that on the page load is quite user hostile). I found this solution kind-of hacky, so maybe this should be considered in relation to #339 (where we should investigate if we want our app to keep its state after a refresh, or if we can live with an app that behaves differently after a refresh).

**Comment by RonnyB71** [comment]
**Alternative 1**
Single field validation should run when loading the form if there are values in the field. This does not solve the case where you would like to validate if one of x number of fields have a value but not the others. 

**Alternative 2**
Trigger validation even if there is no data. This implies marking the single field validation as a "required" validation.

**Alternative 3**
Include a datatype for internal state and validations on each component. This is probably not doable for V4, but might be the preferred solution. This needs more discussion.

**Comment by RonnyB71** [comment]
Will be solved by #1506

**Comment by olemartinorg** [comment]
Isn't this essentially solved now, @bjosttveit? Not by running single field validation, but by gathering all validations and showing then on load.

**Comment by bjosttveit** [comment]
Yes this should no longer be an issue
