### ISSUE TITLE
Repeating groups: Kunne slå av muligheten til å fjerne og legge til grupper

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#64]
## Description
Noen grupper skal ikke kunne fjernes. Det vil typisk være pre-utfylte grupper som må være med i innsendingen. Vi må ha mulighet til å skjule slett-funksjonaliteten for disse elementene. Dette må være mulig å sette på noen eller alle elementer i den repeterende gruppen

## Considerations
Finnes det caser det man også skal kunne skjule "legg til ny" funksjonaliteten?

## Acceptance criteria
- [ ] Man kan fjerne "slett" knapp på pre-utfylte elementer
- [ ] Hvis brukeren kan legge til egne grupper så kan disse fjernes

## Specification tasks

- [ ] Forstår brukeren hvorfor den ikke kan slettes?
      - Her må vi se på om vi visuelt burde skille mellom preutfylte og egenlagde grupper for å gjøre det tydeligere at det er en forskjell på dem

**Comment by Halland67** [comment]
org/ssb

**Comment by olemartinorg** [comment]
Regner dette som en utvidelse av eksisterende funksjonalitet som gjør det mulig å skru av "legg til ny" for en gruppe:

*   Altinn/altinn-studio#7164

Det er altså mulig å fjerne ny-knappen ([lenke til dokumentasjon](https://docs.altinn.studio/app/development/ux/fields/grouping/alternatives/#addbutton)) og slett-knappen ([lenke til dokumentasjon](https://docs.altinn.studio/app/development/ux/fields/grouping/alternatives/#deletebutton)), men det er nok ikke mulig å gjøre dette for spesifikke "låste" rader i gruppen. Det vil si, man kan ikke legge til pre-utfyllte rader i en gruppe som ikke kan slettes, og samtidig beholde funksjonaliteten for å legge til flere rader manuelt (som deretter kan slettes igjen).

For å få til denne nye funksjonaliteten regner jeg med vi må bruke et hjelpefelt i datamodellen som spesifiserer om raden kan slettes eller ikke, og spesifisere hvilket felt i datamodellen som bestemmer dette i gruppens skjema-oppsett.

@Halland67 og @rvessb: For vår egen prioritering kunne det være greit for oss å vite om behovene deres blir løst av eksisterende funksjonalitet, eller om dere trenger støtte for å markere hver enkelt rad som mulig å slette eller ikke.

**Comment by olemartinorg** [comment]
En liten oppdatering. Jeg begynner å se litt på #61, som også er et prioritert issue. I forbindelse med den saken må jeg implementere det meste som trengs for å løse det som gjenstår i denne saken også, så da kan jeg like godt få med dette samtidig. Jeg lager en epic, #355, og har samlet disse sakene der.

**Comment by rvessb** [comment]
@olemartinorg Vi har også tenkt at men må bruke et hjelpefelt i datamodellen for å si hvilken "rader" i repeterende gruppe man skal få lov til å slette og ikke. Det vi nok også vil ha behov for er å skrivebeskytte enkelte av feltene som inngår i "repeterende gruppen" dersom de er "preutfylte", dette kan da også støtte seg på samme hjelpefelt.
I utgangspunktet tenker jeg at det ikke er behov for å merke hvilken rader som det ikke er mulig å slette, utover at sletteknappen er deaktivert.

**Comment by olemartinorg** [comment]
@bjosttveit FYI, the remaining part of this task now basically revolves around this TODO from #540:
```
deleteButton?: ExpressionOr<'boolean'>; // TODO: Make expressions resolve per-row
```

**Comment by bjosttveit** [comment]
Yeah, I figured I would give it a try. I need to get more familiar with expressions anyway

**Comment by tjololo** [comment]
Solved through #61
