### ISSUE TITLE
Repeating groups: Validation causes rows not to be closable

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#653]
### Description of the bug

Først beskrevet i #296.

Nå har vi skrudd "validation" så får jeg ikke lukket gruppen selv om alle felter er lukket, dette er kun når vi har satt triggers: "validation". Dette har jeg ikke opplevd før.

### Steps To Reproduce

1. Bruk `"triggers": "validation"` på en gruppe
2. Vis/skjul felter med dynamikk?
3. Observer at gruppen ikke kan lukkes

**Comment by bjosttveit** [comment]
Klarte ikke å reprodusere dette, klarer du å beskrive situasjonen mer detaljert @StianVestli?

**Comment by StianVestli** [comment]
Jeg skal prøve å reprodusere feilen igjen og commite så kan du få repo og commit.

**Comment by StianVestli** [comment]
Se på https://altinn.studio/repos/stian.vestli/ra0673-01.git commit 61b16fe00974ad85ad7f68a6e4834f3b1a1a15b6
Side 2 repgruppen der er satt til triggers validation. den lukkes ikke ved lagre og lukk.. Kan være noe annet rart i skjema da..

**Comment by bjosttveit** [comment]
Sjekka den ut nå, er det bare at den kjører validering på alle radene? For "triggers=validation" stopper deg fra å lagre raden hvis andre rader har feil, men sånn var det før også. Derfor vi lagde validateRow.

Eller er det en annen grunn til at de ikke lukker seg? Jeg får i alle fall opp valideringsfeil på alle de andre radene som ikke er fylt ut enda.

**Comment by StianVestli** [comment]
Ja det har du nok rett i at den validere alle radene, men jeg syns det er litt rart at jeg ikke får lukket gruppen som faktisk er ok. Men er det slik den vil fungere så er det jo greit nok, er vel validaterow som man vil bruke mest i repeterende gruppe vil jeg tro.

**Comment by bjosttveit** [comment]
Ja, vil tro at validateRow er bedre å bruke i nesten alle tilfeller, vi lot standard validation-triggeren for grupper være urørt for å ikke endre eksisterende oppførsel, men det spørs om noen egentlig har bruk for den typen validering i det hele tatt.

**Comment by bjosttveit** [comment]
Så spørsmålet er om vi skal la det være som det er, eller å sørge for at `trigger=validation` ikke stopper deg fra å lagre en gyldig rad men likevel kjører validering på hele gruppa. Tanker @olemartinorg ?

**Comment by olemartinorg** [comment]
@bjosttveit Oppførselen som var her er jo litt forvirrende, så jeg tenker vi skulle tillatt å lagre/lukke raden selv om andre rader har valideringsmeldinger.

**Comment by bjosttveit** [comment]
Jeg kan ta det 👍

**Comment by bjosttveit** [comment]
Fiks er nettopp merga i main, gjerne ta en titt @StianVestli

**Comment by StianVestli** [comment]
For det er slik at den nå skal lukke seg når jeg trykker lagre og lukk gang nr 2 da eller?

**Comment by StianVestli** [comment]
@bjosttveit den lukker seg fortsatt ikke når jeg klikker lagre

**Comment by bjosttveit** [comment]
Så lenge det ikke er valideringsfeil på raden du prøver å lagre skal den kunne lukkes, så forskjellen er at valideringsfeil på andre rader ikke skal ha noe å si

**Comment by StianVestli** [comment]
Ah , jeg som ikke er helt med, joda den lukker som den skal nå når feilen på raden du står på er rettet
Så da funker det bedre.
