### ISSUE TITLE
readOnly property doesnt work for radio-component.

### ISSUE THREAD

**Issue by FTLems** [Altinn/app-frontend-react#662]
### Description of the bug

Read-only property for radio-komponent doesnt work. If you set radio-component to readonly it will still be open for editing, but wont write the information to the data-model. 

### Steps To Reproduce

1. Create radio-button. 
2. Set readOnly property to true.
3. Test the component. Field will still be open for users to edit.
4. If you navigate to another page (another steg) then it will the remove what you have choosen on that radio-button.
5. Also check that it doesnt write information to datamodell. 
6.

**Comment by FTLems** [comment]
Please tag issue with: org/krt

**Comment by olemartinorg** [comment]
@FTLems Da er dette på plass i siste alpha av app-frontend. Kunne du testet? Gi beskjed om det fungerer som tiltenkt eller om noe var uventet!
