### ISSUE TITLE
Server validations can't be fixed when their message lies in resource files

### ISSUE THREAD

**Issue by allinox** [Altinn/app-frontend-react#678]
### Description of the bug

We need to tell a specific field that its validation error is now fixed (when the thing that fixed it is input to a different field than the one with the validation error)

As explained [here](https://docs.altinn.studio/app/development/logic/validation/#specify-that-validation-errors-are-fixed), there is a way to do it, but this method doesn't seem to work when the error message is fetched from text resource files.

All this gives us is a new error with the text *FIXED*text.label
![image](https://user-images.githubusercontent.com/22012997/202460584-c9cd33f0-7e71-41ad-bfcd-b24dac140588.png)

### Steps To Reproduce

1. Implement server validation on a field. Set the message in a text resource file.
2. Implement code that marks the error as fixed, triggered from a different field using [this method](https://docs.altinn.studio/app/development/logic/validation/#specify-that-validation-errors-are-fixed)
3. Observe that the error is not fixed

**Comment by bjosttveit** [comment]
I attempted to follow the above steps, and it worked as expected for me, the error simply disappeared. Is there a specific app i can use to reproduce this error?

**Comment by allinox** [comment]
Yes, you can check on [this one](https://altinn.studio/repos/brg/rrh-innrapportering) once I push the unfinished code to a branch 🙂

But did you use references to the resource files?
![image](https://user-images.githubusercontent.com/22012997/202478541-67a2eb76-0d5b-46e1-818b-cb586ddf1ff4.png)

**Comment by bjosttveit** [comment]
Yes I did use a text resource, i'll check out the app 👍

**Comment by allinox** [comment]
Takk! Du kan finne koden på branchen exceeds-100-validation 😊

**Comment by bjosttveit** [comment]
Hmm, in the app, it does not seem to work when not using a text resource either. The app is supposed to send back the message along with a severity (1=error, 4=fixed), but the app always seems to send back `severity: 1`, which then means that something went wrong when parsing the message. I have not found the cause of the error yet, but it does not appear to be with app-front-end as it does what it is supposed to given the information it receives.

**Comment by bjosttveit** [comment]
Figured it out 🥳 
1. Add `FixedValidationPrefix` to `appsettings.json` like this: 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/47412359/202664232-994cd076-85b4-45ce-9c1a-7be3d6f50ed0.png">

2. In `ValidateSumOwnerships`, there is a `NullReferenceException` caused by `rettighetshavere[i].posisjonEierGrunnlag` is null and not an empty string if none of these checkboxes are checked:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/47412359/202664657-33e5eb14-ebd8-4c6c-aad5-f94ba0644f6a.png">

Which causes the function to fail due to calling `rettighetshavere[i].posisjonEierGrunnlag.Contains`.

**Comment by bjosttveit** [comment]
The docs should probably be updated to include the information that `appsettings.json` may need to be updated for this to work.

**Comment by allinox** [comment]
It works!!🤩
Thank you so much!! 

And yeah, that'd be nice - I for one didn't know I had to make changes to appsettings 😅
