### ISSUE TITLE
Repeating groups: Special labels for the table view

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#68]
## Description
I mange tilfeller vil det ikke være nødvendig å vise hele ledeteksten i tabellvisningen hvor man har mye mindre plass til rådighet. Man burde derfor ha mulighet til å lage en alternativ versjon av ledeteksten som kun vises i tabelvisningen

**Eksempel:**
Editeringsmodus: Fyll ut både fornavn og etternavn
I tabelvisning: Navn

**Comment by rvessb** [comment]
Ser veldig bra ut, sett gjerne på label org/ssb
