### ISSUE TITLE
Missing value in summary when using dynamic codelist with query param in a repeating group 

### ISSUE THREAD

**Issue by JohanGuntherKrogevoll** [Altinn/app-frontend-react#680]
### Description of the bug

Missing value in summary when using dynamic codelist with query param in a repeating group. The component itself and the PDF looks okay. I can also see that the correct codelist is fetched from backend when reloading the summary-page. 

### Steps To Reproduce

1. Create a component i a repeating group that uses a dynamic codelist with query param
2. Open schema and select a value in the component.
3. Go to summary to see that the value is missing.

### Additional Information

[Discussion in slack](https://altinn.slack.com/archives/C02EJ9HKQA3/p1668772768633609)
[Example](https://altinn.studio/repos/dsb/uhell-transport-av-farlig-gods/src/commit/4b7dddef465f0eea25368309c2e51cf9974dfc8d/App/ui/layouts/Packaging.json#L56)

**Comment by olemartinorg** [comment]
Tasks I want us to complete when fixing this:
- [ ] Add Cypress test-case for mapped options in a repeating group
- [ ] Add Cypress test-case for summary of mapped options in the `changeName` layout in `frontend-test`
- [ ] Add Cypress test-case for summary of mapped options in repeating groups in the `group` layout in `frontend-test`

**Comment by bjosttveit** [comment]
Fix is merged to main, would you mind testing if it works for you now @JohanGuntherKrogevoll ?

**Comment by JohanGuntherKrogevoll** [comment]
@bjosttveit 
Works like a charm 😉
