### ISSUE TITLE
Issues with jsonschema validation on app frontend (new datamodels)

### ISSUE THREAD

**Issue by nkylstad** [Altinn/app-frontend-react#693]
## Description
When XSD has the `xsd:nillable` attribute set, the data model structure becomes 
```json
"oneOf": [
{
  // The actual schema, or reference to it
},
{
  "type": "null"
}
]
```
This is the correct way to set up a schema for a field that is nullable. However it is causing issues in app-frontend validation, since all of the following validation errors are triggered by invalid data against the schema:
- Actual error against the actual schema, f.eks. format, type, etc.
- Error against the second (null) schema
- Error agains the oneOf structure, since it does not "match just one of the schemas exactly".

This results in 3 different error messages in app frontend for the 1 error.

## Screenshots

![Image](https://user-images.githubusercontent.com/1636323/203765826-a8ac1512-78ea-4e11-8f33-c2e961c2f08a.png)

## Solution
We ignore the oneOf validation messages. This is not something that was actually supported properly in app frontend before, so ignoring those messages should not cause any issues. In addition, we ignore the `null` schema error message. We do not have `null` values in form data in app frontend. We only show the validation error on the actual subschema that is failing, which is what is expected in this case.

**Comment by olemartinorg** [comment]
Re-opening this, as testing revealed that problems persist even after the fix. [See discussion here](https://altinn.slack.com/archives/C02ESDSGPN1/p1670412156113459?thread_ts=1667921781.762209&cid=C02ESDSGPN1).

**Comment by olemartinorg** [comment]
Turned out to be a misunderstanding - closing the issue again.
