### ISSUE TITLE
Links in helptext doesnt work

### ISSUE THREAD

**Issue by FTLems** [Altinn/app-frontend-react#705]
### Description of the bug

Added helptext with links to an input component, but it is not possible to click on this.

### Steps To Reproduce

**Component:** 
      {
        "id": "6.2",
        "type": "Datepicker",
        "textResourceBindings": {
          "title": "6_2",
          "help": "6_2Hjelp"
        },
        "dataModelBindings": {
          "simpleBinding": "skjemainnhold.plikterHvitvaskingsloven.datoInternkontrollHvitvasking.value"
        },
        "required": false,
        "grid": {
          "xs": 12,
          "innerGrid": {
            "xs": 6
          }
        },
        "timeStamp": false
      }
      
     
     **Text from textresource-file:** 
         {
      "id": "6_2Hjelp",
      "value": "[Hvitvaskingsloven § 35](https://lovdata.no/dokument/NL/lov/2018-06-01-23#KAPITTEL_7)<br/>Viss føretaket ikkje har gjennomført internkontroll skal datofeltet ikkje fyllast ut."
    },
    
    **Text appears as link** but not possible to click on this: 
![image](https://user-images.githubusercontent.com/90687291/205053801-60ec977f-28d9-423e-b5c6-7d0d2d03a980.png)

**Comment by bjosttveit** [comment]
What do you mean impossible to click on? Does it close the popover instead?

**Comment by FTLems** [comment]
Sorry, I could have elaborated myself better. Yes,thats exacly what I mean. When tryin to click on the link the popup closes.
But trying again now, it seems to be working. Not sure why. So I will just close this issue now.

**Comment by bjosttveit** [comment]
The popover is set to close when it loses focus, and for some reason, clicking the link causes the it to lose focus and close. I noticed when i clicked and held the mouse down that it would close the popover. Quick fix incoming.

**Comment by bjosttveit** [comment]
Merged into main

**Comment by bjosttveit** [comment]
@FTLems have you tested it out since the fix?

**Comment by FTLems** [comment]
@bjosttveit  I just tested it. Works great. Thank you.
