### ISSUE TITLE
Kalkuleringer lagrer ikke data til datamodellfelter som ikke er i skjema

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#707]
### Description of the bug

Hvis man setter oppe en calculation rule som gjør en beregning og returnere denne til et felt i datamodellen som ikke er benyttet som inputfelt i skjema så lagres ikke verdien i datamodellen. 
Dette gjelder også når en benytter denne som variabel inn i en tekst.

Workaround er å opprette et skjult felt i skjema, da lagres data som det skal, men dette er en grisete måte å løse det på...

### Steps To Reproduce

Opprette en calculation rule som returnere inn i et felt i datamodell som da ikke har noen tilknytning til noe inputfelt i skjema.
benytt datafeltet inn som en variabel i en tekst som vises for å se at den ikke setter noe data.

**Comment by StianVestli** [comment]
org/ssb

**Comment by olemartinorg** [comment]
@StianVestli Har du en app du har testet dette på? Hvis du har en lenke til en app (og en spesifikk commit) med noen tilhørende steg man kan følge for å reprodusere dette, er det lettere for oss å ta en titt.

**Comment by StianVestli** [comment]
Du kan dra ned https://altinn.studio/repos/stian.vestli/ra1601-01.git  commit 51e50619784ff79ea90b304d3979ee755ac29808 har jeg gjenskapa feilen. Sett verdi i de to feltene for første side, for at side 6 skal vises som har variabelen som det beregnes mot i en tekst Hjelpefelt4. den siste commiten så funker alt for der er 2 felter lagt ut på side 1, som viser innholdet i hjelpefelt4 og 5.

**Comment by olemartinorg** [comment]
FYI: Jeg kom plutselig på denne i det jeg gikk gjennom koden for å kjøre klientside-kalkuleringer nå. Det ser ut til at dette er gjort med vilje, men jeg utforsker muligheten til å droppe dette i endringene jeg gjør i #1175 (som nok blir med til v4). Usikker på hvorfor det er gjort slik, men det krever da gjerne noe testing av apper som bruker dynamikk/kalkulering dersom vi gjør om på dette.
