### ISSUE TITLE
App crashes on confirmation task when user's role is not allowed to confirm

### ISSUE THREAD

**Issue by allinox** [Altinn/app-frontend-react#715]
### Description of the bug

Our case is such that there are 20 roles allowed to fill out the form, but only 13 roles are allowed to perform the confirmation step.
However, when setup for this is done in the apps policy file, as described by the documentation, and we test with a user that has one of these 7 roles that can perform the first step but not the second, the app crashes.

That is, the user is allowed to fill out the form and hit next, can see the confirmaton page (as expected) but they can also hit 'confirm'. And when they do, the app crashes with a 403 error.

This isn't exactly the ideal way to prevent the user from confirming. We'd much rather see some form of error message that explains why the user is not allowed to perform the confirmation.

The case here is that you have `read` access, but not `confirm`. 

### Steps To Reproduce

1. Have an app with two tasks defined. 
2. Set Role1 and Role2 to be able to perform one process task, but only Role1 being able to perform the next (in the policy file).
3. Try to perform Task1 with Role2 and see that it works. Move on to Task2
4. See that you are in Task2 and try to move on passed this with Role2.
5. The app crashes

### Additional Information

A proposed quick-fix is for front-end to handle the resulting 403 in a way that makes sense for the user.

**Comment by RonnyB71** [comment]
Blocked by https://github.com/Altinn/app-lib-dotnet/issues/205

**Comment by RonnyB71** [comment]
Closing, will be solved by #991
