### ISSUE TITLE
Prefix/suffix in input fields should have language support + way to differentiate thousand/decimal based on language

### ISSUE THREAD

**Issue by xmrsa** [Altinn/app-frontend-react#717]
## What needs to be solved?
There doesn't seem to be a way to get correct thousand separator depending on the chosen language (and probably also for the decimal separator) for numbers in input fields. The normal way to write large decimal numbers is f.ex. 1 000 000,00 in Norwegian and 1,000,000.00 in English.

## How do you want it solved?
The easiest would be that the browser "discovers" that it is a number and formats it automatically. We need to be able to specify the number of decimals somewhere. Maybe the best way to do this is with css, which you say you "don't support"? Supporting a "prefix" depending on the chosen language is probably impossible with css.

## Alternative solutions
You could improve the functionality for the Input-field by expanding the options for this type of element: 

{
  "id": "numberComponent",
  "type": "Input",
  ...
  "formatting": {
    "number": {
      "thousandSeparator": " ",
      "prefix": "kr "
    },
    "align":"right"
  }
},

The parameter "thousandSeparator" would have solved the problem if it were possible to use an **id** from the json-language-files to define if it should be space or decimal. You would then also need a similar parameter for "decimalPoint" with language support. The "prefix" should also have the possibility of referring to an id in the json-language-files.

The number of decimals should also be an option under "number" (maybe it already is?)

## Additional context
This feature is connected to the description in the documentation here: https://docs.altinn.studio/nb/app/development/ux/styling/#:~:text=Formattert%20tall%20i%20input%2Dfelt

**Comment by olemartinorg** [comment]
Team Studio: Jeg flyttet denne fra `altinn-studio` over til `app-frontend-react` fordi støtte for dette i Studio ikke hjelper noenting om vi ikke har støtte for det i app-frontend først.

Behovet virker enkelt og klart her; man ønsker å kunne språkstyre tallformatteringen. Det er en liten djevel i detaljene her, da - for slik jeg ser det kan vi implementere dette på veldig forskjellige måter:

1. Styre hele tall-formatteringen via dynamiske uttrykk (på utsiden av hele `formatting`-egenskapen, slik at man må potensielt putte inn flere `formatting`-objekter, et for hvert språk).
2. Heve hele `formatting`-saken slik at man heller kan referere til en egen "tallformatteringsnøkkel" i språket. Som f.eks. `"formatting": "numbers.weightInKg"` som har ulike visninger basert på valgt språk. Dette krever avansert støtte i språkeditor.
3. Styre hver nøkkel med potensiale for å hente verdier fra språket. F.eks. `"thousandSeparator": "numbers.thousandSep",` som er en nøkkel i språkressursene.
4. Dykke dypt ned i strengene og hent ut potensielle språknøkler (yikes!), som f.eks. `"suffix": " 000 numbers.moneySymbol"` hvor `numbers.moneySymbol` er en nøkkel.

De andre tingene som er meldt inn her er helt separate saker, og burde være separate issues (ingen hast med å melde dem inn, men denne saken bør ikke lukkes før dette har blitt meldt inn separat - eller fikset):
- Feilmelding bør vise verdien med tallformattering (potensielt allerede løst, @bjosttveit?)
- Mulighet for å vise postfix/suffix før man har fyllt inn noe som helst

**Comment by bjosttveit** [comment]
Feilmelding formatterer ikke tall per i dag nei.

**Comment by FinnurO** [comment]
- #602

**Comment by olemartinorg** [comment]
Jeg lenker inn diskusjoner rundt prefix/suffix fra designsystemet, samt tråd på slack om løsningen vi har nå:
- https://github.com/digdir/designsystem/issues/92
- https://altinn.slack.com/archives/C02EVE4RU82/p1685008050411359

Jeg gjenåpner saken, fordi det ikke er helt mulig å oversette alt her helt enda - bare forhåndsbestemte formater som valuta og enheter. Ønsket her er å oversette alt mulig, men vi må også se dette i sammeheng med hva som er fornuftig å implementere ihht. tilgjengelighet og støtte i Studio.
