### ISSUE TITLE
New dynamic fails for entire page

### ISSUE THREAD

**Issue by FTLems** [Altinn/app-frontend-react#718]
### Description of the bug

* When hiding entire page with new hidden option in layoutpage, it is not reflected when choosing next-buttons. 
If you choose next button and land on the page that actually is hidden, you will end up in a blank page and get stuck. 
![image](https://user-images.githubusercontent.com/90687291/206135793-0de72a73-b488-453d-aec1-805e5a5ef4cd.png)
Pressing next, you end up on the page that actually is hidden: 
![image](https://user-images.githubusercontent.com/90687291/206136168-2ab61f26-9d0d-423b-9c34-709389ab6f99.png)

This is the blank page you end up with: 
![image](https://user-images.githubusercontent.com/90687291/206136370-10725383-31ba-4edc-a28b-2c620ae3ab39.png)

### Steps To Reproduce

1. Run the app: https://altinn.studio/repos/krt/krt-1012a-1
2. Choose Advokat on the first page
3. navigate using next button

**Comment by olemartinorg** [comment]
I also discovered this, and have fixed it in #713 :blush:

**Comment by olemartinorg** [comment]
Another problem discovered here is that combining `"triggers": ["calculatePageOrder"]` with dynamic hiding of pages can lead to you attempting navigation to a 'next' page that is hidden using expresions. If that is the case in `calculatePageOrderAndMoveToNextPageSaga`, the navigation is now rejected and will appear as the next button not working.
