### ISSUE TITLE
Validering ved hjelp av dynamikk

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#726]
### Description

Vi ønsker en enklere måte å kunne sette opp valideringer på i skjema.
I dag må dette sette via validation eventet i C#, noe som gir mye og uoversiktlig kode, som igjen gir oss på sikt mye teknisk gjeld.
På samme måte som den nye dynamikken så ønsker vi en lignende løsning for valideringer.
Man må kunne sette opp regler som validere som true på lik linje som dynamikken, man bør kunne sjekke på et datamodellfelt eller en componentid.

- Valideringen skal ikke skje hvis felte har hidden=true.
- Man skal kunne benytte samme kontroller som ved dynamikk, dvs. "or", "equal" osv.
- Man må kunne ha muligheten til å linke inn et tekst id for å kunne ha en custom feilmeldingstekst.
- Man bør kunne styre om det er en hard kontroll eller en mjuk (error/warning)
- Man bør antagelig kunne si hvilke componentid som skal markers som feil, feks som ved summering av tall fra flere felter.
- Støtte warning og error
- Implementere alle metoder https://docs.altinn.studio/app/development/logic/expressions/

### Additional Information
Blocked by: https://github.com/Altinn/app-frontend-react/issues/1182

Includes cleanup in validation.ts ref. https://github.com/Altinn/app-frontend-react/issues/377

**Comment by rvessb** [comment]
org/ssb

**Comment by FinnurO** [comment]
![Image](https://user-images.githubusercontent.com/97158464/207955024-bb7bff48-06fc-48b0-bce7-2af1ef926ae1.png)

Eksempler fra en SSB tjeneste i A2. Bruker hjelpefelt, @my. 

Refererer til valideringsmelding, men usikker på hva screen tip er i A3.

**Comment by StianVestli** [comment]
Eksempel på enkel validering er feks ved to datovelgere å kunne legge på sjekk at den ene datoen skal være før den andre.

**Comment by olemartinorg** [comment]
Jeg tenkte litt på denne saken tidligere i dag, og jeg har et forslag til hvordan jeg ser for meg dette skal kunne konfigureres.

```json
{
  "id": "minKomponent",
  "type": "Datepicker",
  "errors": {
    "Datoen må være før år 2000": ["dateGreaterThan", ["value"], 2000],
    "validation.error.pre.1900": ["dateLessThanEq", ["value"], 1900],
  }
}
```

Merknader fra eksempelet:
- Vi har ulike valideringsmeldingstyper, så vi bør støtte `errors` men også soft-valideringer som `warnings`, `infos` og `successes`. Det blir fort litt rart med flertallsendelser her, så forslag mottas med takk!
- Hver nøkkel i objektet bør være en streng, som potensielt peker mot en tekstressurs
- Kjøring av uttrykket skal føre til en `true` eller `false` returverdi. Bare returverdier som gir `true` fører til en valideringsmelding.
- Jeg forutsetter også to nye expression-funksjoner her:
  - [ ] `value`, som henter ut verdien til komponenten man står på. Dette er en slags snarvei til `["component", "minKomponent"]` som gjør det enklere å skrive slike uttrykk hvor man henter ut komponent-verdien hele tiden.
  - [ ] `dateGreaterThan` som fungerer likt som `greaterThan`, men for datoer. Det bør også implementeres tilsvarende `dateLessThan`, `dateGreaterThanEq` og `dateLessThanEq`.

En kompliserende faktor her er at valideringsmeldinger i dag hovedsaklig knyttes til datamodellen, og for noen komponenter er det mulig å knytte flere bindinger til datamodellen. Det åpenbare eksempelet er adresse-komponenten (et konsept med flere input-felter i en komponent som vi kanskje ønsker oss litt bort ifra). Der blir det ikke helt åpenbart hvilket av feltene som skulle "fått" feilmeldingen. For andre, som `List`-komponenten, har vi hatt motsatt problem (ved at valideringsmeldinger har vist flere ganger på samme komponent fordi komponenten har flere knytninger mot datamodellen - dermed har det blitt implementert deduplisering i #1046).

Slik validering ved hjelp av dynamikk bør naturligvis også kjøres i backend (for API-brukere), men der forventes det at valideringene knyttes mot et sted i datamodellen, og frontend kan ignorere disse fullstendig (siden de samme meldingene burde dukke opp som følge av kjøring i frontend). Vi bør ta en runde med hva vi ønsker slik at vi finner en god løsning for både frontend og backend.
