### ISSUE TITLE
Specifying an invalid dataModelBinding in layout silently fails

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#743]
### Description of the bug

While testing an example app, where the form layout had already been set up, I just spent an annoying amount of time figuring out that a `dataModelBinding` pointing to a non-existing field in the XSD silently fails, and never saves data to the instance data - even though the backend never complains.

The frontend keeps its own state, also never validates the data model binding, and shows the value in-form while the frontend is loaded. It's not until you refresh the page to reload the instance data you'll find your data missing.

### Steps To Reproduce

1. Add a data model:
```xsd
<xsd:complexType name="MyModel">
  <xsd:sequence>
    <xsd:element name="Name" type="xsd:string" />
  </xsd:sequence>
</xsd:complexType>
```
2. Create a form layout and make a typo:
```json
{
  "id": "type-your-name",
  "type": "Input",
  "textResourceBindings": {
    "title": "Please type your name"
  },
  "dataModelBindings": {
    "simpleBinding": "MyModel.Naime"
  },
  "required": false
}
```
3. Observe that requests are successful, but no data is actually stored.

**Comment by olemartinorg** [comment]
Completed in #1742

**Comment by RonnyB71** [comment]
Closing this, tested and verified that invalid dataModelBinding now shows an error.
