### ISSUE TITLE
Dynamic expressions in repeating groups are incorrect on summary-page

### ISSUE THREAD

**Issue by akselhmadslien** [Altinn/app-frontend-react#747]
### Description of the bug

When having dynamic expressions for readonly on fields in repeating groups, the correct value of the dynamic expression is not shown on the summary page

### Steps To Reproduce

1. Clone the repository https://altinn.studio/repos/krt/krt-1230a-1/src/commit/58eaa73f7bf6a06d74fa49205213af1b0eba4c89
2. Start the app and log in as Sophie Salt
3. Fill in all required fields*. When filling out the repeating group do: 
- On the first group, select "Ja" on point "4.1 Har forsikringsforetaket et norsk organisasjonsnummer?", and use a valid orgnr (e.g. 974 760 673) on "4.2 Organisasjonsnummer". Fill in the rest of the group.
- Open a second group and select "Nei" on "4.1 Har forsikringsforetaket et norsk organisasjonsnummer?". Fill in the rest of the group. 
4. Go to the summary page and see that the "Edit"-buttons on the second group is on the wrong fields.

*To fill out the form faster, select "Nei" on "6.1 Behandler agentforetaket klientmidler?" and use valid email-adresses (e.g epost@epost.no)

### Additional Information

The readonly-state of the green fields on the form-page are not expressed by the "Endre"-buttons on the summary-page

Form-page:
![image](https://user-images.githubusercontent.com/113341457/207578548-8ad77322-c66b-4217-91d6-b8f261f9f582.png)

Summary-page:
![image](https://user-images.githubusercontent.com/113341457/207579256-a16f8221-a474-4fbd-8302-2cbb7795a061.png)

**Comment by olemartinorg** [comment]
I agree that the edit button should not be visible if the source component has `"readOnly": true`. Adding `good-first-issue` to this, as I believe it should be an easy fix.

**Comment by bjosttveit** [comment]
@akselhmadslien this should now be fixed in main. Could you let me know if it fixed your problem?

**Comment by akselhmadslien** [comment]
@bjosttveit It works! :)
