### ISSUE TITLE
Navigation dont show the top of the page.

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-frontend-react#748]
### Description of the bug

When I use the navigate button to navigate between two pages, it put the scroll position in the same position as the first page. It is strange too Scroll to the top of the next page to continue filling out the app.

I want the possibility to show the top of the next page when using the navigate button. A setting in the app wher the developer can configure if the pages in the app shoud always show the top of the page, or the same scroll position as the last page may be the best solution.

### Steps To Reproduce

1.	Open App wid two long pages.
2.	Scroll down to the bottom of the page one and use next button.
3.	The next page show the same position as the last page.

### Additional Information

Page 1 scroll to the bottom of the page and use “neste”.
![image](https://user-images.githubusercontent.com/75472603/202157831-91423843-4de6-452e-b51f-4ad2a3e3e1b2.png)

The next page is shown in the same position.  
![image](https://user-images.githubusercontent.com/75472603/202157875-b4ee2aa3-511d-405f-8cd8-b2dd1b96a9d3.png)

**Comment by olemartinorg** [comment]
This should be fixed in #713, but I didn't know about this issue back then.
