### ISSUE TITLE
Variables in text. Empty variables in will display path to datasource.

### ISSUE THREAD

**Issue by tronberg** [Altinn/app-frontend-react#754]
### Description of the bug

If a variable's datasource is empty, the path to the datasource will be displayed. 

![ra0182-01-01](https://user-images.githubusercontent.com/40568354/207824953-1dcf23b2-6428-43a8-bb4a-5acb120b5a15.JPG)

![ra0182-02-02](https://user-images.githubusercontent.com/40568354/207824959-00ba579a-474d-4913-a1a6-780472458041.JPG)

### Steps To Reproduce

Clone and run app ra0182.

**Comment by olemartinorg** [comment]
In the long term, we hope to replace these variables with [dynamic expressions](https://docs.altinn.studio/nb/app/development/logic/expressions/).

**Comment by olemartinorg** [comment]
As an easier quick-fix, I believe we should support a default parameter (in plain text, or possibly other text keys - if easy to implement).

```json
{
  "id": "entityInfoBusinessId",
  "value": "Business ID: {0}",
  "variables": [
    {
      "key": "EntityInfo.BusinessId",
      "dataSource": "dataModel.default",
      "default": "(missing value)" // <--------- New parameter
    }
  ]
},
```

This might have consequences for Studio, so we should make sure Studio doesn't clean these up for us. It's also relevant for the possible future language file format, where references to the data model will change at some point (@mjulstein @mijohansen @TomasEng @andrealouisestanderen).

**Comment by FinnurO** [comment]
Kunne man brukt `shortname` brukt i validering, eller samme mønster, for å sette inn default tekst? Eller bruke teksten på feltet man skal hente verdien fra? @olemartinorg

**Comment by olemartinorg** [comment]
Tekstnøklene har ikke en 1-1-relasjon med komponentene, så det blir ikke naturlig å putte `shortName` eller lignende som default-verdi for et oppslag som feiler i disse variablene. Med det sagt, vi har en god workaround for dette problemet på plass nå, som er mer fleksibel enn det jeg foreslo 13. januar.

Vi støtter nå [dynamiske uttrykk](https://docs.altinn.studio/nb/app/development/logic/expressions/) på alle verdiene i `textResourceBindings`. Så for å gjenbruke eksempelet vi har over:

```json
[
  {
    "id": "entityInfoBusinessId",
    "value": "Business ID: {0}",
    "variables": [
      {
        "key": "EntityInfo.BusinessId",
        "dataSource": "dataModel.default"
      }
    ]
  },
  {
    "id": "entityInfoBusinessIdNotFound" // <--- Lagt til
    "value": "Business ID not found",
  }
]
```

Og i layout-fila:
```json
{
  "id": "abc123",
  "type": Header",
  "textResourceBindings": {
    "title": [
      "if"
      ["equals", ["dataModel", "EntityInfo.BusinessId"], null]
      "entityInfoBusinessIdNotFound",
      "else",
      "entityInfoBusinessId"
    ]
  }
}
```

Med andre ord, man kan nå bruke uttrykk for å bytte mellom forskjellige tekstressurser, avhengig av f.eks. verdien som ligger i datamodellen. En manglende verdi vil være lik `null` i uttrykk-språket.

**Comment by olemartinorg** [comment]
Implemented now. See these PRs for details:
- #1444
- #1441 
- #1596
