### ISSUE TITLE
WCAG: Fixed font size (AAA)

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#756]
### Description of the bug

NB: This is a AAA requirement, meaning it is not a part of the mandatory accessibility guidelines i Norway. But anyhow, we should check if this is something that causes problems. [1.4.8 Visual Presentation](https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation.html)

Error message from Siteimprove
![Skjermbilde 2022-12-15 kl  12 46 37](https://user-images.githubusercontent.com/33222679/207851437-0e9466bf-db40-4c60-a179-f86d36ccd918.png)

Font size set to `16px` in this case a paragraph element
![Skjermbilde 2022-12-15 kl  12 51 42](https://user-images.githubusercontent.com/33222679/207852427-fae10a68-4880-4b42-a119-25bac838f2b0.png)

Other text element is set to `1.6rem` (Label/Legend for radiogroup)
![Skjermbilde 2022-12-15 kl  12 52 30](https://user-images.githubusercontent.com/33222679/207852672-416cd110-99ba-4b6e-baee-de746b24475c.png)

- [ ] Is this used in other places as well?
- [ ] What kind of problems can this cause?

### Steps To Reproduce

Check the font-size of a paragraph element

**Comment by bjosttveit** [comment]
Fixed by #1173
