### ISSUE TITLE
When adding more than one *FIXED* ModelError to a field that has an Error, the Error isn't removed even if it's one of the *FIXED* ones

### ISSUE THREAD

**Issue by guttoma** [Altinn/app-frontend-react#764]
### Description of the bug

When adding more than one `*FIXED*` ModelError to a field with an Error, the Error isn't removed (if the field we add the `*FIXED*` ModelError to isn't the one that triggered Validation). It works as expected if you only add one `*FIXED*` ModelError to that field. 

The application we noticed this on is rrh-innrapportering (https://altinn.studio/repos/brg/rrh-innrapportering/issues). We have deployed a temporary fix that avoids the problem (but that isn't ideal for permanent use), so you will need to check out this commit or an earlier one (https://altinn.studio/repos/brg/rrh-innrapportering/commit/578a2f893d000ad1fd934b4727af4d21e79c8808). 

The code is in `/App/logic/Validation/ValidationHandler.cs`, starting on line 190 in the commit linked above. (Direct link: https://altinn.studio/repos/brg/rrh-innrapportering/src/commit/578a2f893d000ad1fd934b4727af4d21e79c8808/App/logic/Validation/ValidationHandler.cs). 

### Steps To Reproduce

1. For any company, choose "Har reelle rettighetshavere"
2. Select "Ja" on "Har personen enten fødselsnummer eller d-nummer? *"
3. Fill in 11 digits on "Fødselsnummer".
4. Fill in the last name of a person you can test with into the "Etternavn" field and that you have the fødselsnummer of. This will make the Validation fail when you click outside the textfield.
5. Fill in the correct fødselsnummer. 
6. The correct information pops up, but the error under the Etternavn-field is still there. 

### Additional Information

![image](https://user-images.githubusercontent.com/57175682/208451204-6de21fcb-0a7f-4451-9155-e8399db14fc3.png)
![image](https://user-images.githubusercontent.com/57175682/208451224-ff20ee1b-2c72-4413-b510-4e9542cd2deb.png)

**Comment by bjosttveit** [comment]
@guttoma En potensiell fiks er merget i main. Var litt vanskelig å teste skikkelig med appen deres siden fødselsnummer-greiene krevde en secret hvis jeg forstod riktig. Så fint hvis du kan teste og komme med tilbakemelding!

**Comment by guttoma** [comment]
@bjosttveit Har prøvd litt av hvert, og ser ut som om feilen fortsatt er her dessverre. 🙁 Funksjonalitet fungerer når vi fjerner kun en `*FIXED*` fra et felt, men med en gang vi prøver å fjerne flere så forsvinner ikke den vi har fikset. 

Vi har en `switch`-block som legger til spesifikk error basert på et error-flagg vi legger inn i funksjonen, og denne `switch`-blocken har en `default` som bare legger til alle mulige errors som kan oppstå her. Vet ikke om det har noe å si at den da prøver å fikse error-flagg som ikke egentlig er satt?

For ordens skyld er versjonen jeg testet med `3.56.0-alpha1`, den nyeste i listen min over forskjellige frontend-versjoner.

**Comment by bjosttveit** [comment]
Ahh, beklager, fiksen er ikke med i den versjonen. Lager en ny preview til deg!

**Comment by bjosttveit** [comment]
Her er en versjon du kan teste: [3.56.0-alpha2](https://github.com/Altinn/app-frontend-react/releases/tag/v3.56.0-alpha2), beklager det.

Og det å legge til `*FIXED*` for error som ikke er satt skal ikke være et problem.

**Comment by guttoma** [comment]
Denne ser ut til å funke! 😄 Takk!
