### ISSUE TITLE
Need a way to refresh the frontend of the attachment component

### ISSUE THREAD

**Issue by allinox** [Altinn/app-frontend-react#787]
## The problem with the current state of things
In certain cases we need to make changes to attachments in backend. E.g. in a form currently being made for Digitale Helgeland, where the user may be required to upload an attachment depending on their answer to a previous question.
If they change their answer after uploading the attachment so that the attachment is no longer required, it should be deleted in backend. However, after the attachment has been deleted, it will still be listed in the attachment component because there is no way to trigger the frontend of the component to refresh.
This can cause problems with confusing error messages and buggy behaviour.

## What I want
I want a way to trigger a refresh of the attachment component frontend from backend.
I can refresh other components in e.g. DataProcessingHandler.cs by returning await Task.FromResult(true), but this does not currently work with the attachment component.

## Examples of problems

By going back and forth between the question determining weather an attachment is required, my attachment has been deleted in the blob, but it doesn't look like it from a user perspective.
Not only is this confusing to a user, but the validatePage-trigger that should stop the user from progressing without a valid attachment is no longer working as wanted.
![image](https://user-images.githubusercontent.com/22012997/128875464-cc26e762-cf0b-4176-b721-76c0b182768f.png)

The user is stopped from sending in the form, but the error message is confusing for the user because it looks like the attachment is already there.
![image](https://user-images.githubusercontent.com/22012997/128876838-6c5e7547-0ff2-4ba4-b5d5-ea13df5899fe.png)

If there is no summary page or if the attachment component is not included in the summary page, there is no indication of what is wrong. Only the generic error message which provides little help to the user, especially in long forms such as this one.
![image](https://user-images.githubusercontent.com/22012997/128877075-976219d0-18cb-4cf4-b9b3-9fbdfbbca847.png)

When navigating back to the page where the failing attachment component is located (after having tried to send it in and gotten an error) the app fails and bluescreens.
![image](https://user-images.githubusercontent.com/22012997/128877558-0f79f2ad-8d0b-495f-9adc-c287754836bf.png)

**Comment by olemartinorg** [comment]
Moving to `app-frontend-react`. I'm assuming this could be implemented by having a trigger that refreshes instance data (and re-maps attachments) _after_ saving updates to that component.

**Comment by bjosttveit** [comment]
This is now possible, see: https://github.com/Altinn/app-frontend-react/issues/1335#issuecomment-2506004466
