### ISSUE TITLE
FileUpload component frontend is not re-rendered when a calculation backend deletes an attachment

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#788]
## Describe the bug
If a calculation backend deletes an attachment

A use case: a checkbox determining if a file upload should be shown and we have some logic backend that cleans up relevant attachments if the user goes from showing file upload to hiding it.

## To Reproduce
1. Go to an app with a fileupload component
2. Trigger a fileupload
3. Trigger some calculation that removes the attachment
4. See that app-frontend still has the relevant file in the redux state

## Expected behavior
We should have some way for a calculation backend to inform that the attachment state has changed. An object passed to app-frontend when a file is removed?

## Additional info
> Add any other relevant context info about the problem here.
> For example OS (Windows, MacOS, iOS), browser (Chrome, Firefox, Safari), device (iPhone, laptop), screen-size, etc.

**Comment by olemartinorg** [comment]
Closing this as duplicate of #787
