### ISSUE TITLE
New properties on ["instanceContext", ...]

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-frontend-react#794]
### Description

We have requirement for a schema to show different questions based on the type of instance owner. If the instance is owned by an org, we ask different questions, than for instances owned by a person with a fødselsnumber, and different again if it's a self identified user with a username.

This seems reasonable to implement using expression, but the `["instanceContext", ]` lookup function is very limited, but the docs suggest that we should add more lookups when a need is identified.

My immediate suggestion would be the following additions
* `"instanceOwnerOrganisationNumber"`
* `"instanceOwnerPersonNumber"`
* `"instanceOwnerUserName"`
* `"instanceOwnerPartyType"`

The last one `PartyType` is probably the biggest change, as it doesn't exist in backend yet, but an enum with the values `Org`, `Person`, `SelfIdentified` or similar would make expressions in the apps clearer.

### Additional Information

I found one instance in the backend where the InstanceOwnerPartyType would be nice https://github.com/ivarne/app-lib-dotnet/blob/a2cbd13f81e17e6f72de6b5e86d715dc7cedb40f/src/Altinn.App.Core/Infrastructure/Clients/Events/EventsClient.cs#L64

**Comment by FinnurO** [comment]
Related to https://github.com/Altinn/app-lib-dotnet/issues/57?

**Comment by ivarne** [comment]
It is kind of related, but the other issue is for how to access this information in the backend when fetching options for dropdown lists. This issue is about accessing the information in dynamics used in layout files. It's a great example for why this enum would be great to have on the `InstanceOwner` class in C# as well.

Looking more at the approach I'm confused how you would get the relevant party information without having the instanceId and lookup the owner. It seems to me like @caroliss should rather try to use the `InstanceIdentifier` to fetch the `Instance`, and use `instance.Owner` to find out what org is actually owning the instance, instead of using the `PartyId` in the cookie, witch will always be the partyid of the logged inn user, never the org he is representing.
