### ISSUE TITLE
Revisors bekreftelse

### ISSUE THREAD

**Issue by knut-olav-hoven-ske** [Altinn/app-frontend-react#804]
### Description

Skattemeldingen for næringsdrivende og selskap skal leveres via tjenester i Altinn3. I noen tilfeller er det krav om at skattemeldingen eller selskapsmeldingen med tilhørende næringsspesifikasjon skal bekreftes av en revisor.

Det er et ønske at revisorbekreftelse løses i samarbeid med Altinn3. Denne siden beskriver behov, løsningsforslag og et utkast til krav til Altinn3 for å støtte dette.

[Revisorbekreftelse - behov, krav til Altinn og løsning - Skatteetaten v68.pdf](https://github.com/Altinn/altinn-studio/files/8897707/Revisorbekreftelse.-.behov.krav.til.Altinn.og.losning.-.Skatteetaten.v68.pdf)

### In scope

Godkjenningsprosess for skattepliktige og revisorer.
Register over statsautoriserte revisorer.
Løsningen blir et samspill mellom Altinn, ID-porten, Skatteetaten og Finanstilsynet.

### Out of scope

Det er foreløpig ikke behov for høy sikkerhet i sporbarhet. En referanse til personidentifikator etter en verifisert identifisering med høyt sikkerhetsnivå er tilstrekkelig.

**Comment by RonnyB71** [comment]
Resolved by https://github.com/Altinn/app-lib-dotnet/issues/192
