### ISSUE TITLE
Repeating groups: ProcessDataWrite mangler info om hva som har trigget eventet

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#810]
### Description of the bug

I ProcessDataWrite eventet så kan jeg vanligvis se hvilket datafelt eller componentid som har trigget ProcessDataWrite via Request Headers. Men hvis jeg sletter en rad i en repgruppe så ser jeg ikke dette.
Hvis vi skal kunne benytte dette til å manipulere data så trenger vi og å vite hva som har trigget dette, enten i form at datamodel felt eller componentid.

### Steps To Reproduce

Opprett en side med repgruppe , stopp koden i ProcessDataWrite og sjekk etter info ved sletting av rad i repgruppen

Man kan hente ut commit b82277c573258348049252ab3b083460db7452b9 fra https://altinn.studio/repos/stian.vestli/ra0244-01
og teste dette her.

**Comment by olemartinorg** [comment]
På sett og vis duplikat av:
- Altinn/app-template-dotnet/issues/55

Det er i alle fall veien vi bør gå for å løse denne saken. Vi kan godt få app-frontend til å sende inn bedre data, men vi må ha et system som takler å motta disse dataene på et fornuftig format. Det må dermed bli en litt større sak (involverer både frontend og backend), så eksakt løsning må avklares.

**Comment by StianVestli** [comment]
Men hvis man skal tilby ny og gammel verdi så er det vel slik at man burde kunne kjøre valideringer og på dette i ProcessDataWrite , det er kanskje mulig i dag?

**Comment by olemartinorg** [comment]
Hvis det blir implementert slik jeg ser for meg, er det ekstra-informasjon sendt av app-frontend, så det blir fullt mulig for en lur bruker å endre det som sendes inn som f.eks. "forrige" verdi. Det bør derfor trås varsomt om en f.eks. skal gjøre serverside-validering basert på det grunnlaget. I tillegg ser jeg vel ikke helt use-caset klart for meg for når en trenger "forrige verdi" som et grunnlag for validering (det bør jo være nå-verdi som valideres, ikke forrige-verdi).

Dette kan være nyttig for å skrive mer effektiv og simplere kode i ProcessDataWrite, og da gjør det kanskje ingenting at en "lur bruker" trikser til dataene slik at datamodellen blir ulogisk/ufullstendig, for slikt skal vel uansett fanges opp i validering før innsending.

**Comment by olemartinorg** [comment]
Det ble diskutert en teknisk løsning såvidt på Daily i dag. Jeg foreslår at vi implementerer dette i app-frontend først, og da at vi sender med endringer siden sist gang til et nytt endepunkt som ikke eksisterer (enda). Hvis vi får 404 tilbake fra backend vet vi at støtte for dette ikke er implementert der enda, så da kan vi huske det til senere og bare fortsette med å sende "gammel type" requester som ikke husker endringer. På den måten kan støtte for dette i backend implementeres etterpå, og man får ikke funksjonaliteten før man har oppgradert backend til en gitt versjon.

I dag sender vi en PUT til `/<org>/<app>/instances/<party-id>/<instance-id>/data/<datamodell-uuid>` for å lagre. Dessverre har den ikke noe versjonsinformasjon i seg, men hvis vi putter det på slutten ved å legge til en `/v2` til sist, ser det ut til å i alle fall gi 404 i dag.

Da kan vi f.eks. bygge en multipart-request som inneholder både fullstendig datamodell _og_ en dot-representasjon av hva tidligere verdier var. Ut nøklene i lista over tidligere verdier har vi dermed også informasjon om nøyaktig hva som har endret seg.

Her er et eksempel på hvordan det kan se ut (her er en request som lagrer nye data, hvor et tekstfelt som hadde verdien "foo bar" har blitt endret til "hello world", og samtidig har det blitt satt inn noe nytt med verdien "whatever" hvor det ikke var noe fra før:

```http
PUT /org/app/instances/12345/my-instance-uuid/data/my-data-uuid/v2
Content-Type: multipart/form-data; boundary=------------------1b413943afaca3410b1ffeb12fc8b367

------------------1b413943afaca3410b1ffeb12fc8b367
Content-Disposition: form-data; name="dataModel"
Content-Type: application/json

{
  "My": {
    "Data": {
      "Model": "hello world",
      "Type": "string",
      "NewItem": "whatever"
    }
  }
}
------------------1b413943afaca3410b1ffeb12fc8b367
Content-Disposition: form-data; name="previousValues"
Content-Type: application/json

{
  "My.Data.Model": "foo bar",
  "My.Data.NewItem": null,
}

------------------1b413943afaca3410b1ffeb12fc8b367
```

Har vi da noe vi kan begynne på, @bjosttveit?
Og vil denne strukturen fungere greit for backend å tolke, og ser endepunktet med `/v2` fornuftig og greit ut, @tjololo @RonnyB71?

**Comment by ivarne** [comment]
I stedet for å ha (potensielt) mange slike spørringer som forventer 404, så kan man ha et nytt api i backend som forteller hva slags versjon som kjører. Eller enda bedre et api som gir en liste over nye features som er støttet. `{"supportsUpdateWithChanges":true}`, så det lett kan utvides fremover.

**Comment by StianVestli** [comment]
Er det endringer i header elementet med denne fiksen? hvis du forstå hva je mener? X-DataField and X-ComponentId finnes fortsatt?

**Comment by olemartinorg** [comment]
`X-DataField` og `X-ComponentId` forsvinner, men ingen fare - denne endringen (i app-frontend) har ingen effekt helt enda. Den neste oppgaven blir å støtte dette på backend, og planen er å gjøre det til en valgfri funksjonalitet man må skru på. Da går man altså bort fra disse headerene (de blir ikke sendt med når man lagrer), men man vil istedenfor kunne hente ut mer detaljert informasjon om hvilke felter i datamodellen som ble endret i en gitt request (og hva som var verdien i disse før endring). Målet er å lage noen verktøy som gjør denne operasjonen enkel og nyttig for deg som app-utvikler. Om man ikke tar i bruk denne nye måten å få med endringer på ved lagring, får man fortsatt med `X-DataField` og `X-ComponentId`, men de forsvinner altså i det øyeblikket man går over til ny løsning.

Se saken for backend-oppgaven her (som må løses før dette kan tas i bruk):
- https://github.com/Altinn/app-lib-dotnet/issues/187
