### ISSUE TITLE
Define how groups and repeating groups should handle titles

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#820]
### Description

In a discussion on Slack it was revealed some weird behavior in how groups and repeating groups handle titles. Lets try to get an overview on this and suggest a way to solve it. 

### Repeating group
The title text today is only visible on the summary view. (Shown over each row in the repeating group)

- Rename todays title to summaryTitle 
- Add a title that can be added to the repeating group. Being visible above the table in the form. (Look into if it should be a `caption`to connect it to the table for screen readers. Might be a issue when there are no table? For example before the user has added a row)
**OR**
- Merge these together as one value. And only show the title once on the summary page. 

- `showAll` Do we need fieldset/legend or title when using this attribute?

### Group
- Add fieldset with legend (and description) The app developer will set a title that will be rendered as the legend for the fieldset. 
- Should it be opt-in? A concern is that an app-developer used group to show/hide fields and might not want them to be visually/coded as semantic group

### Group with panel style
- This is confusing. Should be handled in #1486 

### Tasks

**Design tasks**
- [ ] Design title and description for repeating groups.
- [ ] Check if the title/description for groups needs a re-design

**Comment by hflateland** [comment]
Repeating groups does not get a title and description when using textResoursceBindings. This should behave like input fields, so that you can have the same setup.

Example:

`{
        "id": "Group-3Sdx5m",
        "type": "Group",
        "children": [
          "Input-crOOp9"
        ],
        "maxCount": 20,
        "dataModelBindings": {
          "group": "skjemaSpesifikt.kritikkverdigForhold.hvilkenMyndighet"
        },
        "textResourceBindings": {
          "title": "label.hvilken_offentlig_myndighet",
          "add_button": "label.instans"
        }
      }`

Creates a button with no aparant context:
![image_current](https://user-images.githubusercontent.com/44457738/224001946-2469c09c-a402-4b08-9382-f5860950b80c.png)

Mockup of how it should behave:
![image (33)](https://user-images.githubusercontent.com/44457738/224002246-dd1e4169-bc88-48fd-a7f2-68cc17e2840d.png)
![image (34)](https://user-images.githubusercontent.com/44457738/224002537-7c4f0424-2c85-4631-9d95-6f648bc17574.png)

**Comment by olemartinorg** [comment]
Right now, you _can_ set a `title` on a repeating group, but it will only have an effect when showing that repeating group in a Summary, possibly only with `largeGroup: true`. In that case, the title will be shown above each 'row' in the repeating group, meaning it becomes a title for each row. You can also use dynamic expressions to set different titles per-row.

After #339 I think we should add regular titles and description support to repeating groups, and rename the functionality I mentioned above to something like `summaryRowTitle`.

See also:
- #1278 
- #1234 
- #1188

**Comment by olemartinorg** [comment]
@hannefinnoy @Annikenkbrathen Ser at dere har flyttet litt på denne saken i UX-boardet. Vi anser dette som en potensielt breaking change i app-frontend, så vi har et vindu hvor vi kan gjøre noe med dette nå før jul - og om vi skal tro historikken blir det potensielt over et år til neste vindu hvor vi kan gjøre noe med dette. Ta det gjerne med i betraktningen. Jeg ser for meg ting vi kan gjøre på denne saken uten nødvendigvis å vente på deres input (som å legge til skikkelig støtte for titler i repeterende grupper, som jeg har skrevet om over), men det er ikke sikkert det løser alt.

**Comment by StianVestli** [comment]
Se gjerne på det som er nevnt i denne slack tråden : https://altinn.slack.com/archives/C04CZ3KND6Z/p1698927846741459
