### ISSUE TITLE
Instance with many repeating group wont open

### ISSUE THREAD

**Issue by FTLems** [Altinn/app-frontend-react#822]
### Description of the bug

We have app: KRT-1012a-1 which is abo-schema (We instanciate to users mailbox). 
This app contains a reapeating group: 
![image](https://user-images.githubusercontent.com/90687291/211547143-cfb8fb5d-51ed-452b-b751-822a801368a9.png)

If there are many repeating group (maybe 120 stk), it takes12 sek to open the group after clicking Rediger knapp. In general the entire app is very slow.

Also, it cant handle that many components in summary-page, and the entire summary-page appears white after it should iterate the repeating group here. 
![image](https://user-images.githubusercontent.com/90687291/211548282-968a1af1-5ecb-4e56-a75c-587bd638036e.png)

The instance is: 
/instance/50164456/78c06a1a-9684-4af5-bc39-30b243733bb3

 Note. The repeating groups are empty and only contain one field of data (component 5.1). User has to fill in the rest. 

### Steps To Reproduce

1. Find the instance and try to run it ?

**Comment by olemartinorg** [comment]
Very related to #345, and in some ways related to #377.

Nice to know about this limitation, and there are been thoughts and plans to run expressions a little less often (i.e. by doing it once and passing around the resolved nodes using a top-level react context).

Is there an easy way for me to reproduce this issue? I don't have access to your data model, so I'd love to get my hands on something I can use to replicate this (without creating 120+ rows myself).

**Comment by olemartinorg** [comment]
We've discussed this a bit further on Slack, and I now have some test instance data for me to reproduce the issue. This issue is currently blocking the release of this app, which should be in production on 01.feb, so we should have a fix (or workaround) in time before that.

**Comment by FTLems** [comment]
Thank you for prioritizing this issue. I would love to test this, but have some issue with downloading yarn on my computer to run the frontend localy. Are there a relase that I can hook on to?

**Comment by FTLems** [comment]
Thanks for prioritizing this.  Just tried this branch yesterday, and it was significant improvent. I agree that this is a workable state and we can use this for our app. 👍
