### ISSUE TITLE
Dynamic expressions "hidden" does not work on components located in a group.

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-frontend-react#826]
### Description of the bug

When I try to use the expression "hidden" which points to a component that is included in a Group, the expression does not work.

1. Group containing radio button component.
```
{
        "id": "d8a834ba-88e4-433f-8278-0d0474960cd1",
        "type": "Group",
        "children": [
          "fdacd8f7-a563-4d55-8dc6-27320ba44e76",
          "172b8fbb-bea6-4ac6-8979-429ba5823d87",
          "925f5744-d164-4ce0-9415-7237ad87f2cc"
        ],
        "textResourceBindings": {
          "title": "xDnqTKrIwvuE"
        },
        "maxCount": 0,
        "dataModelBindings": {}
      },
      {
        "id": "fdacd8f7-a563-4d55-8dc6-27320ba44e76",
        "type": "RadioButtons",
        "textResourceBindings": {
          "title": "CQVGjiuhq9Qx"
        },
        "dataModelBindings": {
          "simpleBinding": "Skjemadata.brukSosialeMedia.sosNettverkJaNei"
        },
        "optionsId": "jaNei",
        "required": false
      },
```

2. This Radio button should be hidden using the  `"hidden":` Expressions that point ot the component `"fdacd8f7-a563-4d55-8dc6-27320ba44e76"` that is a part of the code above.
```
{
        "id": "3e6a0cfd-a41f-4ee2-99d8-e81cbd241ee6",
        "type": "RadioButtons",
        "textResourceBindings": {
          "title": "Scesd4hEzy8V"
        },
        "dataModelBindings": {
          "simpleBinding": "Skjemadata.brukSosialeMedia.brukAvOvennevnte.utviklingJaNei"
        },
        "optionsId": "jaNei",
        "required": false,
        "hidden": [
          "notEquals",
          [
            "component",
            "fdacd8f7-a563-4d55-8dc6-27320ba44e76"
          ],
          1
        ]
      },
```

3. Feilmelding i konsollen.
![image](https://user-images.githubusercontent.com/75472603/211796021-86128644-2e1c-4730-b029-4998386049d0.png)

4. The expression work when i remove the  `"fdacd8f7-a563-4d55-8dc6-27320ba44e76"` from the Group.

### Steps To Reproduce

1. clone this repo  https://altinn.studio/repos/ttd/ra-0419/src/branch/errorHidden
2. run the app local.
3. page  Bruk-av-nettside.json contain the expression that fails.

**Comment by bjosttveit** [comment]
I have looked into this a bit, and it appears that the problem lies in the `LayoutNode.closest()`-method. This function only looks at itself, its immediate siblings and then traverses upwards. This means that if, as in this case, the component you are looking for is not an immediate sibling of any of the parent nodes going upwards, but instead the child of such a sibling, it will not be able to find it.

@olemartinorg The comment above the `closest()`-function clearly states that it only checks upwards through the hierarchy, but I suppose you would expect the `component`-expression to be guaranteed to find the component as long as it is properly defined?

@andreas-didriksen A workaround is simply referring to the dataModel directly instead of referencing components. But it looks like you have figured that out already.

**Comment by olemartinorg** [comment]
@bjosttveit Yup, I agree with your assessment. I don't think we should change the meaning of `closest()`, but I guess the expressions engine should make one more attempt at finding a component if it's not among the closest ones.

Just assuming, but I think this could work in the `component` lookup function (defined in `src/featues/expressions/index.ts`):

```diff
       const node = this.failWithoutNode();
-      const component = node.closest((c) => c.id === id || c.baseComponentId === id);
+     const closestComponent = node.closest((c) => c.id === id || c.baseComponentId === id);
+     const component = closestComponent || (node instanceof LayoutPage ? node.findById(id) : node.top.findById(id));
       const binding = component?.item?.dataModelBindings?.simpleBinding;
```

If you want to look into it, make sure to create a shared unit test for the expressions engine (look into `src/features/expressions/shared-tests/functions/component/`). Bonus points if you copy the tests over to `app-lib-dotnet` and make sure they run there as well! I usually use [Meld](https://meldmerge.org/) for diffing the folders in the two projects when I sync tests between them.

**Comment by bjosttveit** [comment]
Something like that should do it

**Comment by bjosttveit** [comment]
@andreas-didriksen this should be fixed now in `main`.
