### ISSUE TITLE
tabindex=0 on table component

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#830]
### Description of the bug

Might be an issue for our design system?

When testing our keyboard navigation I noticed that some elements on the table gets tab focus without having any functionality

**Focusable elements:**
- The whole table
- header
- footer

### Steps To Reproduce

Try tabbing trough a page with a table

**Comment by bjosttveit** [comment]
Yes, this is from the design system. Looks like table rows get a `tabIndex=0` (focusable) when they are in the header or footer of the table. I suspect this has something to do with being able to tab into sorting controls for header and pagination controls for the footer.
