### ISSUE TITLE
Repeating groups: ProcessDataWrite, sletting av data fører til at data henger igjen i den repeterende gruppa

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#836]
### Description of the bug

Har en regruppe med en undergruppe, dette bygges opp i kode bak utfra valg som bruker gjør fra en checkliste. Dette funker som det skal, men hvis bruker unchecker i lista så sletter jeg data i koden bak og, men da henger det igjen en rad i repgruppen, dvs en tom rad, data er vekke fra data modell. Se vedlagt gif.
![repgruppeheng](https://user-images.githubusercontent.com/91887041/212097363-33633344-7294-4ed4-bcb2-df462d411bcb.gif)

slack: https://altinn.slack.com/archives/C02EVE4RU82/p1673532394133469

### Steps To Reproduce

Repo: https://altinn.studio/repos/stian.vestli/ra0244-01.git commit: a1c2ad68197774863a919ad7fa1e626e1a26ef32

Kjør skjema og gjenskap likt som GIF.

**Comment by bjosttveit** [comment]
Hvis ikke det er noe feil i appen så kan det være at feilen ligger i backend.
Ved ProcessDataWrite returnerer backend en liste over endrede felter, når man bruker sjekkboks for å legge til et element så ser den slik ut:

![Image](https://user-images.githubusercontent.com/47412359/212295740-52bbafbe-a0b6-4741-a660-00c82253b9c0.png)

Og når man fjerner det igjen ser det slik ut:

![Image](https://user-images.githubusercontent.com/47412359/212295870-18d8d09c-7d5d-40e4-b547-37619ab45614.png)

Den forteller altså ikke frontend om like mange felter som skal fjernes som den la til i utgangspunktet, noe som fører til at det ligger igjen litt greier i formData. Spesifikt er det den nøstede dataen som henger igjen

**Comment by bjosttveit** [comment]
@StianVestli Merget i main. Kommer i neste nuget-versjon 👍 

Testet på appen din at det funker som forventet.
