### ISSUE TITLE
Datepicker: Duplicate validation on `"triggers": ["validation"]`

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#850]
### Description of the bug

When using Datepicker in combination with `"triggers": ["validation"]`, we seem to send the data for validation on server even in cases where we know the date format is not valid yet. When the data model has been set up with `xsd:date` as the type, the generated C# class contains a regex the date needs to match - but as the data is invalid, the regex does not match, and we get a generic error back from the server complaining about the data not matching a regex. This error is not meaningful for users:

![birthdate-validation-regex](https://user-images.githubusercontent.com/700139/214005412-106da790-7959-4167-b613-057e4538bf89.png)

We should probably automatically ignore this specific regex validation message for datepicker fields, thus making sure full page (or all-page) validation still works as expected (even when the datepicker field has not been filled completely).

### Steps To Reproduce

1. Set up a Datepicker
2. Add `"triggers": ["validation"]` on it
3. Bind it to a location in the data model using `xsd:date`
4. Observe it showing the regex in the validation message when filling out the date

### Additional Information

- https://altinn.slack.com/archives/C02ESDSGPN1/p1674216071117389
- https://altinndevops.slack.com/archives/C01LVQ8B1L1/p1674220722845989

**Comment by ivarne** [comment]
Validating a C# `DateTime` with that regex is also kind of useless. You'd get a serialization error long before it has a chance to run.

**Comment by bjosttveit** [comment]
Should have been solved by https://github.com/Altinn/app-frontend-react/pull/1281

**Comment by bjosttveit** [comment]
This specifically is no longer an issue, but we still have other related issues with datepicker validation, see https://github.com/Altinn/app-frontend-react/issues/2319
