### ISSUE TITLE
Dropdown menu for multiple choises. Dosen't work properly when using Arrow keys or cursor movement.

### ISSUE THREAD

**Issue by Zmrihawy** [Altinn/app-frontend-react#868]
### Description of the bug

MultipleSelect dropdown.  When using Arrow keys or cursor movement, it becomes unclear where you are in the list.

### Steps To Reproduce

Try tabbing trough a page with MultipleSelect dropdown.

**Comment by Febakke** [comment]
Thanks for reporting this! 🙌 We have more problems with this component and are about to fix this in #831
