### ISSUE TITLE
Frontend laster ikke tekst fra datamodell satt i ProcessDataRead bestandig

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#895]
### Description of the bug

Har en datamodell felt som er koblet til tekst variabel som parameter. innholdet i denne settes via et async funksjonskall i dataread.
Dette gir til tider en feil som gjør at den satte teksten ikke vises i frontend.

![image](https://user-images.githubusercontent.com/91887041/216941196-f1d29c3a-012a-48a2-a234-c88b97dff226.png)

### Steps To Reproduce

Repo: https://altinn.studio/repos/ssb/ra1000-01.git
Commit: f22db80e848a7a79e61fa3c65df75bb1ac33eda9

**Comment by olemartinorg** [comment]
Testet og forsøkt reprodusert, men dette ser ut til å heller være forårsaket av manglende prefill-data for en gitt instans + manglende `await` i `ProcessDataRead` som gjør at requesten kan fullføres _før_ prefill har blitt lest og brukt til å sette disse verdiene i datamodellen.

Lukkes, ref diskusjon på Slack:
- https://altinn.slack.com/archives/C02EVE4RU82/p1675672131314559
