### ISSUE TITLE
Replace usages of AltinnTable with newer Table component

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#897]
We currently use `AltinnTable` in the instance selection screen, and in the Likert layout component. These two should be rewritten to use the newer [Table component](https://designsystem.altinn.studio/?path=/story/components-table--basic-table) from the design system (or, if moved to the DigDir design system, we should use components from there instead).

**Comment by bjosttveit** [comment]
Related to https://github.com/Altinn/app-frontend-react/issues/101
