### ISSUE TITLE
WCAG: Opening and closing repeating groups need to be read by screen readers

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#901]
### Description of the bug

When we build our own components we have to describe how the component behave so that assistive tools have something base their feedback on to their users. In this instance we dont tell the user if the repeating group is open or closed. 

Since we use a button to open and close another component I think we need to use this method: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#buttons

### Steps To Reproduce

1. Go to an app with a repeating group
2. Use a screen reader and try to toggle a group open and closed.
3. The screen reader should not indicate that anything has happened

**Comment by bjosttveit** [comment]
Solved by https://github.com/Altinn/app-frontend-react/pull/900?
