### ISSUE TITLE
Feil på postnummerfelt (adressekomponent)

### ISSUE THREAD

**Issue by ChristineSunnevaag** [Altinn/app-frontend-react#944]
### Description of the bug

Når bruker skriver inn feil input i feltet for postnummer (f.eks. feil antall siffer eller bokstaver) og trykker seg videre i skjemaet, feiler skjemaet og bruker får opp side med beskjed om at en ukjent feil har oppstått. 
Om man refresher siden funker ting igjen.

### Steps To Reproduce

1. Forsøk å skrive inn postnummer bestående av f.eks. kun tre siffer eller inkludert bokstaver.
2. Klikk "neste" nederst på siden - får da beskjed om at en ukjent feil har oppstått

**Comment by bjosttveit** [comment]
Fixing this specific issue seems to be quite simple. However, I suggest that the validation logic should be moved outside of the react component and handled in a better way when dealing with this issue.

**Comment by bjosttveit** [comment]
Yes, in v4 this has been moved from the react component into the actual validation logic, so it should now stop the user from submitting if the zip-code is incorrect, and no longer cause a crash.
