### ISSUE TITLE
Button to expand app modal to full width

### ISSUE THREAD

**Issue by lorang92** [Altinn/app-frontend-react#95]
## Description
For some use cases the current app modal is too narrow to present the data to the user in a reasonable way. We should support expanding the modal to fit the whole width.

See figma scetches: https://www.figma.com/file/wnBveAG2ikUspFsQwM3GNE/Altinn-Studio-Apps?node-id=15394%3A23195

## Screenshots
![image](https://user-images.githubusercontent.com/10416981/169052887-bec4721b-0501-4399-85b9-61d916d97a2a.png)

## Acceptance criteria

- Expand/minimize button enabled 
## Specification tasks

- [x] Development tasks are defined
- [ ] Should this be default or opt-in (setting in settings.json?)

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by FinnurO** [comment]
#272
