### ISSUE TITLE
Summary - 'excludedChildren' feature does not exclude children

### ISSUE THREAD

**Issue by madsenandreas** [Altinn/app-frontend-react#950]
### Description of the bug

**Synopsis**
The docs contain a description on how to exclude chosen children of a group from appearing in the summary (https://docs.altinn.studio/app/development/ux/pages/summary/). The chosen children to be excluded still appear in the summary in both the local environment and in tt02. This is tested by me and another user, the room for doing this wrong seems rather slim so we suspect that there is a bug.

### Steps To Reproduce

Link: https://docs.altinn.studio/app/development/ux/pages/summary/

**Summary for groups**
It is also possible to exclude certain (child) components from displaying in the group summary by using the excludedChildren property. This property should be set to an array with component IDs to exclude.

**Comment by bjosttveit** [comment]
@madsenandreas this should now be fixed and is available in [v3.58.0-alpha4](https://github.com/Altinn/app-frontend-react/releases/tag/v3.58.0-alpha4). Could you see if this solved your problem?
