### ISSUE TITLE
Pass fixed query parameters to dynamic options

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-frontend-react#957]
### Description

Currently we can add a mapping configuration to an field using options ref https://docs.altinn.studio/app/development/data/options/#pass-query-parameters-when-fetching-options. This will add a named query parameter with the value of the mapped datamodel. This in turn can be picked up by another field using dynamic codelists providing a way to filter it's values.

Some dynamic codelists provide large hierarchical structures including sorting, filtering and other options to display only the relevant options for the client.

I would like to be able to add fixed query parameters to as part of the options/codelist configuration allowing for the same optionsId to be used on multiple fields but with different parameters effectively making the dynamic codelist provider returning different values. 

### Additional Information

This could be done by using the current mapping configuration but allowing for mappings not in the datamodel.

```json
  "mapping": {"level": "1"}
```
Level in this case is just the name of the query parameter to be added and the value is constant and not based on the datamodel.

**Comment by ivarne** [comment]
The rule should probably not be
```
if(string is valid datmodel key)
then (lookup value in data model)
else (send raw value)
```
because that would make validations of the lookup impossible.

maybe support expressions that evaluate to string instead? That way a literal would be `["1"]` instead and altinn studio could convert the old strings to `["dataModel","key.value"]` for consistency?

**Comment by RonnyB71** [comment]
The example provided is necessarily not something that needs to be implemented as-is. It was just the closest thing to the needed behavior. And given your point on validation, it should probably be a separate configuration or expression support as suggested.
