### ISSUE TITLE
PDF is generated for the error page.

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-frontend-react#970]
### Description of the bug

This PDF is rather useless.

![image](https://user-images.githubusercontent.com/131616/222737965-007af5cf-c39c-4dc2-b49e-c5c70528a20b.png)

Seems like `browserless/puppeteer` don't have a way to signal that a page load has crashed, so it just needs to time out when `#readyForPrint` is not found. Unfortunately it is displayed on the error page, so the user will get a pdf with `Ukjent feil`
![image](https://user-images.githubusercontent.com/131616/222743089-a7ba3f1c-84d8-49c8-a285-ed6e5231063a.png)

Not sure if a timeout is handled well enough in `app-lib-dotnet` to be better than the empty pdf.

### Steps To Reproduce

Generate a pdf with a layout that crashes pdf generation.

**Comment by bjosttveit** [comment]
Does the entire form crash with "Ukjent feil" or only PDF-generation? And do you get the same result when using preview in the browser?

**Comment by ivarne** [comment]
Yes, it's one of your standard missing null checks when `textResourceBindings` is empty for a component, but this one is only triggered when displaying pdf. I'm trying to reduce the example down to report a separate issue on the crash.

This issue is that you actually generate a PDF that looks valid and just happens to be empty, and totally useless.
