### ISSUE TITLE
Schema validation does not support "flat" data model

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-frontend-react#975]
### Description of the bug

- Relevant slack thread: https://altinndevops.slack.com/archives/CDU1S3NLW/p1678098290514349

Currently, app-frontend requires a definite "root" object in the data model in order to perform validation against the json schema. You simply cannot have multiple properties in the top level of the data model. This limitation is probably not necessary, and since it is easier than ever to create datamodels from scratch in studio, it would be nice to remove this limitation.

![image](https://user-images.githubusercontent.com/47412359/223394102-ad9f0e4b-bab0-4b2a-958f-b414d273ab48.png)

### Steps To Reproduce

.

**Comment by olemartinorg** [comment]
Should have been fixed now in #1473
