### ISSUE TITLE
Alternative summary-title

### ISSUE THREAD

**Issue by johlie** [Altinn/app-frontend-react#978]
### Description

Today the title on the summary-component is the title from the component that is summarized. Would like the option to have a alternative title on summary-component. An example is if the component does not have any title but you want to show a title in the summary page and pdf to make it easier for the user to know what the field was about.
If you just add an paragraph above the the summary component it looks weird. Here is an example of an summary-component where the component does not have a title. One of the pictures is without a paragraf and one is with a paragraph(look at the top row).

![image](https://user-images.githubusercontent.com/48760352/223724029-b27b6b42-74fe-45c4-9957-b7c41681afbb.png)
![image](https://user-images.githubusercontent.com/48760352/223724110-44651e6c-2d16-48af-a82c-6154957af491.png)

Link to slack thread about the issue: https://altinn.slack.com/archives/C02FK32SFA4/p1678275843560759

**Comment by olemartinorg** [comment]
Is this solved now, as `summaryTitle` arrived in #1278? 🤔 Closing this issue as I expect this now has a valid solution, but please correct me if I'm wrong, @johlie.
