### ISSUE TITLE
Validation messages from backend show up too early (wrong page), instead of on relevant page

### ISSUE THREAD

**Issue by mariannestor** [Altinn/app-frontend-react#979]
### Description of the bug

We are having trouble with the timing of a couple of validation messages from backend on this app: https://altinn.studio/repos/krt/krt-1007a-1. They show up too early, on wrong pages, instead of the relevant page. I.e. the messages here show up on page 1, but are supposed to pop up when clicking on the "Next"-button on page 6. "Premier og inntekter fra megling" - see the screenshot.

All of the pages have ValidatePage triggers on the next-buttons, and none of them have ValidateAllPages (and neither should they). 

### Steps To Reproduce

1. Open the app locally and login as any business user.
2. Select "Ja" on question 1.2.2 and 1.4.1 to open more pages. 
3. See the validation messages regarding page 6 "Premier og inntekter fra megling" show on the bottom of the page (still first page). (As shown in the screenshot.)

### Additional Information

![image](https://user-images.githubusercontent.com/113341248/223725426-3a36936d-1c58-4f02-8e98-867bc4f4d821.png)

**Comment by FTLems** [comment]
Can we get tag org/krt on this one

**Comment by olemartinorg** [comment]
I reported #1472 as a duplicate, and there's some details in that issue as well.

**Comment by cammiida** [comment]
Får ikke reprodusert dette i v4. 

Det nærmeste jeg kommer er om man allerede har åpnet en annen side via knappene for å velge side i stedet for navigasjonsknappene. Hvis man da prøver å navigere gjennom navigasjonknappene vil man få opp feil for alle sidene man allerede har åpnet. Det er i så fall ikke en bug, men kan potensielt forbedres en gang :)
