### ISSUE TITLE
Validation: Hide error message when the content is corrected by user

### ISSUE THREAD

**Issue by mrosvik** [Altinn/app-frontend-react#98]
## Description
_As a user I want the error message to disappear immediately when I correct the content, so that I know its correct without having to leave the field to check._ 

## Design
https://www.figma.com/file/Pvti3aRcOwH0k5Z7DrLznk/Arbeidsomr%C3%A5de%3A-Altinn-Studio-APPS?node-id=2545%3A50628

https://user-images.githubusercontent.com/1464915/158812922-98a7ccda-17b9-4a08-abf2-088d953cc5d3.mov

## Development tasks
- [ ] Check if this is possible to combine with onBlur
- [ ] Both the messages connected to the field and the messages in the summarybox should dissapear when fixed.
- [ ] When the summary-box has no error left it should turn green. 

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by olemartinorg** [comment]
I made a quick prototype of this, as I've noticed the same thing. My annoyances have also included:
 - That I have to go to the next input field in a form before I'm reminded I did something wrong (at that point my attention has moved on to the next field, as I believed my input was correct)
 - Data is only saved in the instance when I blur the field. This means that if I spend the day writing my novella in a TextArea, all may be lost if I never tabbed out of the field at some point.

With the changes in the [feature/98-save-on-change](Altinn/app-frontend-react/tree/feature/98-save-on-change) branch, data on Input components will be saved 500 milliseconds after you last typed something. Meaning we won't save the data or run validations per-character, but we'll run validations and save the data whenever you stop typing for a short while.

I believe this is a better solution, at least parts of it, but it leads to new issues:
- If I typed something, changed my mind and deleted it, I'm now reminded (quite harshly) that the field is required - even though I'm still thinking of what I'm supposed to write. Maybe we should delay that specific validation until you tab out of the field.
- It still does not feel 'immediate', but that might just be something we'll need to balance. We could also check more quickly if there are validation errors and you started typing something else.

If possible, please take a look at the proposed solution, and we'll iterate until perfect!
