### ISSUE TITLE
App datamodel is not loaded in receipt page after page refresh

### ISSUE THREAD

**Issue by lasseklovstad** [Altinn/app-frontend-react#980]
### Description of the bug

Before page reload:
![image](https://user-images.githubusercontent.com/43168787/223733812-9543b6bd-c749-4fc3-b433-5a3eb6519559.png)

After page Reload:
![image](https://user-images.githubusercontent.com/43168787/223733959-969d7264-c6d0-453c-8c74-b326e360d384.png)

### Steps To Reproduce

1. Create app with translations and a simple receipt page
2. Go to receipt page and refresh

### Additional Information
Our text resources reference avariable in the datamodel and on refresh the datamodel is not fetched when we are at the receipt page. Before the page is reloaded the datamodel are kept in memory from before.

**Comment by bjosttveit** [comment]
This should have been fixed by https://github.com/Altinn/app-frontend-react/pull/1721. Please reopen if the issue still exists.
