### ISSUE TITLE
Timing issue regarding updating the data model (Stateless)

### ISSUE THREAD

**Issue by ZuperNova** [Altinn/app-frontend-react#989]
### Description of the bug

With a stateless app and under heavy load or with a slow internet connection there seems to be an issue with updating the data model. With a question that has multiple options (radio buttons) when picking options with a fast pace will result in wrong option to be checked.

It seems that all requests fired after the first request has completed will be ignored.
![bug](https://user-images.githubusercontent.com/5908907/223390357-f4472a0c-f497-4840-ba7b-e9ecee8b0a38.gif)

### Steps To Reproduce

There are two scenarios in which both has a schema with a question that has multiple options (radio buttons).
**Scenario 1**

1. Pick an option.
1. Make sure slow3G is enabled in your browser.
2. Pick a new option and swiftly pick a new one right after, both for the same question.
3. This will result in the first option in step 2 to be checked.

**Scenario 2**

1. Pick an option.
2. Make sure slow3G is enabled in your browser.
3. Pick a new option and swiftly pick a new one right after and then hit "Next page".
5. When going back to the previous page the first option picked in step 3 is checked.

### Additional Information

![bug-slow3G](https://user-images.githubusercontent.com/5908907/223383459-e87bf5e7-0b8b-40b6-9be0-fd0631f2b64a.gif)
![bug-slow3G-next-page](https://user-images.githubusercontent.com/5908907/223385321-57c3de78-77cf-4339-8d05-1c3b2b8c1570.gif)

**Comment by olemartinorg** [comment]
Thanks for the bug report, @ZuperNova. Just to make sure, am I correct in assuming you tested this withing the last couple of weeks? I fixed quite a few problems like these in #899, which was released in [v3.58.0](https://github.com/Altinn/app-frontend-react/releases/tag/v3.58.0).

**Comment by ZuperNova** [comment]
@olemartinorg In our repo I can see that this js is included in Index.cshtml: 
`https://altinncdn.no/toolkits/altinn-app-frontend/3/altinn-app-frontend.js`. Is this the latest? Or do I need to change it to: `https://altinncdn.no/toolkits/altinn-app-frontend/3.58.0/altinn-app-frontend.js`

**Comment by olemartinorg** [comment]
Yup, `/3/` means you're loading the latest one of the major version 3. Thanks!
